// sd_provision_top.v — DEDICATED provisioning bitstream top level.
//
// Standalone minimal design for one job: bulk-writing a disk image onto
// the board's SD card over JTAG, fast.  It is NOT wired into fpga_top —
// build it with `make sd-provision-impl`, JTAG-load the resulting
// bitstream transiently, run `sd-write-fast` from tools/jtag_repl.tcl,
// then re-program the board with the normal fpga_top bitstream.  Nothing
// persists after reprogramming (the SD card contents excepted, which is
// the point).
//
// Contents (and deliberately nothing else — no CPU, no video, no DDR,
// no peripheral bus):
//   * IBUFDS_GTE4 + BUFG_GT on the AB7/AB6 100 MHz MGTREFCLK pair —
//     same proven fabric-clock lineage as the real-MIG fpga_top build.
//   * clk_rst reset synchroniser (INPUT_BUFFERED — clock already comes
//     via BUFG_GT).
//   * prov_jtag_axi — Xilinx JTAG-to-AXI master IP, generated by
//     synth/sd_provision.tcl with CONFIG.M_HAS_BURST=1 (unlike
//     fpga_top's debug_jtag_axi): one hw_axi transaction moves up to
//     256 x 32-bit beats = 1 KiB.  This is the entire speed story —
//     see rtl/board/sd_bulk_writer.v.
//   * sd_provision_core — boot_fsm card init + sd_bulk_writer
//     (128 KiB staging BRAM, CMD25 bulk write, CMD18 CRC verify) +
//     sd_spi_mux + sd_spi.
//
// Clocking: 100 MHz core clock (BUFG_GT DIV=0 off the 100 MHz refclk).
// sd_spi HS divider then gives 25 MHz SPI — SD wire time for a 10 MiB
// image is ~5 s, negligible against the JTAG transfer time.
//
// LEDs: led[0] card_ready, led[1] writer_busy, led[2] init/op error,
//       led[3] heartbeat.
//
// Verilog-2005 (+ Xilinx primitives), synchronous active-high rst.

`default_nettype none

module sd_provision_top (
    // 100 MHz MGTREFCLK pair (AB7/AB6) — see synth/sd_provision.xdc.
    input  wire       fabric_clk_p,
    input  wire       fabric_clk_n,

    // Active-low board reset push-button (T19).
    input  wire       cpu_resetn,

    output wire [3:0] led,

    // SD card SPI pins.
    output wire       sd_clk,
    output wire       sd_mosi,
    input  wire       sd_miso,
    output wire       sd_cs_n
);

    // ──────────────────────────────────────────────────────────────────
    // Clocking — IBUFDS_GTE4 → BUFG_GT (DIV=0) → 100 MHz core_clk.
    // Mirrors the real-MIG fpga_top fabric-clock path (ODIV2 may not
    // drive fabric loads directly on KU5P; it must go through BUFG_GT).
    // ──────────────────────────────────────────────────────────────────
    wire fabric_clk_gt_unused;
    wire fabric_clk_odiv2;
    wire core_clk;

    IBUFDS_GTE4 #(
        .REFCLK_EN_TX_PATH (1'b0),
        .REFCLK_HROW_CK_SEL(2'b00),
        .REFCLK_ICNTL_RX   (2'b00)
    ) u_fabric_clk_ibufds_gte4 (
        .I     (fabric_clk_p),
        .IB    (fabric_clk_n),
        .CEB   (1'b0),
        .O     (fabric_clk_gt_unused),
        .ODIV2 (fabric_clk_odiv2)
    );

    // CLR from the raw reset pin — same rationale as fpga_top_clocks.vh:
    // a board reset must also clear the BUFG_GT divider state machine so
    // the clock comes back in a clean phase.
    wire fabric_gt_clr = ~cpu_resetn;

    BUFG_GT u_fabric_core_bufg_gt (
        .I      (fabric_clk_odiv2),
        .CE     (1'b1),
        .CEMASK (1'b0),
        .CLR    (fabric_gt_clr),
        .CLRMASK(1'b0),
        .DIV    (3'd0),
        .O      (core_clk)
    );

    // ──────────────────────────────────────────────────────────────────
    // Reset — debounce the push-button, then clk_rst's async-assert /
    // sync-deassert chain.  No DDR here, so init_done is tied high.
    // ──────────────────────────────────────────────────────────────────
    wire cpu_resetn_db;

    reset_debounce #(
        .DEBOUNCE_CYCLES (1024)
    ) u_cpu_resetn_db (
        .clk      (core_clk),
        .raw_in_n (cpu_resetn),
        .out_n    (cpu_resetn_db)
    );

    wire core_rst;

    clk_rst #(
        .CLK_DIVIDE     (1),
        .INPUT_BUFFERED (1)      // core_clk already buffered via BUFG_GT
    ) u_clk_rst (
        .clk_in           (core_clk),
        .rst_in           (~cpu_resetn_db),
        .init_done        (1'b1),
        .dbg_full_rst_in  (1'b0),
        .clk_out          (),
        .rst_out          (core_rst),
        .soc_full_rst_out (),
        .core_rst_bank    (),
        .soc_full_rst_bank()
    );

    // ──────────────────────────────────────────────────────────────────
    // JTAG-to-AXI master (burst-capable) → sd_provision_core.
    //
    // PROV_JTAG_AXI is defined by synth/sd_provision.tcl for the real
    // bitstream.  Verilator lint builds leave it undefined and tie the
    // AXI face off (the unit tb drives sd_provision_core directly).
    // ──────────────────────────────────────────────────────────────────
    wire [31:0] jaxi_awaddr;
    wire [7:0]  jaxi_awlen;
    wire        jaxi_awvalid;
    wire        jaxi_awready;
    wire [31:0] jaxi_wdata;
    wire [3:0]  jaxi_wstrb;
    wire        jaxi_wlast;
    wire        jaxi_wvalid;
    wire        jaxi_wready;
    wire [1:0]  jaxi_bresp;
    wire        jaxi_bvalid;
    wire        jaxi_bready;
    wire [31:0] jaxi_araddr;
    wire [7:0]  jaxi_arlen;
    wire        jaxi_arvalid;
    wire        jaxi_arready;
    wire [31:0] jaxi_rdata;
    wire [1:0]  jaxi_rresp;
    wire        jaxi_rlast;
    wire        jaxi_rvalid;
    wire        jaxi_rready;

`ifdef PROV_JTAG_AXI
    wire [0:0] jaxi_awid_unused;
    wire [2:0] jaxi_awsize_unused;
    wire [1:0] jaxi_awburst_unused;
    wire       jaxi_awlock_unused;
    wire [3:0] jaxi_awcache_unused;
    wire [2:0] jaxi_awprot_unused;
    wire [3:0] jaxi_awqos_unused;
    wire [0:0] jaxi_arid_unused;
    wire [2:0] jaxi_arsize_unused;
    wire [1:0] jaxi_arburst_unused;
    wire       jaxi_arlock_unused;
    wire [3:0] jaxi_arcache_unused;
    wire [2:0] jaxi_arprot_unused;
    wire [3:0] jaxi_arqos_unused;
    // Tie m_axi_bid/m_axi_rid through named 1-bit wires, matching
    // fpga_top_debug_host.vh's debug_jtag_axi instance style, rather
    // than an inline literal in the port map.
    wire [0:0] jaxi_bid_tie = 1'b0;
    wire [0:0] jaxi_rid_tie = 1'b0;

    prov_jtag_axi u_prov_jtag_axi (
        .aclk          (core_clk),
        .aresetn       (~core_rst),
        .m_axi_awid    (jaxi_awid_unused),
        .m_axi_awaddr  (jaxi_awaddr),
        .m_axi_awlen   (jaxi_awlen),
        .m_axi_awsize  (jaxi_awsize_unused),
        .m_axi_awburst (jaxi_awburst_unused),
        .m_axi_awlock  (jaxi_awlock_unused),
        .m_axi_awcache (jaxi_awcache_unused),
        .m_axi_awprot  (jaxi_awprot_unused),
        .m_axi_awqos   (jaxi_awqos_unused),
        .m_axi_awvalid (jaxi_awvalid),
        .m_axi_awready (jaxi_awready),
        .m_axi_wdata   (jaxi_wdata),
        .m_axi_wstrb   (jaxi_wstrb),
        .m_axi_wlast   (jaxi_wlast),
        .m_axi_wvalid  (jaxi_wvalid),
        .m_axi_wready  (jaxi_wready),
        .m_axi_bid     (jaxi_bid_tie),
        .m_axi_bresp   (jaxi_bresp),
        .m_axi_bvalid  (jaxi_bvalid),
        .m_axi_bready  (jaxi_bready),
        .m_axi_arid    (jaxi_arid_unused),
        .m_axi_araddr  (jaxi_araddr),
        .m_axi_arlen   (jaxi_arlen),
        .m_axi_arsize  (jaxi_arsize_unused),
        .m_axi_arburst (jaxi_arburst_unused),
        .m_axi_arlock  (jaxi_arlock_unused),
        .m_axi_arcache (jaxi_arcache_unused),
        .m_axi_arprot  (jaxi_arprot_unused),
        .m_axi_arqos   (jaxi_arqos_unused),
        .m_axi_arvalid (jaxi_arvalid),
        .m_axi_arready (jaxi_arready),
        .m_axi_rid     (jaxi_rid_tie),
        .m_axi_rdata   (jaxi_rdata),
        .m_axi_rresp   (jaxi_rresp),
        .m_axi_rlast   (jaxi_rlast),
        .m_axi_rvalid  (jaxi_rvalid),
        .m_axi_rready  (jaxi_rready)
    );

    /* verilator lint_off UNUSED */
    wire _unused_jaxi = &{1'b0, jaxi_awid_unused, jaxi_awsize_unused,
                          jaxi_awburst_unused, jaxi_awlock_unused,
                          jaxi_awcache_unused, jaxi_awprot_unused,
                          jaxi_awqos_unused, jaxi_arid_unused,
                          jaxi_arsize_unused, jaxi_arburst_unused,
                          jaxi_arlock_unused, jaxi_arcache_unused,
                          jaxi_arprot_unused, jaxi_arqos_unused, 1'b0};
    /* verilator lint_on UNUSED */
`else
    // Lint / no-IP builds: quiesce the AXI face.
    assign jaxi_awaddr  = 32'd0;
    assign jaxi_awlen   = 8'd0;
    assign jaxi_awvalid = 1'b0;
    assign jaxi_wdata   = 32'd0;
    assign jaxi_wstrb   = 4'd0;
    assign jaxi_wlast   = 1'b0;
    assign jaxi_wvalid  = 1'b0;
    assign jaxi_bready  = 1'b1;
    assign jaxi_araddr  = 32'd0;
    assign jaxi_arlen   = 8'd0;
    assign jaxi_arvalid = 1'b0;
    assign jaxi_rready  = 1'b1;

    /* verilator lint_off UNUSED */
    wire _unused_jaxi = &{1'b0, jaxi_awready, jaxi_wready, jaxi_bresp,
                          jaxi_bvalid, jaxi_arready, jaxi_rdata,
                          jaxi_rresp, jaxi_rlast, jaxi_rvalid, 1'b0};
    /* verilator lint_on UNUSED */
`endif

    // ──────────────────────────────────────────────────────────────────
    // Provisioning core.
    // ──────────────────────────────────────────────────────────────────
    wire card_ready;
    wire init_error;
    wire writer_busy;

    sd_provision_core #(
        .STAGE_SECTORS (256),
        // 100 MHz core clock → 200 kHz init, 12.5 MHz fast, 25 MHz HS.
        .SPI_SLOW_HALF (250),
        .SPI_FAST_HALF (4),
        .SPI_HS_HALF   (2)
    ) u_core (
        .clk        (core_clk),
        .rst        (core_rst),

        .s_awaddr   (jaxi_awaddr),
        .s_awlen    (jaxi_awlen),
        .s_awvalid  (jaxi_awvalid),
        .s_awready  (jaxi_awready),
        .s_wdata    (jaxi_wdata),
        .s_wstrb    (jaxi_wstrb),
        .s_wlast    (jaxi_wlast),
        .s_wvalid   (jaxi_wvalid),
        .s_wready   (jaxi_wready),
        .s_bresp    (jaxi_bresp),
        .s_bvalid   (jaxi_bvalid),
        .s_bready   (jaxi_bready),
        .s_araddr   (jaxi_araddr),
        .s_arlen    (jaxi_arlen),
        .s_arvalid  (jaxi_arvalid),
        .s_arready  (jaxi_arready),
        .s_rdata    (jaxi_rdata),
        .s_rresp    (jaxi_rresp),
        .s_rlast    (jaxi_rlast),
        .s_rvalid   (jaxi_rvalid),
        .s_rready   (jaxi_rready),

        .sd_clk     (sd_clk),
        .sd_mosi    (sd_mosi),
        .sd_miso    (sd_miso),
        .sd_cs_n    (sd_cs_n),

        .card_ready (card_ready),
        .init_error (init_error),
        .writer_busy(writer_busy)
    );

    // ──────────────────────────────────────────────────────────────────
    // LEDs.
    // ──────────────────────────────────────────────────────────────────
    reg [25:0] heartbeat_q;
    always @(posedge core_clk) begin
        if (core_rst) heartbeat_q <= 26'd0;
        else          heartbeat_q <= heartbeat_q + 26'd1;
    end

    assign led[0] = card_ready;
    assign led[1] = writer_busy;
    assign led[2] = init_error;
    assign led[3] = heartbeat_q[25];

endmodule

`default_nettype wire
