| Auto-generated by gen_program.py --seed 148
    .text
    .org 0

_start:
    lea     0x0010ce00, %a0
    neg.l   %d6
    move.l  #0x9b249839, %d3
    moveq   #1, %d3
    add.l   %d6, %d5
    move.l  #0x00000084, %d0
    addq.l  #2, %d4
    or.l   %d7, %d2
    move.l  %d5, (184,%a0)
    bmi    fwd_1
    cmp.l   %d2, %d2
    subi.l  #0xffffffff, %d7
    andi.l  #0xc29fa4e5, %d0
    bcc    fwd_2
    tst.l   %d6
fwd_1:
    move.l  #0xfc2c06bf, %d3
fwd_2:
    moveq   #39, %d6
    move.l  %d7, (24,%a0)
    cmpi.l  #0x0000009b, %d3
    moveq   #-122, %d4
    tst.l   %d2
    addq.l  #6, %d4
    move.l  (80,%a0), %d2
    add.l   %d5, %d1
    sub.l   %d1, %d1
    move.l  #0x4af16fed, %d5
    move.l  #0x5492e398, %d2
    not.l   %d0
    ori.l  #0x000000cb, %d7
    move.l  (248,%a0), %d2
    bge    fwd_3
    addq.l  #3, %d5
    not.l   %d1
    add.l   %d2, %d0
    move.l  %d3, %d2
fwd_3:
    ext.l   %d5
    bra    fwd_4
    cmp.l   %d2, %d7
fwd_4:
    tst.l   %d0
    move.l  #0x00000001, %d7
    move.l  %d7, %d1
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt
