| Auto-generated by gen_program.py --seed 776678823
    .text
    .org 0

_start:
    lea     0x00080000, %a7   | stack top
    lea     0x00100000, %a0   | A0 data pool
    lea     0x00104000, %a1   | A1 data pool
    lea     0x00108000, %a2   | A2 data pool
    lea     0x0010c000, %a3   | A3 data pool
    moveq   #3, %d6           | D6 = hop counter
    moveq   #0, %d4
    moveq   #0, %d5

    asr.l  #2, %d4
    move.l  %d3, (44,%a3)
    moveq   #0, %d5
dbcc_1:
    addq.l  #1, %d3
    dbne   %d5, dbcc_1
    lsr.l  #8, %d0
    add.l   %d5, %d2
    bset    #27, %d3
    move.l  %d2, 0x00101a6c
    moveq   #80, %d1
    bclr    #27, %d4
    move.l  0x0010fccc, %d1
    move.l  %d2, %d4
    roxl.l  #6, %d5
    add.l   %d3, %d0
back_2:
    link    %a6, #-16
    addq.l  #1, %d4
    unlk    %a6
back_3:
    beq    fwd_4
    move.l  #0x571da084, %d0
    bclr    %d5, %d2
back_5:
    move.l  (%a0), %d1
    move.l  %d5, (%a3)
    move.l  %d0, 0x0010977c
    move.l  #0x0000611d, %d1
    move.l  (%a2), %d4
    bmi    fwd_6
    beq    fwd_7
fwd_4:
back_8:
    moveq   #-121, %d3
fwd_6:
    subq.l  #1, %d6
    bne     back_5
    moveq   #3, %d6
    move.l  (%a2), %d5
    move.l  0x001007f4, %d5
    subq.l  #8, %d5
    move.l  %d1, (%a1)
    bchg    #24, %d5
back_9:
    btst    #9, %d1
    subq.l  #6, %d3
back_10:
    subq.l  #7, %d2
    move.l  0x00109c0c, %d1
    rol.l  #4, %d4
fwd_7:
    addi.l  #0x00000001, %d1
    bset    #19, %d0
    ror.l  #4, %d4
back_11:
    bclr    %d3, %d3

_end:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt
