| Auto-generated by gen_program.py --seed 106
    .text
    .org 0

_start:
    lea     0x0010f500, %a0
    bls    fwd_1
    ble    fwd_2
    ble    fwd_3
    andi.l  #0x0000efae, %d4
    move.l  %d4, %d5
    bpl    fwd_4
    move.l  %d6, %d1
fwd_1:
    moveq   #-35, %d5
    subq.l  #8, %d7
    move.l  %d7, %d3
fwd_2:
    addq.l  #3, %d5
    move.l  %d7, (180,%a0)
    sub.l   %d5, %d6
    cmp.l   %d2, %d2
    addq.l  #2, %d7
    addq.l  #4, %d1
    move.l  #0xb6699b02, %d2
    bge    fwd_5
    move.l  (140,%a0), %d1
    moveq   #91, %d3
fwd_3:
fwd_4:
fwd_5:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt
