| Auto-generated by gen_program.py --seed 1419
    .text
    .org 0

_start:
    lea     0x00080000, %a7   | stack top
    lea     0x00100000, %a0   | A0 data pool
    lea     0x00104000, %a1   | A1 data pool
    lea     0x00108000, %a2   | A2 data pool
    lea     0x0010c000, %a3   | A3 data pool
    move.l  #0x00000059, %d0   | D0 init (B1b)
    move.l  #0x00006df5, %d1   | D1 init (B1b)
    move.l  #0x000000f3, %d2   | D2 init (B1b)
    move.l  #0x0000002f, %d3   | D3 init (B1b)
    movea.l #0xc57b6d1c, %a4  | A4 init (B1b)
    movea.l #0x00006dd8, %a5  | A5 init (B1b)
    movea.l #0x4e484246, %a6  | A6 init (B1b)
    moveq   #3, %d6           | D6 = hop counter
    moveq   #0, %d4
    moveq   #0, %d5

    lea     (452,%a0), %a4
    lea     (928,%a0), %a5
    lea     (660,%a0), %a6
    move.l  %a6, (436,%a0)
    move.l  #0xffffffff, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    move.l  #0xa5a5a5a5, %d7
    divul.l  %d7, %d2:%d4
    cmpi.l  #0x00003d09, %d0
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (852,%a4), %a1
    lea     (1144,%a4), %a0
    moveq   #4, %d2
    move.l  #0x7fffffff, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    blt    fwd_1
    cmp.l   %d1, %d4
    and.l   (%a0)+, %d3
    add.l   %d1, %d4
    movem.l %d6/%a2/%a4-%a5, -(%a7)
    lea     0x00100000, %a2
    lea     0x00100100, %a4
    move.l  #0xdead0002, %d6
    lea     0x00100300, %a5
    movem.l (%a7)+, %d6/%a2/%a4-%a5
    move.l  %d2, %d3
    move.l  %d5, %d4
fwd_1:
    bne    fwd_2
fwd_2:
    moveq   #-50, %d1
    cmpm.l  (%a2)+, (%a3)+
    tst.w   (164,%a0)
    cmp.l   (%a3), %d1
    lsr.l  #6, %d0
    cmp.l   %d1, %d3
    move.l  %a0, %a1
    adda.l  #984, %a1
    move.l  %a0, %a4
    adda.l  #1256, %a4
    move.l  %a4, 16(%a1)
    move.l  #0x5d3a59d9, (%a4)
    move.l  #0x0000e038, %d0
    moveq   #3, %d5
    .word   0xeff1, 0x0944, 0x0164, 0x0010
    and.l   (%a2)+, %d2
    btst    #31, %d4
    sub.b   (120,%a3), %d5
    moveq   #3, %d4
    bra     _pcidx_after_4
_pcidx_tbl_3:
    .byte   0x40, 0x33, 0xea, 0xbd
    .align  2
_pcidx_after_4:
    move.b  _pcidx_tbl_3(%pc,%d4.w), %d3
    move.l  %d0, (208,%a1)
    tst.w   %a3
    move.l  %d3, %d6
    move.l  %d6, %d2
    move.l  %d2, %d0
    move.l  %d0, %d5
    move.l  %d5, %d4
    eori.l  #0x00000000, %d2
    move.l  #0x123456a5, %d1
    not.b   %d1
    cmpi.l  #0x000000ab, (%a2)
    bcc    fwd_5
    move.l  0x001045c0, %d0
    bfchg   %d2{15:28}
    moveq   #-32, %d2
    tst.l   %d1
    beq    fwd_6
    bls    fwd_7
    move.l  %d0, (156,%a0)
    add.w   %d1, (%a3)
fwd_5:
    move.l  %d5, (240,%a2)
    lea     0x0010c3c0, %a4
    move.l  #0x00008b4f, (%a3)
    movea.l (%a3)+, %a5
    movea.l (116,%a3), %a6
fwd_6:
    lea     0x00100000, %a6
    adda.l  (240,%a3), %a6
fwd_7:
    lea     (152,%a0), %a4
    tst.l   (%a4)+
    moveq   #102, %d0
    moveq   #0, %d0
    subq.w  #8, %d2
    lea     (115,%a0), %a4
    lea     (44,%a1), %a5
    move.b  (%a4)+, (%a5)+
    lea     0x00107898, %a6
    cmpi.b  #0xf0, (216,%a3)
    cmp.l   %d4, %d5
    sne     (%a0)
    lea     (32,%a0), %a6
    move.b  #0x29, (%a6)
    bset    #0, (%a6)
    andi.l  #0x80000000, %d3
    move.l  %d4, %d5
    move.l  %d5, %d6
    move.l  %d6, %d3
    move.l  %d3, %d0
    move.l  %d0, %d2
    move.l  %d2, %d1
    move.l  #0x00000011, %d7
    divs.l  %d7, %d0
    lea     0x00100000, %a6
    adda.l  (%a0), %a6
    sub.b   -(%a1), %d4
    movep.w %d2, 390(%a3)
    add.l   -(%a3), %d1
    movem.l %d0/%d2/%d7/%a1-%a2/%a6, -(%a7)
    move.l  #0xdead0000, %d0
    lea     0x00100100, %a6
    move.l  #0xdead0002, %d2
    lea     0x00100300, %a2
    lea     0x00100400, %a1
    move.l  #0xdead0005, %d7
    movem.l (%a7)+, %d0/%d2/%d7/%a1-%a2/%a6
    or.l    (56,%a2), %d1
    lea     (20,%a0), %a6
    move.b  #0x5f, (%a6)
    btst    #2, (%a6)+
    add.b   (28,%a0), %d2
    muls.l  #0xffffffff, %d1
    move.l  #0x00000002, %d5
    move.l  #0x00000003, %d7
    divu.l  %d7, %d5:%d3
    cmpi.l  #0x86224633, (%a3)
    sub.l   (%a3), %d3
    jmp     jmp_8
    moveq   #0, %d1
    mulu.l  #0x00000007, %d4
    asr.b  #5, %d4
    bls    fwd_9
    lea     (192,%a0), %a4
    moveq   #0, %d5
    and.b   (4,%a4,%d5.w*4), %d3
    sub.l   %d3, %d3
    cmp.l   %d2, %d3
    sub.l   (%a0), %d1
    bmi    fwd_10
    move.l  #0x00000095, %d7
    move.l  #0x00000019, %d5
    sbcd    %d5, %d7
    cmp.l   %d5, %d4
    bcs    fwd_11
    move.b  (45,%a2), %d2
jmp_8:
    move.l  %d6, %d5
    move.l  %d5, %d0
    move.l  %d0, %d2
    move.l  %d2, %d4
fwd_9:
    bra    fwd_12
    sub.w   %d4, (180,%a1)
fwd_10:
    move.l  #0x00000066, %d4
    ori.b  #0x00ce, %d4
    tst.l   %d4
    or.l    (60,%a2), %d0
    sne     %d4
fwd_11:
    add.w   -(%a2), %d1
    lea     (428,%a0), %a4
    lea     (1008,%a0), %a5
    lea     (664,%a0), %a6
    move.l  %a6, (412,%a0)
    move.l  #0x00004b12, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    subq.w  #2, %d2
    moveq   #0, %d3
    move.w  (%a2)+, %d3
    subq.l  #2, %a2
    ble    fwd_13
    lea     (8,%a0), %a4
    tst.w   (%a4)+
    add.b   (%a1), %d3
    rol.w  #5, %d1
    lea     0x00100000, %a4
    adda.l  -(%a2), %a4
    lea     (456,%a0), %a4
    lea     (916,%a0), %a5
    lea     (732,%a0), %a6
    move.l  %a6, (440,%a0)
    move.l  #0x000000ad, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
fwd_12:
    cmp.l   %d3, %d3
    asr.b  #3, %d1
    bset    %d4, %d0
    moveq   #65, %d5
    btst    %d2, %d2
    move.l  (%a1)+, %d0
    lea     (12,%a1), %a5
    andi.l  #0xd644da9a, (%a5)+
fwd_13:
    lea     0x00100000, %a6
    adda.l  (%a2), %a6
    or.l    (%a0)+, %d1
    divs.l  #0x00000001, %d1
    bge    fwd_14
    lea     0x00100000, %a5
    adda.l  (40,%a1), %a5
    lea     0x00100000, %a4
    adda.w  (252,%a3), %a4
    move.l  (156,%a1), %d4
    muls.w  #0x0002, %d0
    tst.l   %d3
    bne    fwd_15
    lea     0x00100000, %a6
    move.l  #0x00008000, %d0
    adda.w  %d0, %a6
fwd_14:
    move.l  %d1, (172,%a2)
    asl.b  #6, %d0
    lea     (252,%a1), %a5
    move.w  #0xa24, (%a5)+
    subq.b  #4, (140,%a2)
    add.b   (16,%a0), %d3
    addi.l  #0x939b4597, %d5
    lea     0x00100000, %a6
    adda.l  -(%a1), %a6
    add.w   (196,%a0), %d4
    move.l  #0x00000001, %d5
    andi.l  #0x0000003f, %d4  | dynamic count in 0..63
    asl.l   %d4, %d5
    ble     shift_v_done_4e65
    nop
shift_v_done_4e65:
    lea     0x00100000, %a4
    adda.l  -(%a3), %a4
    and.l   %d4, (%a0)
fwd_15:
    st     %d1
    cmp.l   -(%a2), %d3
    move.l  #0x00000003, %d7
    divsl.l  %d7, %d4:%d6
    move.l  #0x00000007, %d5
    divul.l  %d5, %d7:%d6
    muls.l  #0x00000001, %d4
    moveq   #3, %d5
    bra     _pcidx_after_17
_pcidx_tbl_16:
    .byte   0x90, 0x40, 0x2e, 0xfd
    .align  2
_pcidx_after_17:
    move.b  _pcidx_tbl_16(%pc,%d5.w), %d2
    cmp.l   %d0, %d3
    add.w   (%a2), %d0
    move.l  %d1, %d3
    cmp.l   (%a3)+, %d0
    cmpi.l  #0x80000000, %d1
    subq.l  #8, %d1
    and.l   (%a2)+, %d0
    roxl.l  %d4, %d2
    cmp.l   (8,%a3), %d3
    cmp.l   %d5, %d0
    bls    fwd_18
    tst.l   %d4
    move.b  (156,%a0), %d2
    moveq   #3, %d0
    move.b  %d3, (7,%a0,%d0.l)
    add.l   %d3, %d2   | sets X for chain
    addx.l  %d1, %d3
    subx.l  %d3, %d0
    addx.l  %d5, %d3
    rol.l  %d4, %d5
    add.l   %d1, %d0
    move.l  #0xFFFFFFFF, %d4
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d4
    bge     shift_v_done_e75c
    nop
shift_v_done_e75c:
    rol.l  %d5, %d5
fwd_18:
    move.l  %d4, %d4
    move.l  %d2, (%a2)
    move.l  %a0, %a2
    adda.l  #928, %a2
    move.l  %a0, %a4
    adda.l  #1176, %a4
    move.l  %a4, 16(%a2)
    move.l  #0x2d69d6a5, (%a4)
    .word   0xebf2, 0x10cb, 0x0164, 0x0010
    move.l  %d0, %d6
    move.l  %d6, %d1
    move.l  %d1, %d2
    move.l  %d4, 0x0010fdb4
    bclr    %d4, %d1
    cmp.l   (%a2), %d0
    moveq   #106, %d3
    and.l   (%a1), %d4
    lea     0x00100000, %a4
    adda.w  (120,%a1), %a4
    moveq   #1, %d3
    bra     _pcidx_after_20
_pcidx_tbl_19:
    .byte   0x71, 0x06, 0xb8, 0x3c
    .align  2
_pcidx_after_20:
    move.b  _pcidx_tbl_19(%pc,%d3.w), %d0
    asl.l  #1, %d5
    blt    fwd_21
    or.l    (%a2)+, %d5
    bpl    fwd_22
    move.l  #0xd051be8c, %d4
    bset    %d0, %d5
    tst.b   (%a3)
    lea     (72,%a1), %a5
    andi.l  #0x0000da29, (%a5)+
fwd_21:
    move.l  %d3, %d1
    move.l  %d1, %d5
    move.l  %d5, %d6
    move.l  %d6, %d0
    cmpi.l  #0xce834805, %d4
fwd_22:
    add.l   %d0, %d5
    and.l   (100,%a3), %d4
    subq.l  #5, (100,%a1)
    bchg    #2, %d1
    add.l   %d0, %d3
    bchg    #24, %d3
    subq.w  #2, (220,%a0)
    lea     (480,%a0), %a4
    moveq   #20, %d5
    and.l   (8,%a4,%d5.w*1), %d2
    svs     %d0
    and.l   (%a0), %d1
    move.l  (%a0), %d3
    lea     (88,%a0), %a4
    add.w   %d5, (%a4)+
    cmp.l   (%a3)+, %d5
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (864,%a4), %a1
    lea     (1064,%a4), %a0
    moveq   #0, %d2
    move.l  #0x000028e3, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    bpl    fwd_23
fwd_23:
    move.w  #0x7fff, (50,%a0)
    divu.w  (50,%a0), %d4
    bfclr   %d1{31:18}
    jmp     jmp_24
jmp_24:
    move.l  #0xfffffffe, %d7
    divsl.l  %d7, %d4:%d1
    move.l  #0x000001ad, %d5
    pack    %d5, %d0, #0xc228
    ble    fwd_25
    bls    fwd_26
    ble    fwd_27
    bsr     sub_28
    bhi    fwd_29
    movep.l %d3, 126(%a0)
    move.l  (%a1), %d2
    exg     %a4, %a6
fwd_25:
    or.l    (%a1)+, %d0
    sub.w   (156,%a2), %d4
    tst.l   (%a0)
    mulu.w  #0x00ff, %d5
    add.w   (%a1), %d0
    moveq   #0, %d1
    subq.l  #4, %d1
    muls.w  (40,%a3), %d3
fwd_26:
    move.l  %d3, %d2
fwd_27:
    moveq   #123, %d5
    move.l  #0x00002125, %d0
    eori.w  #0xfc75, %d0
    tst.l   %d0
    bne    fwd_30
fwd_29:
    not.l   %d5
    addq.l  #8, %d0
fwd_30:
    tst.l   %d1
    moveq   #-25, %d1
    move.l  #0x0000aebb, %d3
    lea     0x00100000, %a5
    adda.w  %a3, %a5
    lea     (160,%a0), %a4
    move.l  -(%a4), %d5
    sub.l   %d2, %d5
    and.l   (16,%a0), %d2
    moveq   #10, %d6
back_31:
    addq.l  #1, %d2
    subq.l  #1, %d6
    bpl     back_31
    moveq   #3, %d6
    and.l   (104,%a3), %d0
    move.l  #0x00000088, %d0
    unpk    %d0, %d6, #0xf394
    sub.w   %d3, (8,%a1)
    mulu.l  %d2, %d1
    move.l  %d2, (%a2)
    sub.l   (%a0), %d1
    subq.w  #4, (164,%a3)
    move.l  #0x00000005, %d7
    divs.l  %d7, %d2
    bchg    #3, %d1
    addi.l  #0x00007cc3, %d5
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (872,%a4), %a1
    lea     (1100,%a4), %a0
    moveq   #12, %d2
    move.l  #0x0000ccfe, (12,%a1)
    move.l  #0x00000000, (12,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    jmp     jmp_32
jmp_32:
    or.l    (%a3)+, %d0
    cmp.l   (%a0), %d2
    eori.l  #0x000000e5, %d3
    bfchg   %d1{15:28}
    and.l   (184,%a2), %d4
    move.l  #0x00000100, %d7
    divsl.l  %d7, %d4:%d5
    cmp.l   %d4, %d5
    move.l  %d0, %d4
    move.l  %d4, %d6
    move.l  %d6, %d5
    move.l  %d5, %d2
    move.l  %d2, %d1
    move.l  %d1, %d3
    and.l   (%a1), %d4
    add.l   (%a1)+, %d3
    lea     0x00100000, %a4
    adda.l  -(%a1), %a4
    move.w  #0x0008, %d4
dbcc_33:
    addq.l  #1, %d1
    dbeq   %d4, dbcc_33
    and.l   (%a2)+, %d3
    move.l  %d3, %d2
    move.l  %d2, %d0
    move.l  %d0, %d4
    move.l  %d4, %d5
    move.l  %d5, %d6
    move.l  %d6, %d1
    addq.l  #1, %d1
    beq     fwd_34
    lea     (4,%a1), %a5
    andi.l  #0xe69ea07e, (%a5)+
fwd_34:
    bfins   %d1, %d3{31:27}
    and.l   (%a1)+, %d1
    lea     (120,%a1), %a5
    move.b  #0x00, (8,%a5)
    moveq   #15, %d2
    btst    %d2, (8,%a5)
    lea     (200,%a1), %a5
    move.b  #0xcd, (2,%a5)
    moveq   #3, %d3
    bclr    %d3, (2,%a5)
    roxr.l  %d0, %d5
    and.l   (176,%a3), %d3
    bmi    fwd_35
    or.l    (%a2), %d5
fwd_35:
    add.b   (36,%a1), %d5
    bcc    fwd_36
fwd_36:
    lea     (156,%a0), %a4
    add.w   %d2, (%a4)+
    lea     0x00100000, %a4
    adda.l  -(%a0), %a4
    sub.w   (84,%a1), %d0
    andi.l  #0x0000005d, %d3
    movep.w %d0, 656(%a2)
    bpl    fwd_37
    move.l  %a0, %a2
    adda.l  #1016, %a2
    move.l  %a0, %a4
    adda.l  #1176, %a4
    move.l  %a4, 16(%a2)
    move.l  #0x00000089, (%a4)
    moveq   #3, %d1
    .word   0xecf2, 0x4842, 0x0164, 0x0010
    nop
fwd_37:
    subq.l  #8, %d5
    ble    fwd_38
    moveq   #-15, %d4
    bfclr   %d2{7:1}
    move.w  #0x003d, %d4
dbcc_39:
    addq.l  #1, %d0
    dbeq   %d4, dbcc_39
fwd_38:
    move.l  #0x00000010, %d2
    move.l  #0x00010000, %d6
    divu.l  %d6, %d2:%d7
    addi.l  #0x0000ba03, %d1
    cmp.l   (%a1)+, %d5
    muls.w  (%a1), %d2
    bhi    fwd_40
fwd_40:
    bhi    fwd_41
    move.l  %d2, %d4
    addq.l  #1, %d5
    beq     fwd_42
    and.l   (48,%a2), %d3
    move.l  %d5, %d2
    move.l  %d2, %d6
    move.l  %d6, %d4
    move.l  %d4, %d3
    movep.w %d5, 952(%a0)
    bmi    fwd_43
    mulu.l  %d2, %d1
fwd_41:
    subq.l  #1, %d4
    bne     fwd_44
    move.l  %d4, %d4
fwd_42:
    addq.l  #5, %d3
    cmp.l   -(%a1), %d1
fwd_43:
    add.l   %d4, %d3   | sets X for chain
    addx.l  %d5, %d5
    subx.l  %d0, %d3
    clr.b   (220,%a3)
fwd_44:
    add.l   %d1, %d3   | sets X for chain
    addx.l  %d4, %d0
    addx.l  %d2, %d1
    addq.l  #6, %d3
    rol.l  %d1, %d2
    clr.w   %d5
    move.l  %d2, (%a0)
    cmp.l   %d4, %d2
    cmp.l   (%a3)+, %d1
    sls     %d2
    lea     (440,%a0), %a4
    lea     (900,%a0), %a5
    lea     (700,%a0), %a6
    move.l  %a6, (424,%a0)
    move.l  #0x435f8051, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    movep.w %d3, 276(%a2)
    move.l  #0x00000056, %d6
    move.l  #0x00000023, %d7
    sbcd    %d7, %d6
    moveq   #0, %d4
    move.w  (%a3)+, %d4
    subq.l  #2, %a3
    lea     (8,%a0), %a4
    move.b  #0x27, (%a4)
    moveq   #1, %d0
    bchg    %d0, (%a4)
    move.l  %d5, 0x001081e4
    move.l  %d4, %d3
    add.b   (%a2), %d1
    sub.l   %d2, %d2
    lea     0x00100000, %a4
    adda.w  %a1, %a4
    move.l  (%a2), %d4
    move.l  #0x00007cfb, %d5
    pack    %d5, %d1, #0x0000
    lea     0x00101df0, %a4
    lea     (172,%a1), %a5
    andi.l  #0x00000010, (%a5)+
    lea     (476,%a0), %a4
    lea     (1020,%a0), %a6
    move.l  %a6, (460,%a0)
    move.l  #0xb3ffa2d9, %d7
    .word   0x2987, 0x0164, 0xfff0
    lea     (4,%a0), %a4
    cmpi.l  #0x725b23cc, (%a4)+
    and.l   %d2, %d1
    cmp.l   (%a0), %d2
    add.l   %d5, %d0   | sets X for chain
    addx.l  %d2, %d0
    addx.l  %d1, %d5
    cmpi.l  #0x00000090, %d2
    lea     (232,%a0), %a4
    move.l  -(%a4), %d2
    lea     0x00104f90, %a5
    eori.l  #0xffffffff, %d0
    cmpi.l  #0x0000ca60, %d3
    move.w  #0x0008, %d5
dbcc_45:
    addq.l  #1, %d1
    dbeq   %d5, dbcc_45
    clr.w   %d3
    cmp.l   -(%a0), %d0
    lea     0x00100000, %a5
    adda.l  (%a3), %a5
    addi.l  #0x0000d090, %d3
    lea     0x00100000, %a6
    adda.l  (%a2), %a6
    bmi    fwd_46
fwd_46:
    nop
    bfset   %d4{8:22}
    ori.l  #0x00000001, %d5
    link    %a6, #-16
    addq.l  #1, %d5
    unlk    %a6
    lea     (96,%a1), %a5
    move.w  %d2, (%a5)+
    lea     (168,%a1), %a5
    move.w  %d3, (%a5)+
    eori.l  #0xe37334a2, %d0
    moveq   #6, %d0
    lea     (8,%a0), %a4
    move.b  (%a4)+, (6,%a3,%d0.l)
    addq.l  #2, %d5
    lea     (344,%a0), %a4
    lea     (716,%a0), %a5
    lea     (328,%a0), %a6
    move.l  %a5, (%a6)
    lea     (716,%a0), %a6
    move.l  #0x80000000, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    muls.w  #0xffff, %d5
    sub.w   (%a0)+, %d3
    lea     0x00100000, %a4
    move.l  #0x00000008, %d0
    adda.w  %d0, %a4
    add.l   %d4, %d5   | sets X for chain
    addx.l  %d1, %d0
    addx.l  %d3, %d3
    movem.l %d0-%d7/%a0/%a2-%a6, -(%a7)
    move.l  #0xdead0000, %d7
    lea     0x00100100, %a6
    move.l  #0xdead0002, %d5
    move.l  #0xdead0003, %d0
    lea     0x00100400, %a5
    lea     0x00100500, %a0
    lea     0x00100600, %a4
    move.l  #0xdead0007, %d6
    move.l  #0xdead0008, %d2
    move.l  #0xdead0009, %d4
    move.l  #0xdead000a, %d1
    lea     0x00100b00, %a3
    move.l  #0xdead000c, %d3
    lea     0x00100d00, %a2
    movem.l (%a7)+, %d0-%d7/%a0/%a2-%a6
    lea     (56,%a0), %a6
    move.b  #0xf5, -1(%a6)
    bchg    #7, -(%a6)
    moveq   #89, %d2
    cmp.l   -(%a0), %d4
    sub.b   -(%a2), %d4
    move.l  #0x0000000d, %d7
    divs.w  %d7, %d3
    add.l   %d4, %d4   | sets X for chain
    addx.l  %d5, %d5
    addx.l  %d4, %d2
    move.l  %d4, %d1
    move.l  (%a2), %d0
    or.l    (%a2), %d1
    move.l  #0xFFFFFFFE, %d3
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d3
    bge     shift_v_done_0bf6
    nop
shift_v_done_0bf6:
    move.l  (%a2), %d2
    cmpi.l  #0xdeadbeef, %d5
    and.l   (%a0), %d2
    move.l  0x0010513c, %d4
    add.l   %d4, %d2
    lea     (148,%a1), %a5
    move.l  #0xdeadbeef, (%a5)+
    move.l  0x00104444, %d2
    addq.l  #1, %d0
    beq     fwd_47
fwd_47:
    tst.l   %a1
    muls.l  %d1, %d5
    add.w   (40,%a1), %d4
    lea     (36,%a0), %a4
    add.b   %d5, (%a4)+
    or.l   %d0, %d4
    bcs    fwd_48
    and.l   (252,%a3), %d4
    bsr     sub_49
fwd_48:
    moveq   #0, %d0
    lea     (14,%a0), %a4
    move.b  (%a4)+, (7,%a2,%d0.l)
    beq    fwd_50
fwd_50:
    bchg    #25, %d5
    moveq   #63, %d6
back_51:
    addq.l  #1, %d1
    subq.l  #1, %d6
    bge     back_51
    moveq   #3, %d6
    move.l  #0x82a7af6a, (%a1)
    movea.l (%a1)+, %a6
    lea     (40,%a1), %a5
    move.b  #0x85, (2,%a5)
    moveq   #11, %d0
    bchg    %d0, (2,%a5)
    move.l  %d2, %d1
    movea.l #0xdeadbeef, %a6
    sub.b   (%a3), %d0
    movem.l %d1-%d3/%d5/%d7/%a2/%a4-%a5, -(%a7)
    move.l  #0xdead0000, %d1
    move.l  #0xdead0001, %d2
    move.l  #0xdead0002, %d5
    move.l  #0xdead0003, %d3
    lea     0x00100400, %a4
    move.l  #0xdead0005, %d7
    lea     0x00100600, %a5
    lea     0x00100700, %a2
    movem.l (%a7)+, %d1-%d3/%d5/%d7/%a2/%a4-%a5
    moveq   #0, %d0
    bra     _pcidxw_after_53
_pcidxw_tbl_52:
    .word   0xac9e, 0xdb37, 0x9a27, 0xfa7e
_pcidxw_after_53:
    move.w  _pcidxw_tbl_52(%pc,%d0.w*2), %d3
    lea     0x00100000, %a4
    adda.l  (244,%a1), %a4
    bfchg   %d4{14:%d5}
    add.b   %d0, (%a0)
    move.l  %d1, %d4
    or.l    (%a3), %d3
    lea     0x001001f0, %a4
    add.l   (%a0), %d5
    move.l  #0x000000aa, %d1
    cmp.l   %d1, %d3
    tst.l   %d0
    lea     (75,%a0), %a4
    lea     (229,%a1), %a5
    move.b  (%a4)+, (%a5)+
    rol.b  #4, %d5
    cmpi.l  #0x00009ebc, %d0
    lea     0x00100000, %a4
    adda.l  -(%a2), %a4
    move.l  #0x00000002, %d1
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d1
    bgt     shift_v_done_137d
    nop
shift_v_done_137d:
    move.l  %d5, (180,%a0)
    subq.l  #1, %d5
    bne     fwd_54
    move.l  #0x00000000, %d2
    move.l  (%a1), %d3
    move.l  %d5, 0x00104ba4
fwd_54:
    lea     (236,%a1), %a5
    move.b  #0xbc, (8,%a5)
    moveq   #8, %d5
    bclr    %d5, (8,%a5)
    lea     (400,%a0), %a4
    lea     (636,%a0), %a5
    lea     (384,%a0), %a6
    move.l  %a5, (%a6)
    lea     (632,%a0), %a6
    move.l  #0x00008ed2, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    bpl    fwd_55
    blt    fwd_56
fwd_55:
    and.l   (172,%a2), %d3
    cmp.l   (236,%a2), %d2
    moveq   #1, %d0
    lea     (10,%a0), %a4
    move.b  (%a4)+, (8,%a3,%d0.l)
    move.l  #0x0000004b, %d3
    andi.b  #0x00ee, %d3
    tst.l   %d3
fwd_56:
    lea     (158,%a0), %a4
    lea     (9,%a1), %a5
    move.b  (%a4)+, (%a5)+
    blt    fwd_57
    eor.l   %d1, %d1
    sub.l   (%a2), %d1
    move.l  #0x00000059, %d4
    nbcd    %d4
    addq.l  #8, %d2
    bmi    fwd_58
fwd_57:
    or.l    (%a1), %d5
    move.l  %d0, (56,%a1)
    ror.l  %d5, %d0
    neg.l   %d4
    cmp.l   (%a0), %d4
fwd_58:
    move.l  %d0, 0x00105604
    moveq   #0, %d1
    moveq   #2, %d0
    move.b  %d1, (2,%a2,%d0.l)
    move.l  (132,%a0), %d5
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (784,%a4), %a1
    lea     (1088,%a4), %a0
    moveq   #0, %d2
    move.l  #0x000000fd, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    moveq   #8, %d0
    lea     (0,%a0), %a4
    move.b  (%a4)+, (6,%a3,%d0.l)
    sne     %d0
    lea     (252,%a0), %a4
    move.l  -(%a4), %d0
    spl     %d5
    bra    fwd_59
fwd_59:
    lea     (244,%a0), %a4
    cmpi.w  #0x73f1, (%a4)+
    movep.w 20(%a1), %d3
    movep.w 866(%a3), %d2
    or.l    (%a0), %d2
    add.b   %d1, (%a1)
    move.l  #0x80000001, %d2
    andi.l  #0x0000003f, %d0  | dynamic count in 0..63
    asl.l   %d0, %d2
    bge     shift_v_done_319a
    nop
shift_v_done_319a:
    addq.l  #5, %d3
    mulu.w  (%a0), %d1
    move.l  #0x00000001, %d7
    divs.l  %d7, %d0
    subq.l  #1, %d5
    bne     fwd_60
    move.l  (136,%a1), %d1
fwd_60:
    lea     (120,%a1), %a5
    andi.l  #0x045bec5f, (%a5)+
    move.l  #0x00000001, (%a2)
    movea.l (%a2)+, %a4
    ble    fwd_61
fwd_61:
    move.l  #0x000000a8, %d0
    lea     (352,%a0), %a4
    moveq   #4, %d5
    and.l   (4,%a4,%d5.l*1), %d2
    cmp.l   -(%a1), %d3
    bhi    fwd_62
    lea     0x00100000, %a6
    adda.l  (188,%a0), %a6
fwd_62:
    ble    fwd_63
fwd_63:
    lea     (212,%a0), %a4
    lea     (16,%a1), %a5
    move.l  (%a4), (%a5)+
    sle     %d5
    or.l    %d0, (%a0)
    bne    fwd_64
    bmi    fwd_65
fwd_64:
    mulu.l  %d3, %d2
    and.l   (%a3), %d2
    or.l   %d3, %d0
    movem.l %d0/%d2-%d7/%a0-%a6, -(%a7)
    move.l  #0xdead0000, %d4
    lea     0x00100100, %a1
    lea     0x00100200, %a0
    move.l  #0xdead0003, %d0
    lea     0x00100400, %a6
    move.l  #0xdead0005, %d6
    lea     0x00100600, %a3
    lea     0x00100700, %a2
    lea     0x00100800, %a4
    lea     0x00100900, %a5
    move.l  #0xdead000a, %d3
    move.l  #0xdead000b, %d7
    move.l  #0xdead000c, %d2
    move.l  #0xdead000d, %d5
    movem.l (%a7)+, %d0/%d2-%d7/%a0-%a6
    lea     (536,%a0), %a4
    lea     (952,%a0), %a6
    move.l  %a6, (520,%a0)
    move.l  #0x00009a43, %d7
    .word   0x2987, 0x0164, 0xfff0
    sf     %d0
    cmp.l   (236,%a3), %d0
fwd_65:
    tst.l   %a0
    cmpi.l  #0x8f6489a2, (%a2)
    moveq   #29, %d0
    movem.l %d3-%d4/%d6-%d7/%a1-%a2, -(%a7)
    move.l  #0xdead0000, %d6
    move.l  #0xdead0001, %d3
    move.l  #0xdead0002, %d4
    lea     0x00100300, %a1
    lea     0x00100400, %a2
    move.l  #0xdead0005, %d7
    movem.l (%a7)+, %d3-%d4/%d6-%d7/%a1-%a2
    move.l  %d2, 0x00104de8
    and.l   %d5, (%a3)
    smi     %d1
    cmp.l   -(%a1), %d3
    addq.l  #1, %d3
    beq     fwd_66
    addq.l  #5, %d0
    moveq   #-63, %d0
    move.l  #0xdeadbeef, (%a2)
    movea.l (%a2)+, %a4
fwd_66:
    moveq   #1, %d2
    bclr    %d1, %d1
    move.l  #0x00000001, %d3
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d3
    blt     shift_v_done_3983
    nop
shift_v_done_3983:
    move.l  0x00103ab4, %d5
    bhi    fwd_67
fwd_67:
    lea     0x00109f68, %a4
    moveq   #15, %d2
    add.l   %d4, %d3
    move.l  %d5, %d2
    move.l  %d2, %d0
    move.l  %d0, %d3
    move.l  %d3, %d4
    addq.l  #1, %d5
    beq    fwd_68
    movep.l 772(%a3), %d3
    mulu.w  (%a1), %d0
    tst.l   %d3
fwd_68:
    bchg    #27, %d4
    lea     (92,%a1), %a5
    move.w  %d2, (%a5)+
    and.l   %d0, (%a2)
    bfchg   %d5{%d2:18}
    clr.w   %d1
    bclr    %d3, %d3
    lea     (64,%a0), %a6
    move.b  #0xf6, (%a6)
    bchg    #5, (%a6)
    sub.l   %d1, %d1
    lea     0x00100000, %a4
    adda.l  (%a3)+, %a4
    move.b  (94,%a0), %d2
    lea     (444,%a0), %a4
    lea     (656,%a0), %a5
    lea     (428,%a0), %a6
    move.l  %a5, (%a6)
    lea     (656,%a0), %a6
    move.l  #0x0000097e, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    move.l  %d5, (72,%a1)
    tst.l   %d3
    move.l  %d4, (160,%a3)
    sgt     %d3
    beq    fwd_69
    jmp     jmp_70
    cmpi.l  #0x32da5235, %d1
    cmp.l   -(%a2), %d5
    lea     (12,%a1), %a5
    andi.l  #0xdeadbeef, (%a5)+
    muls.w  (6,%a3), %d2
fwd_69:
    movem.l %d0-%d7/%a0/%a2-%a6, -(%a7)
    move.l  #0xdead0000, %d0
    move.l  #0xdead0001, %d1
    lea     0x00100200, %a2
    lea     0x00100300, %a3
    lea     0x00100400, %a6
    move.l  #0xdead0005, %d2
    move.l  #0xdead0006, %d6
    move.l  #0xdead0007, %d3
    lea     0x00100800, %a5
    move.l  #0xdead0009, %d4
    move.l  #0xdead000a, %d5
    lea     0x00100b00, %a4
    lea     0x00100c00, %a0
    move.l  #0xdead000d, %d7
    movem.l (%a7)+, %d0-%d7/%a0/%a2-%a6
jmp_70:
    lea     0x00100000, %a4
    adda.l  (%a3)+, %a4
    tst.l   %d2
    and.l   (160,%a1), %d2
    move.l  0x0010fa14, %d2
    move.w  #0x0022, %d4
dbcc_71:
    addq.l  #1, %d5
    dbgt   %d4, dbcc_71
    sub.w   -(%a0), %d5
    bsr     sub_72
    move.l  %d5, 0x00105de0
    move.l  %d0, (212,%a3)
    svs     %d3
    link.l  %a6, #-512
    subq.l  #1, %d3
    unlk    %a6
    lea     0x00100000, %a5
    adda.l  -(%a0), %a5
    movep.w 994(%a2), %d5
    tst.l   %d5
    bne    fwd_73
fwd_73:
    move.l  #0x80000000, (%a3)
    movea.l (%a3)+, %a6
    sub.l   (%a0), %d0
    sge     %d4
    move.l  %d5, (64,%a2)
    move.l  %d0, (176,%a2)
    cmp.l   %d3, %d0
    bhi    fwd_74
    or.l    (%a0), %d1
    or.l    %d1, (%a2)
    and.l   (%a2), %d0
    bpl    fwd_75
    addq.l  #8, %d4
    move.l  %d2, (228,%a1)
    sub.w   (16,%a2), %d5
    muls.w  #0x8000, %d5
    subq.l  #1, %d4
    bne     fwd_76
    move.l  #0x00000009, %d1
    move.l  #0x00000087, %d0
    abcd    %d0, %d1
    and.l   (%a0), %d5
fwd_74:
    move.l  #0x4688b529, (%a2)
    movea.l (%a2)+, %a4
    lsl.l  #8, %d2
fwd_75:
    move.l  #0x000000c2, %d4
    mulu.l  %d3, %d5
fwd_76:
    beq    fwd_77
    addq.l  #5, %d3
    st     %d3
    move.l  #0xb8d9ed83, %d3
    move.l  %d2, 0x0010c848
fwd_77:
    ext.l   %d2
    add.w   -(%a0), %d2
    lea     (304,%a0), %a4
    lea     (668,%a0), %a5
    lea     (288,%a0), %a6
    move.l  %a5, (%a6)
    lea     (664,%a0), %a6
    move.l  #0x00000054, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    cmp.l   (%a2)+, %d0
    moveq   #0, %d1
    move.w  (%a3)+, %d1
    subq.l  #2, %a3
    lea     (500,%a0), %a4
    lea     (1044,%a0), %a6
    move.l  %a6, (484,%a0)
    move.l  #0xdeadbeef, %d7
    .word   0x2987, 0x0164, 0xfff0
    lea     (36,%a1), %a5
    move.l  #0x78a2, (%a5)+
    move.l  #0x00000016, %d1
    nbcd    %d1
    moveq   #0, %d3
    move.l  %d0, (%a2)
    lea     (236,%a1), %a5
    move.b  #0x52, (8,%a5)
    moveq   #1, %d5
    bset    %d5, (8,%a5)
    move.l  #0x0000009d, %d5
    mulu.w  (%a2), %d3
    lea     0x00100000, %a4
    adda.l  (100,%a1), %a4
    add.l   %d5, %d0
    lea     0x0010330c, %a5
    lea     (28,%a0), %a4
    move.b  #0x68, (%a4)
    moveq   #6, %d3
    bchg    %d3, (%a4)
    addi.l  #0x00009c6a, %d0
    move.b  (203,%a2), %d3
    move.l  #0x00000003, %d0
    move.l  #0x7fffffff, %d7
    divs.l  %d7, %d0:%d5
    move.l  %d3, %d3
    move.l  (0,%a2), %d2
    nop
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    move.l  #0x00000025, %d5
    nbcd    %d5
    bcc    fwd_78
    move.l  0x0010a66c, %d5
    movep.w 72(%a3), %d4
    asl.l  %d3, %d5
    rol.l  #5, %d0
    cmpm.l  (%a0)+, (%a1)+
fwd_78:
    subi.l  #0x35d95539, %d2
    moveq   #119, %d3
    cmp.l   (76,%a3), %d1
    add.w   (%a1), %d2
    beq    fwd_79
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (804,%a4), %a1
    lea     (1112,%a4), %a0
    moveq   #4, %d2
    move.l  #0x6c6bf8c9, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    or.l    (%a0), %d1
fwd_79:
    movem.l %d0-%d1/%d7/%a6, -(%a7)
    lea     0x00100000, %a6
    move.l  #0xdead0001, %d1
    move.l  #0xdead0002, %d7
    move.l  #0xdead0003, %d0
    movem.l (%a7)+, %d0-%d1/%d7/%a6
    and.l   (%a3)+, %d0
    move.l  (%a3), %d0
    cmpi.l  #0x000000fc, %d5
    lea     (392,%a0), %a4
    lea     (560,%a0), %a5
    lea     (376,%a0), %a6
    move.l  %a5, (%a6)
    lea     (556,%a0), %a6
    move.l  #0x0000ba1e, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    moveq   #4, %d0
    move.b  %d4, (4,%a3,%d0.l)
    ror.l  %d0, %d5
    bchg    #21, %d3
    shi     %d4
    exg     %d0, %d1
    movem.l %d1-%d7/%a0/%a2-%a3/%a5-%a6, -(%a7)
    move.l  #0xdead0000, %d6
    lea     0x00100100, %a6
    lea     0x00100200, %a5
    lea     0x00100300, %a0
    move.l  #0xdead0004, %d2
    lea     0x00100500, %a2
    lea     0x00100600, %a3
    move.l  #0xdead0007, %d7
    move.l  #0xdead0008, %d3
    move.l  #0xdead0009, %d1
    move.l  #0xdead000a, %d4
    move.l  #0xdead000b, %d5
    movem.l (%a7)+, %d1-%d7/%a0/%a2-%a3/%a5-%a6
    and.l   %d0, %d2
    sub.w   (240,%a2), %d3
    tst.l   %d0
    beq    fwd_80
    lea     (216,%a0), %a4
    lea     (188,%a1), %a5
    move.l  (%a4), (%a5)+
fwd_80:
    beq    fwd_81
    or.l    (28,%a3), %d1
fwd_81:
    move.l  #0x00000008, %d1
    move.l  #0x00000037, %d1
    abcd    %d1, %d1
    lea     0x00100000, %a5
    adda.l  (%a1)+, %a5
    cmpi.l  #0x7fffffff, (%a3)
    bpl    fwd_82
    cmpi.w  #0xad3f, (16,%a0)
fwd_82:
    sub.l   %d3, %d1
    move.l  #0x00000090, %d4
    move.l  #0x00000036, %d7
    abcd    %d7, %d4
    lea     (380,%a0), %a4
    lea     (896,%a0), %a5
    lea     (728,%a0), %a6
    move.l  %a6, (364,%a0)
    move.l  #0x00000037, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    mulu.l  %d4, %d1
    cmpm.l  (%a0)+, (%a1)+
    add.b   (%a0)+, %d3
    andi.l  #0x00000049, %d4
    bra    fwd_83
    cmpi.l  #0x0000b197, %d3
    lea     (60,%a1), %a5
    andi.l  #0x000000f7, (%a5)+
fwd_83:
    move.l  #0x0000c995, %d7
    pack    %d7, %d3, #0x9e68
    not.l   %d1
    bra    fwd_84
    lea     0x00100000, %a4
    adda.l  (64,%a2), %a4
    addq.b  #1, (140,%a2)
    tst.w   (%a2)
fwd_84:
    subq.l  #1, %d3
    move.w  #0x000c, %d5
dbcc_85:
    addq.l  #1, %d4
    dbne   %d5, dbcc_85
    subq.l  #2, %d0
    and.l   %d3, (%a0)
    move.w  #0x003d, %d4
dbcc_86:
    addq.l  #1, %d2
    dbcc   %d4, dbcc_86
    lea     (244,%a0), %a4
    tst.l   (%a4)+
    lea     0x00100000, %a4
    .word   0xb8f8, 0x1200
    move.l  #0xFFFFFFFF, %d3
    andi.l  #0x0000003f, %d2  | dynamic count in 0..63
    asl.l   %d2, %d3
    bge     shift_v_done_8e80
    nop
shift_v_done_8e80:
    add.b   (%a2)+, %d4
    cmp.l   -(%a0), %d5
    muls.l  #0x80000000, %d3
    move.l  #0x00000007, %d1
    move.l  #0x00000009, %d7
    divs.l  %d7, %d1:%d2
    move.w  #0x8913, (180,%a1)
    clr.b   (164,%a0)
    add.l   %d5, %d1
    lea     (12,%a1), %a5
    move.b  #0x7c, (2,%a5)
    moveq   #10, %d4
    btst    %d4, (2,%a5)
    addi.l  #0x000000d0, %d4
    move.l  #0x00000002, %d5
    move.l  #0x0000000d, %d7
    divu.l  %d7, %d5:%d3
    muls.l  %d2, %d5
    add.b   -(%a1), %d0
    move.l  #0x000018b6, %d4
    eori.w  #0x7eea, %d4
    tst.l   %d4
    move.w  #0x003f, %d5
dbcc_87:
    addq.l  #1, %d2
    dbmi   %d5, dbcc_87
    lea     (252,%a1), %a5
    move.w  #0xb3f5, (%a5)+
    clr.w   %d1
    and.l   (%a2), %d4
    movem.l %d0-%d2/%d4-%d5/%d7/%a0/%a3-%a4, -(%a7)
    move.l  #0xdead0000, %d5
    move.l  #0xdead0001, %d1
    move.l  #0xdead0002, %d7
    lea     0x00100300, %a3
    move.l  #0xdead0004, %d0
    lea     0x00100500, %a0
    move.l  #0xdead0006, %d4
    move.l  #0xdead0007, %d2
    lea     0x00100800, %a4
    movem.l (%a7)+, %d0-%d2/%d4-%d5/%d7/%a0/%a3-%a4
    move.l  %d2, (%a3)
    lea     (104,%a0), %a4
    lea     (144,%a1), %a5
    move.l  (%a4), (%a5)+
    and.l   (228,%a0), %d1
    cmp.l   (%a2)+, %d3
    movea.l (%a1), %a5
    move.l  %a0, %a3
    adda.l  #1008, %a3
    move.l  %a0, %a4
    adda.l  #1272, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x099e34b2, (%a4)
    moveq   #4, %d4
    .word   0xedf3, 0x0224, 0x0164, 0x0010
    move.l  #0x00000063, %d2
    move.l  #0x00000094, %d1
    sbcd    %d1, %d2
    and.l   %d3, %d0
    bcc    fwd_88
    eor.l   %d2, %d2
    add.l   %d4, %d1   | sets X for chain
    addx.l  %d0, %d2
    subx.l  %d1, %d4
    addq.l  #3, %d3
    cmpi.l  #0x000052db, %d2
    ror.l  #2, %d2
fwd_88:
    tst.w   %a2
    rol.l  %d5, %d4
    bchg    #19, %d4
    bpl    fwd_89
    move.l  0x0010cf74, %d1
fwd_89:
    addi.l  #0x00000475, %d1
    subq.l  #7, %d0
    moveq   #116, %d0
    exg     %d3, %d4
    lea     (540,%a0), %a4
    lea     (996,%a0), %a6
    move.l  %a6, (524,%a0)
    move.l  #0x000028f4, %d7
    .word   0x2987, 0x0164, 0xfff0
    move.l  #0xd1d9bbf8, %d1
    ori.l  #0x18b6cc6a, %d2
    add.b   -(%a2), %d1
    cmpi.l  #0x000000d5, (%a0)
    move.l  #0x00000010, %d1
    move.l  #0x00000080, %d5
    sbcd    %d5, %d1
    move.l  %d5, %d5
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (836,%a4), %a1
    lea     (1036,%a4), %a0
    moveq   #0, %d2
    move.l  #0x0000c44d, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    moveq   #-60, %d5
    tst.l   %a1
    cmp.l   %d3, %d0
    nop
    bhi    fwd_90
fwd_90:
    lea     0x0010a490, %a5
    movep.l 442(%a2), %d2
    smi     %d4
    lea     (148,%a0), %a4
    tst.l   (%a4)+
    lea     (324,%a0), %a4
    lea     (572,%a0), %a5
    lea     (308,%a0), %a6
    move.l  %a5, (%a6)
    lea     (572,%a0), %a6
    move.l  #0x00000095, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    moveq   #1, %d0
    bra     _pcidx_after_92
_pcidx_tbl_91:
    .byte   0xa2, 0x98, 0x88, 0xf6
    .align  2
_pcidx_after_92:
    move.b  _pcidx_tbl_91(%pc,%d0.w), %d5
    ext.l   %d2
    lea     (116,%a0), %a4
    lea     (155,%a1), %a5
    move.b  (%a4)+, (%a5)+
    move.l  %d4, %d1
    move.l  %d1, %d6
    move.l  %d6, %d5
    move.l  %d5, %d2
    move.l  %d2, %d3
    move.l  %d3, %d0
    swap    %d0
    bclr    %d4, %d3
    bne    fwd_93
    cmp.l   %d4, %d2
    add.l   %d0, %d0   | sets X for chain
    addx.l  %d3, %d1
    subx.l  %d2, %d1
    addx.l  %d1, %d4
    cmp.l   (%a3)+, %d1
    move.l  #0x00000044, %d6
    nbcd    %d6
    move.l  (%a0), %d1
    moveq   #63, %d6
back_94:
    addq.l  #1, %d2
    subq.l  #1, %d6
    bcc     back_94
    moveq   #3, %d6
    move.l  #0x000042ea, %d0
fwd_93:
    cmpi.l  #0x58220b9a, %d1
    bpl    fwd_95
    movea.l %d4, %a5
    link.l  %a6, #8
    subq.l  #1, %d3
    unlk    %a6
    subq.l  #1, %d3
    bne     fwd_96
    lea     (8,%a0), %a3
    move.b  #0xea, (%a3)
    bclr    #5, (%a3)+
fwd_95:
    jmp     jmp_97
fwd_96:
    and.l   (%a0)+, %d2
    move.l  #0x00000000, %d1
    move.l  #0x00010000, %d7
    divu.l  %d7, %d1:%d3
    move.l  (%a1)+, %d2
    move.l  #0x00000066, %d6
    move.l  #0x00000070, %d4
    sbcd    %d4, %d6
    subq.l  #5, %d4
    bfexts  %d3{16:%d0}, %d1
jmp_97:
    and.l   (%a3), %d1
    rol.l  %d5, %d4
    beq    fwd_98
    mulu.l  %d1, %d2
    lea     0x00100000, %a5
    adda.w  %a2, %a5
fwd_98:
    move.l  #0x123456a5, %d4
    not.b   %d4
    tst.l   %d0
    tst.l   %d3
    beq    fwd_99
fwd_99:
    tst.l   %d5
    addi.l  #0xffffffff, %d2
    or.l    (%a0), %d3
    tst.l   %d4
    beq    fwd_100
    btst    #0, %d1
    move.l  #0x00000000, %d0
fwd_100:
    move.l  (92,%a0), %d4
    lea     0x00103284, %a4
    exg     %d0, %a6
    moveq   #0, %d5
    bra     _pcidxw_after_102
_pcidxw_tbl_101:
    .word   0x5857, 0xf2b2, 0x06e6, 0xc126
_pcidxw_after_102:
    move.w  _pcidxw_tbl_101(%pc,%d5.w*2), %d5
    or.l    %d0, (%a3)
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (852,%a4), %a1
    lea     (1092,%a4), %a0
    moveq   #0, %d2
    move.l  #0x0000000b, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    or.l    (104,%a3), %d3
    or.l    (0,%a3), %d0
    lea     (228,%a0), %a4
    add.b   %d2, (%a4)+
    movep.l %d2, -8(%a2)
    move.l  %d5, (144,%a2)
    lea     0x0010b2a0, %a6
    roxl.l  %d2, %d4
    move.l  #0x00000001, %d7
    divsl.l  %d7, %d0:%d6
    move.l  0x001016cc, %d5
    or.l    %d2, (%a3)
    or.l    (156,%a2), %d4
    mulu.l  %d0, %d3
    move.l  #0x00000007, %d7
    divs.l  %d7, %d3
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    move.l  #0x00000011, %d7
    divu.l  %d7, %d3
    subi.l  #0xdd70349b, %d2
    blt    fwd_103
    move.l  #0xfffffffe, %d7
    divu.l  %d7, %d5
    and.l   (120,%a3), %d5
fwd_103:
    ori.l  #0x00007ab1, %d2
    or.l    (%a1)+, %d5
    tst.w   %a1
    move.l  %d4, 0x001053a0
    move.w  #0x0037, %d5
dbcc_104:
    addq.l  #1, %d1
    dbge   %d5, dbcc_104
    lea     0x00100000, %a4
    adda.l  (%a0), %a4
    lea     (156,%a0), %a4
    move.b  #0x16, (%a4)
    bset    #10, (%a4)
    cmp.l   (%a0), %d4
    cmp.l   (36,%a0), %d2
    tst.l   %a0
    bfins   %d3, %d0{24:18}
    move.l  0x00101424, %d0
    cmp.l   %d4, %d4
    bge    fwd_105
    cmp.l   %d2, %d1
    cmp.l   -(%a1), %d1
fwd_105:
    scs     %d1
    tst.b   (172,%a2)
    subq.l  #8, %d0
    move.l  %d3, (152,%a2)
    bftst   %d3{1:30}
    move.l  #0x00000085, %d6
    move.l  #0x00000038, %d5
    sbcd    %d5, %d6
    sub.b   (%a1), %d5
    bclr    #1, %d0
    move.l  %d1, (128,%a0)
    move.l  #0x13bc88b2, (16,%a0)
    cmp.l   (%a1), %d0
    lea     (184,%a1), %a5
    move.w  %d5, (%a5)+
    sub.l   %d0, %d0
    and.l   (188,%a0), %d0
    lea     (180,%a1), %a5
    move.b  #0x29, (12,%a5)
    bclr    #9, (12,%a5)
    move.l  #0x2dd3fccf, %d4
    subq.l  #1, %d2
    bne     fwd_106
    and.l   %d1, %d1
fwd_106:
    bgt    fwd_107
    nop
    move.l  %d6, %d5
    move.l  %d5, %d1
    move.l  %d1, %d3
    move.l  %d3, %d2
    move.l  %d2, %d4
    move.l  %d4, %d0
fwd_107:
    move.l  #0x000009b9, %d1
    bgt    fwd_108
    nop
fwd_108:
    move.l  %a0, %a2
    adda.l  #960, %a2
    move.l  %a0, %a4
    adda.l  #1168, %a4
    move.l  %a4, 16(%a2)
    move.l  #0xffffffff, (%a4)
    move.l  #0x0000c3ba, %d5
    moveq   #13, %d1
    .word   0xeff2, 0x5843, 0x0164, 0x0010
    bcs    fwd_109
    bhi    fwd_110
    movep.w %d4, 636(%a0)
    move.l  #0xFFFFFFFE, %d5
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d5
    bge     shift_v_done_65f6
    nop
shift_v_done_65f6:
    moveq   #65, %d1
fwd_109:
    addq.w  #7, (252,%a3)
    shi     %d3
    moveq   #3, %d6
back_111:
    addq.l  #1, %d3
    subq.l  #1, %d6
    beq     back_111
    moveq   #3, %d6
    move.w  #0x15ea, (120,%a1)
    sub.l   (92,%a1), %d3
    bge    fwd_112
    cmp.l   %d4, %d5
fwd_110:
    addq.l  #1, %d3
fwd_112:
    lea     0x00100000, %a6
    adda.l  (216,%a2), %a6
    move.l  0x0010a398, %d4
    moveq   #-45, %d1
    move.l  #0x80000001, %d1
    andi.l  #0x0000003f, %d3  | dynamic count in 0..63
    asl.l   %d3, %d1
    bge     shift_v_done_b07a
    nop
shift_v_done_b07a:
    lea     (4,%a0), %a4
    add.l   %d2, (%a4)+
    and.l   (244,%a2), %d2
    and.l   (220,%a1), %d3
    lea     (132,%a0), %a4
    cmpi.w  #0x61e6, (%a4)+
    add.w   %d3, (%a1)
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (772,%a4), %a1
    lea     (1040,%a4), %a0
    moveq   #0, %d2
    move.l  #0x7fffffff, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    add.l   %d4, %d2   | sets X for chain
    subx.l  %d1, %d1
    addx.l  %d1, %d4
    move.l  #0x00000002, %d2
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d2
    blt     shift_v_done_9739
    nop
shift_v_done_9739:
    subq.l  #1, %d2
    bne     fwd_113
    move.l  %a0, %a1
    adda.l  #976, %a1
    move.l  %a0, %a4
    adda.l  #1168, %a4
    move.l  %a4, 16(%a1)
    move.l  #0xa7239399, (%a4)
    moveq   #12, %d3
    .word   0xe9f1, 0x58c5, 0x0164, 0x0010
    or.l    (%a3)+, %d5
fwd_113:
    addq.l  #6, %d1
    bclr    #6, %d4
    move.l  #0x00000002, %d7
    move.l  #0x00000005, %d6
    divu.l  %d6, %d7:%d4
    add.w   (%a2)+, %d4
    subq.l  #3, %d2
    lea     (460,%a0), %a4
    lea     (1000,%a0), %a5
    lea     (764,%a0), %a6
    move.l  %a6, (444,%a0)
    move.l  #0x756cb09b, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    lea     0x00107434, %a5
    cmpm.l  (%a0)+, (%a2)+
    add.b   (40,%a3), %d1
    moveq   #116, %d2
    lea     0x00100000, %a4
    adda.l  (32,%a2), %a4
    bchg    #15, %d3
    blt    fwd_114
    moveq   #0, %d2
    bra     _pcidxw_after_116
_pcidxw_tbl_115:
    .word   0xd277, 0x2118, 0x0858, 0xd77e
_pcidxw_after_116:
    move.w  _pcidxw_tbl_115(%pc,%d2.w*2), %d5
fwd_114:
    move.l  #0x000000d1, %d7
    unpk    %d7, %d7, #0x3030
    cmp.l   (%a3)+, %d3
    bra    fwd_117
    movep.l %d0, 940(%a3)
fwd_117:
    mulu.w  (%a1), %d0
    lea     0x00100000, %a4
    adda.l  -(%a2), %a4
    tst.l   %d1
    bge    fwd_118
fwd_118:
    or.l   %d3, %d1
    sub.w   (64,%a0), %d2
    cmp.l   (124,%a2), %d3
    tst.w   %a1
    tst.l   %d5
    bmi    fwd_119
fwd_119:
    move.w  #0x000e, %d4
dbcc_120:
    addq.l  #1, %d2
    dbpl   %d4, dbcc_120
    ble    fwd_121
    tst.l   %d3
    bfclr   %d0{29:%d4}
    subi.l  #0x0000cbc0, %d4
    lea     0x00100000, %a5
    move.l  #0x00008000, %d1
    adda.w  %d1, %a5
    cmp.l   (112,%a3), %d1
fwd_121:
    bchg    %d3, %d4
    tst.l   (%a1)
    divu.w  #0x7fff, %d2
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    ble    fwd_122
    cmpi.l  #0x00000038, %d1
    move.l  #0x000000e5, %d1
    unpk    %d1, %d2, #0x3030
fwd_122:
    lea     (184,%a1), %a5
    move.l  #0x69, (%a5)+
    shi     %d4
    moveq   #58, %d1
    neg.l   %d4
    moveq   #-46, %d1
    move.l  %d3, (%a3)
    move.l  %d2, %d1
    asr.l  %d5, %d2
    clr.w   %d0
    asl.l  #5, %d3
    ori.l  #0x00000086, %d2
    svc     %d5
    move.l  #0x00000071, %d0
    andi.b  #0x0007, %d0
    tst.l   %d0
    blt    fwd_123
fwd_123:
    link.l  %a6, #-16
    subq.l  #1, %d5
    unlk    %a6
    sls     %d5
    cmpi.l  #0xffffffff, %d0
    nop
    movep.w %d2, 72(%a0)
    add.b   (%a1), %d2
    sub.b   -(%a3), %d5
    lea     (516,%a0), %a4
    lea     (1012,%a0), %a6
    move.l  %a6, (500,%a0)
    move.l  #0x00000006, %d7
    .word   0x2987, 0x0164, 0xfff0
    lea     (148,%a0), %a4
    move.b  #0xaf, (%a4)
    btst    #9, (%a4)
    move.l  (184,%a2), %d3
    eor.l   %d4, %d4
    sf     %d1
    exg     %a6, %a5
    sgt     %d0
    bhi    fwd_124
    moveq   #-36, %d5
    scs     %d3
    cmp.l   %d1, %d0
    and.l   (%a3), %d0
fwd_124:
    lea     0x00100000, %a5
    adda.l  -(%a0), %a5
    cmp.l   %d2, %d1
    jmp     jmp_125
    move.l  (%a3), %d4
    and.l   %d2, (%a3)
jmp_125:
    moveq   #21, %d2
    and.l   (%a1), %d4
    lea     0x00100000, %a4
    adda.l  -(%a1), %a4
    cmp.l   -(%a2), %d2
    sub.l   %d5, %d0
    tst.l   %d2
    move.l  (164,%a1), %d4
    clr.b   (240,%a3)
    lea     (92,%a0), %a4
    move.b  #0x53, (%a4)
    bset    #3, (%a4)
    lea     0x00100000, %a4
    adda.w  %a2, %a4
    move.l  #0x00000001, %d0
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d0
    ble     shift_v_done_ceea
    nop
shift_v_done_ceea:
    add.l   %d0, %d1
    link.l  %a6, #-512
    subq.l  #1, %d4
    unlk    %a6
    movep.l %d3, 494(%a0)
    move.l  %d2, 0x00106b80
    subq.l  #1, %d1
    bne     fwd_126
    not.l   %d5
    cmp.l   -(%a0), %d4
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (840,%a4), %a1
    lea     (1132,%a4), %a0
    moveq   #4, %d2
    move.l  #0x000000c5, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    move.l  %d5, %d0
    move.l  %d0, %d6
    move.l  %d6, %d2
    move.l  %d2, %d3
    move.l  %d3, %d1
    move.l  %d1, %d4
fwd_126:
    muls.w  %d5, %d4
    move.l  (152,%a1), %d2
    move.l  (%a1), %d1
    beq    fwd_127
fwd_127:
    and.l   (84,%a2), %d1
    move.l  %d5, (148,%a2)
    add.l   %d0, %d2   | sets X for chain
    subx.l  %d4, %d2
    subx.l  %d4, %d5
    cmp.l   (%a3), %d4
    bfset   %d2{7:22}
    subq.w  #4, %d2
    lea     0x00100000, %a4
    adda.l  -(%a3), %a4
    lea     (116,%a1), %a5
    andi.l  #0xdeadbeef, (%a5)+
    cmp.l   (%a3)+, %d0
    lea     (96,%a0), %a6
    move.b  #0xbb, (%a6)
    bchg    #7, (%a6)+
    bset    #24, %d0
    move.l  (%a3), %d1
    cmp.l   -(%a0), %d2
    movea.l (%a3), %a5
    rol.w  #6, %d2
    move.l  %d0, (60,%a0)
    cmp.l   %d0, %d1
    lea     (112,%a0), %a4
    moveq   #0, %d5
    and.w   (12,%a4,%d5.l*1), %d3
    movea.l (236,%a2), %a6
    bcs    fwd_128
    exg     %a6, %a5
    lea     (484,%a0), %a4
    lea     (1036,%a0), %a6
    move.l  %a6, (468,%a0)
    move.l  #0x000000da, %d7
    .word   0x2987, 0x0164, 0xfff0
    move.l  #0x00000000, %d5
    move.l  #0x00000086, %d3
    abcd    %d3, %d5
    divs.l  #0xa5a5a5a5, %d5
fwd_128:
    move.w  #0x0001, %d5
dbcc_129:
    addq.l  #1, %d0
    dbpl   %d5, dbcc_129
    move.l  #0x1c9e7588, %d5
    lea     0x00102fc8, %a4
    lea     0x00100000, %a6
    adda.l  (%a0), %a6
    move.l  #0x00000007, %d7
    divu.l  %d7, %d5
    bne    fwd_130
    move.l  #0x80000000, %d4
    move.l  #0x00000032, %d1
    move.l  #0x00000062, %d4
    sbcd    %d4, %d1
    add.w   (156,%a0), %d4
    move.l  #0xffffffff, %d0
fwd_130:
    clr.w   %d4
    move.l  (4,%a1), %d0
    or.l    (%a3)+, %d1
    cmp.l   %d3, %d0
    or.l    (224,%a0), %d1
    moveq   #-14, %d2
    lea     (4,%a1), %a5
    move.w  #0xc9ba, (%a5)+
    scs     %d2
    or.l    (%a0), %d3
    link.l  %a6, #-16
    subq.l  #1, %d0
    unlk    %a6
    asl.l  %d1, %d5
    or.l    (120,%a3), %d4
    move.l  #0x00FF00FF, %d0
    andi.l  #0x0000003f, %d3  | dynamic count in 0..63
    asl.l   %d3, %d0
    bgt     shift_v_done_96d6
    nop
shift_v_done_96d6:
    move.l  %d6, %d3
    move.l  %d3, %d0
    move.l  %d0, %d5
    move.l  #0x00005ad7, %d3
    pack    %d3, %d3, #0x0000
    link.l  %a6, #-64
    subq.l  #1, %d5
    unlk    %a6
    asl.l  #2, %d1
    neg.l   %d2
    bclr    #3, %d1
    add.l   (76,%a1), %d4
    lea     (112,%a0), %a3
    move.b  #0x9d, (%a3)
    btst    #5, (%a3)
    lea     0x00100000, %a4
    adda.l  (%a3)+, %a4
    addi.l  #0x0000f32d, %d4
    sub.l   %d2, %d2
    bchg    #23, %d4
    cmp.l   (%a2), %d3
    cmp.l   %d1, %d5
    move.l  %d2, %d0
    lea     (20,%a1), %a5
    move.b  #0xc5, (12,%a5)
    btst    #5, (12,%a5)
    or.l    %d4, (%a3)
    move.l  (%a2), %d4
    bne    fwd_131
    movep.w %d0, 558(%a3)
    bne    fwd_132
    btst    #1, %d1
fwd_131:
fwd_132:

_end:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt

sub_28:
    addq.l  #1, %d1
    addq.l  #1, %d3
    addq.l  #1, %d5
    rts

sub_49:
    addq.l  #1, %d1
    addq.l  #1, %d0
    addq.l  #1, %d0
    rts

sub_72:
    addq.l  #1, %d5
    addq.l  #1, %d0
    addq.l  #1, %d5
    rts
