| Auto-generated by gen_program.py --seed 1391
    .text
    .org 0

_start:
    lea     0x00080000, %a7   | stack top
    lea     0x00100000, %a0   | A0 data pool
    lea     0x00104000, %a1   | A1 data pool
    lea     0x00108000, %a2   | A2 data pool
    lea     0x0010c000, %a3   | A3 data pool
    move.l  #0x0000b23e, %d0   | D0 init (B1b)
    move.l  #0x0000cb50, %d1   | D1 init (B1b)
    move.l  #0xba4b3147, %d2   | D2 init (B1b)
    move.l  #0xffffffff, %d3   | D3 init (B1b)
    movea.l #0x00000076, %a4  | A4 init (B1b)
    movea.l #0x00000001, %a5  | A5 init (B1b)
    movea.l #0xbc000989, %a6  | A6 init (B1b)
    moveq   #3, %d6           | D6 = hop counter
    moveq   #0, %d4
    moveq   #0, %d5

    move.l  %d4, (36,%a1)
    lea     0x00100000, %a5
    adda.l  (172,%a2), %a5
    add.w   -(%a0), %d2
    lea     (68,%a0), %a4
    not.l   (%a4)+
    moveq   #-51, %d5
    moveq   #63, %d6
back_1:
    addq.l  #1, %d3
    subq.l  #1, %d6
    bhi     back_1
    moveq   #3, %d6
    and.l   (%a2), %d4
    bge    fwd_2
fwd_2:
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (796,%a4), %a1
    lea     (1136,%a4), %a0
    moveq   #0, %d2
    move.l  #0x00000001, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    cmp.l   -(%a3), %d1
    and.l   %d3, %d0
    movep.l -8(%a2), %d2
    move.l  #0xFFFFFFFE, %d3
    andi.l  #0x0000003f, %d4  | dynamic count in 0..63
    asl.l   %d4, %d3
    blt     shift_v_done_ab15
    nop
shift_v_done_ab15:
    or.l    (%a1), %d0
    or.l    (%a2), %d3
    cmpi.l  #0x7fffffff, (%a3)
    move.l  #0x80000000, %d5
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d5
    blt     shift_v_done_5dcb
    nop
shift_v_done_5dcb:
    eor.l   %d1, %d1
    moveq   #3, %d1
    bra     _pcidxw_after_4
_pcidxw_tbl_3:
    .word   0xb29b, 0xc0b4, 0x6dc6, 0x3542
_pcidxw_after_4:
    move.w  _pcidxw_tbl_3(%pc,%d1.w*2), %d4
    move.l  (108,%a0), %d1
    move.l  (%a1), %d4
    bgt    fwd_5
fwd_5:
    link.l  %a6, #-16
    subq.l  #1, %d2
    unlk    %a6
    lea     (504,%a0), %a4
    lea     (808,%a0), %a5
    lea     (536,%a0), %a6
    move.l  %a5, (%a6)
    lea     (808,%a0), %a6
    move.l  #0x00002101, (%a6)
    move.l  #0x00006a12, %d7
    move.l  #0x00000000, %d1
    .word   0xDEB4, 0x1921, 0x0020
    move.l  0x00100c78, %d5
    bclr    #5, %d2
    move.w  #0x0014, %d5
dbcc_6:
    addq.l  #1, %d4
    dbra   %d5, dbcc_6
    ext.l   %d5
    bfins   %d4, %d5{17:%d0}
    bset    #18, %d0
    add.l   %d3, (%a3)
    move.b  (86,%a0), %d1
    lea     0x0010ca04, %a4
    bfextu  %d4{15:1}, %d1
    tst.l   %d5
    bchg    #17, %d0
    lea     (512,%a0), %a4
    lea     (848,%a0), %a5
    lea     (544,%a0), %a6
    move.l  %a5, (%a6)
    lea     (848,%a0), %a6
    move.l  #0x000000e9, (%a6)
    move.l  #0x000094aa, %d1
    .word   0xD2B4, 0x0164, 0x0020
    move.l  #0x0000003f, %d2
    eori.b  #0x00e2, %d2
    tst.l   %d2
    move.b  (106,%a1), %d5
    lea     0x0010b444, %a5
    moveq   #10, %d6
back_7:
    addq.l  #1, %d5
    subq.l  #1, %d6
    bls     back_7
    moveq   #3, %d6
    clr.w   %d3
    lsr.l  %d5, %d1
    or.l    %d5, (%a2)
    bsr     sub_8
    lea     0x00100000, %a6
    adda.l  (%a2), %a6
    and.l   (%a2)+, %d0
    move.l  #0x00000097, %d5
    move.l  #0x00000003, %d4
    sbcd    %d4, %d5
    btst    %d5, %d4
    move.l  %d0, %d4
    sne     %d0
    or.l    (%a2), %d5
    subq.l  #2, %d2
    tst.l   %a3
    move.l  %d2, (84,%a1)
    mulu.w  %d2, %d0
    lea     0x00100000, %a5
    adda.w  (72,%a1), %a5
    bclr    #11, %d3
    moveq   #-113, %d5
    and.l   (%a2)+, %d3
    bhi    fwd_9
    cmp.l   (204,%a3), %d5
fwd_9:
    move.l  0x00105258, %d2
    move.l  #0x00000080, %d2
    move.l  #0x00000005, %d6
    abcd    %d6, %d2
    lea     0x00100000, %a5
    adda.w  (68,%a1), %a5
    tst.l   %d0
    movea.l (44,%a2), %a6
    subi.l  #0x00000059, %d5
    eor.l   %d2, %d2
    clr.w   %d2
    sub.l   %d4, (60,%a1)
    lea     (96,%a0), %a4
    add.w   %d1, (%a4)+
    lea     (52,%a1), %a5
    move.b  #0xb5, (4,%a5)
    bchg    #7, (4,%a5)
    cmp.l   -(%a1), %d0
    move.l  #0x1289c342, %d0
    and.l   %d3, (%a0)
    cmp.l   %d3, %d5
    move.l  #0x00000002, %d1
    move.l  #0xdeadbeef, %d7
    divu.l  %d7, %d1:%d2
    sub.b   -(%a3), %d2
    divu.w  #0x007f, %d2
    muls.l  %d5, %d2
    move.l  #0x00000003, %d3
    move.l  #0xdeadbeef, %d7
    divs.l  %d7, %d3:%d2
    scc     (38,%a3)
    cmp.l   (48,%a2), %d0
    lea     (488,%a0), %a4
    lea     (932,%a0), %a5
    lea     (744,%a0), %a6
    move.l  %a6, (472,%a0)
    move.l  #0x000072f7, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    move.l  %d3, %d1
    add.l   -(%a0), %d3
    bpl    fwd_10
    addq.b  #5, (124,%a2)
    ori.l  #0x00004ea4, %d4
fwd_10:
    divs.l  #0x00000007, %d3
    move.l  #0x8ff68e2e, %d2
    move.l  %d0, (%a0)
    tst.l   %d4
    lea     0x00100000, %a4
    adda.w  (224,%a0), %a4
    add.l   %d2, %d0   | sets X for chain
    subx.l  %d2, %d1
    subx.l  %d4, %d5
    subx.l  %d5, %d2
    move.l  #0x000000cb, %d4
    nop
    or.l    (%a0), %d5
    lea     (484,%a0), %a4
    lea     (948,%a0), %a6
    move.l  %a6, (468,%a0)
    move.l  #0x0000d142, %d7
    .word   0x2987, 0x0164, 0xfff0
    tst.l   %d5
    and.l   %d4, (%a1)
    sub.w   -(%a2), %d5
    addi.l  #0xd7457ce4, %d4
    sub.b   %d5, (144,%a3)
    sub.w   (%a1)+, %d2
    lea     (208,%a0), %a4
    move.b  #0x71, (%a4)
    bchg    #0, (%a4)
    moveq   #-37, %d0
    lea     (132,%a0), %a4
    negx.w   (%a4)+
    subq.l  #5, %d2
    moveq   #3, %d6
back_11:
    addq.l  #1, %d0
    subq.l  #1, %d6
    bhi     back_11
    moveq   #3, %d6
    add.w   (%a2), %d4
    lea     (96,%a0), %a4
    tst.b   -(%a4)
    move.l  %d2, %d1
    move.l  %d2, (208,%a0)
    rol.l  #7, %d0
    and.l   (%a2)+, %d0
    clr.w   %d4
    sub.b   %d1, (12,%a1)
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    asr.l  %d0, %d5
    cmpi.l  #0x00008640, (%a3)
    moveq   #10, %d6
back_12:
    addq.l  #1, %d4
    subq.l  #1, %d6
    bcs     back_12
    moveq   #3, %d6
    add.l   -(%a0), %d5
    bclr    %d0, %d3
    moveq   #4, %d0
    lea     (13,%a0), %a4
    move.b  (%a4)+, (6,%a2,%d0.l)
    move.l  #0x00000046, %d6
    nbcd    %d6
    add.b   %d1, (%a1)
    move.l  %d1, %d5
    move.l  %d5, %d0
    move.l  %d0, %d4
    or.l   %d3, %d1
    movea.l 0x0010def8, %a4
    lea     (53,%a0), %a4
    lea     (39,%a1), %a5
    move.b  (%a4)+, (%a5)+
    addq.w  #2, %d2
    divu.l  #0x00000100, %d3
    lea     (%a0), %a4
    neg.w   (200,%a4)
    sle     %d5
    movep.l 544(%a1), %d1
    moveq   #3, %d6
back_13:
    addq.l  #1, %d4
    subq.l  #1, %d6
    beq     back_13
    moveq   #3, %d6
    lea     (64,%a1), %a5
    move.b  #0x50, (4,%a5)
    bset    #15, (4,%a5)
    slt     %d5
    bcs    fwd_14
    subq.l  #7, %d4
fwd_14:
    or.l    (%a2)+, %d1
    lea     (496,%a0), %a4
    moveq   #16, %d5
    and.l   (12,%a4,%d5.l*8), %d2
    lea     (80,%a0), %a4
    tst.w   (%a4)+
    subi.l  #0x608b611d, %d1
    move.l  %d4, (100,%a2)
    bfexts  %d5{%d0:25}, %d2
    bmi    fwd_15
    sls     %d5
    ext.l   %d1
    or.l    %d2, (%a1)
    move.l  %d5, %d3
fwd_15:
    subq.l  #6, %d5
    jmp     jmp_16
jmp_16:
    lea     (152,%a0), %a4
    move.b  #0x25, (%a4)
    bset    #5, (%a4)
    lea     (36,%a0), %a4
    tst.l   (%a4)+
    movep.w %d2, 144(%a1)
    cmpi.w  #0x1308, (92,%a1)
    eori.l  #0x00004d9d, %d3
    lea     0x00100000, %a6
    .word   0xbdf9, 0x0010, 0xa250
    lea     (464,%a0), %a4
    lea     (948,%a0), %a5
    lea     (744,%a0), %a6
    move.l  %a6, (448,%a0)
    move.l  #0x80000000, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    lea     (540,%a0), %a4
    lea     (860,%a0), %a5
    lea     (572,%a0), %a6
    move.l  %a5, (%a6)
    lea     (860,%a0), %a6
    move.l  #0x0000ce03, (%a6)
    move.l  #0x0000b748, %d3
    move.l  #0x00000000, %d1
    .word   0xD6B4, 0x1925, 0x0020
    ror.l  #5, %d3
    subq.l  #1, %d4
    bne     fwd_17
    bpl    fwd_18
    addq.l  #5, %d1
    nop
fwd_17:
    movep.w 780(%a2), %d3
    sub.l   %d5, (20,%a2)
    link.l  %a6, #-512
    subq.l  #1, %d1
    unlk    %a6
    spl     %d5
    lea     (544,%a0), %a4
    lea     (924,%a0), %a5
    lea     (576,%a0), %a6
    move.l  %a5, (%a6)
    lea     (924,%a0), %a6
    move.l  #0x0000f631, (%a6)
    move.l  #0xfc44c38d, %d0
    move.l  #0x00000000, %d1
    .word   0xD0B4, 0x1925, 0x0020
    lea     (516,%a0), %a4
    lea     (980,%a0), %a6
    move.l  %a6, (500,%a0)
    move.l  #0x00003928, %d7
    .word   0x2987, 0x0164, 0xfff0
    lea     (444,%a0), %a4
    lea     (1048,%a0), %a6
    move.l  %a6, (428,%a0)
    move.l  #0x000000b9, %d7
    .word   0x2987, 0x0164, 0xfff0
fwd_18:
    addq.l  #2, %d3
    bls    fwd_19
    lea     (408,%a0), %a4
    lea     (612,%a0), %a5
    lea     (392,%a0), %a6
    move.l  %a5, (%a6)
    lea     (612,%a0), %a6
    move.l  #0x5ad62f08, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    lea     (68,%a1), %a5
    andi.l  #0x00000089, (%a5)+
    move.l  %d5, %d0
    move.l  %d0, %d4
    move.l  %d4, %d6
    move.l  %d6, %d3
    move.l  %d3, %d1
    or.l    (%a0)+, %d2
    add.b   (%a0), %d4
fwd_19:
    ori.l  #0x0000ad09, %d4
    cmp.l   (%a3), %d5
    move.l  #0x0000b995, %d5
    pack    %d5, %d3, #0xd415
    moveq   #18, %d3
    ori.l  #0x0000c8e7, %d2
    move.l  0x00108604, %d2
    tst.l   (72,%a2)
    cmp.l   %d4, %d0
    move.l  #0x89abcd10, %d1
    clr.b   %d1
    slt     %d1
    move.l  #0x80000001, %d0
    andi.l  #0x0000003f, %d3  | dynamic count in 0..63
    asl.l   %d3, %d0
    ble     shift_v_done_fa18
    nop
shift_v_done_fa18:
    addq.w  #5, (0,%a3)
    tst.l   (56,%a1)
    lea     0x00100000, %a4
    adda.l  (%a2), %a4
    lea     0x00100000, %a6
    adda.l  (96,%a2), %a6
    lea     0x00100000, %a4
    adda.w  (188,%a0), %a4
    moveq   #2, %d2
_pcidxfb_shape_20:
    .word   0x163b, 0x2320, 0x003c
    bra     _pcidxfb_after_21
    .space  0x34, 0
    .byte   0x58, 0x00, 0xb5, 0x00, 0x7f, 0x00, 0x89, 0x00
    .align  2
_pcidxfb_after_21:
    muls.l  %d2, %d3
    ror.l  #6, %d1
    move.b  #0xce, (160,%a1)
    lsr.l  #8, %d0
    move.l  %d4, (184,%a2)
    move.l  (%a1)+, %d1
    moveq   #0, %d3
    add.w   (%a2)+, %d3
    moveq   #-126, %d5
    bgt    fwd_22
    movep.l %d2, 402(%a1)
fwd_22:
    cmp.l   %d4, %d4
    bfset   %d3{%d3:23}
    cmp.l   -(%a1), %d2
    cmp.l   %d2, %d0
    lea     0x0010fb1c, %a4
    move.l  %d1, 0x00105244
    lea     0x00100000, %a4
    adda.l  -(%a0), %a4
    cmp.l   (%a0)+, %d1
    mulu.l  %d0, %d0
    bne    fwd_23
    bfclr   %d0{27:3}
fwd_23:
    addq.l  #7, %d1
    and.l   (%a0)+, %d0
    move.l  %d2, %d1
    move.l  %d1, %d5
    move.l  %d5, %d0
    move.l  %d0, %d3
    move.l  %d3, %d4
    move.l  %d4, %d6
    lea     0x0010b00c, %a6
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (888,%a4), %a1
    lea     (1124,%a4), %a0
    moveq   #16, %d2
    move.l  #0xdeadbeef, (16,%a1)
    move.l  #0x00000000, (16,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    ble    fwd_24
    asr.l  %d4, %d1
fwd_24:
    bls    fwd_25
    or.l    (%a2)+, %d0
    movea.l %a2, %a5
    move.l  %d4, %d1
    lea     (232,%a0), %a4
    add.w   %d5, (%a4)+
fwd_25:
    sub.w   %d5, (36,%a0)
    moveq   #-86, %d5
    lea     sub_26-16, %a4
    jsr     16(%a4)
    and.l   (%a2), %d5
    tst.l   %d1
    bne    fwd_27
    move.l  #0x00000002, %d4
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d4
    bgt     shift_v_done_e966
    nop
shift_v_done_e966:
    subi.l  #0x00006bba, %d2
    shi     (48,%a1)
    subq.l  #2, %d2
    moveq   #-118, %d1
    moveq   #0, %d2
    lea     (20,%a0), %a4
    neg.w   (%a4)+
fwd_27:
    mulu.l  %d5, %d1
    beq    fwd_28
    ror.w  #4, %d5
fwd_28:
    lea     (196,%a0), %a4
    move.b  #0x33, (%a4)
    moveq   #15, %d1
    btst    %d1, (%a4)
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    or.l    (%a0), %d0
    lea     0x00100000, %a6
    adda.l  (132,%a3), %a6
    and.l   (%a0), %d4
    move.l  (0,%a3), %d3
    lea     (220,%a1), %a5
    move.b  #0x6b, (2,%a5)
    bchg    #13, (2,%a5)
    sub.l   (228,%a1), %d2
    cmp.l   (%a1)+, %d5
    bchg    #27, %d4
    lea     0x00100000, %a6
    adda.l  (44,%a2), %a6
    bcc    fwd_29
    move.l  #0x00002f04, %d3
    subi.l  #0x000000c8, %d1
    subi.l  #0x0000d6e2, %d0
    beq    fwd_30
fwd_29:
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #4, %d5
    moveq   #20, %d6
    move.b   (4,%a4,%d5.l*2), (8,%a5,%d6.l*8)
    cmp.l   %d3, %d0
    add.w   (%a3)+, %d2
fwd_30:
    move.l  %d1, %d4
    move.l  #0x0000003b, %d4
    move.l  #0x00000000, %d3
    addi.l  #0x0000ffc1, %d1
    and.l   %d0, %d1
    addq.l  #5, %d5
    add.b   %d4, (%a3)
    or.l    (%a3), %d4
    lea     (480,%a0), %a4
    moveq   #12, %d5
    and.b   (0,%a4,%d5.w*4), %d2
    spl     %d5
    moveq   #3, %d2
    bra     _pcidx_after_32
_pcidx_tbl_31:
    .byte   0xc6, 0x55, 0x3f, 0x00
    .align  2
_pcidx_after_32:
    move.b  _pcidx_tbl_31(%pc,%d2.w), %d3
    andi.l  #0xdeadbeef, %d2
    bge    fwd_33
    bgt    fwd_34
    clr.l   (220,%a3)
    cmpi.l  #0x2994ccd9, %d2
fwd_33:
    asl.l  %d2, %d5
fwd_34:
    move.l  #0x00000003, %d7
    divul.l  %d7, %d1:%d6
    move.l  %d1, (%a1)
    bgt    fwd_35
    add.l   (152,%a0), %d2
    bne    fwd_36
    move.l  #0x00000020, %d2
    move.l  #0x00000057, %d3
    sbcd    %d3, %d2
fwd_35:
    bsr     sub_37
    muls.l  %d4, %d4
    lea     (440,%a0), %a4
    lea     (992,%a0), %a5
    lea     (688,%a0), %a6
    move.l  %a6, (424,%a0)
    move.l  #0xdeadbeef, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    move.l  #0x00001c21, %d3
    eori.w  #0x7cae, %d3
    tst.l   %d3
fwd_36:
    add.l   %d1, (%a1)
    lea     (212,%a0), %a4
    tst.b   (%a4)+
    lea     (488,%a0), %a4
    lea     (920,%a0), %a5
    lea     (520,%a0), %a6
    move.l  %a5, (%a6)
    lea     (920,%a0), %a6
    move.l  #0x74879808, (%a6)
    move.l  #0xcae5dc3e, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1921, 0x0020
    move.l  #0xFFFFFFFF, %d3
    andi.l  #0x0000003f, %d4  | dynamic count in 0..63
    asl.l   %d4, %d3
    blt     shift_v_done_dc2a
    nop
shift_v_done_dc2a:
    lsl.l  #2, %d1
    move.l  %d1, (12,%a3)
    clr.l   (44,%a2)
    bset    #30, %d0
    move.l  %d3, %d4
    cmp.l   %d4, %d5
    bcs    fwd_38
    moveq   #0, %d3
    move.w  (%a2)+, %d3
    subq.l  #2, %a2
    move.l  #0x00000080, %d5
    negx.b   %d5
    addi.l  #0xb2bf1b2d, %d2
    addq.w  #7, %d4
fwd_38:
    mulu.w  (60,%a1), %d2
    moveq   #3, %d0
    move.b  %d2, (7,%a0,%d0.l)
    move.l  #0x00000005, %d7
    divsl.l  %d7, %d5:%d4
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (888,%a4), %a1
    lea     (1136,%a4), %a0
    moveq   #8, %d2
    move.l  #0x03854018, (8,%a1)
    move.l  #0x00000000, (8,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    bset    %d0, %d4
    move.l  #0x00000041, %d0
    move.l  #0x00000079, %d7
    sbcd    %d7, %d0
    rol.l  #2, %d5
    cmp.l   (%a1)+, %d3
    lsl.l  #1, %d4
    move.l  #0x00000036, %d6
    move.l  #0x00000074, %d7
    sbcd    %d7, %d6
    muls.w  %d1, %d4
    cmpi.l  #0x8, (124,%a3)
    lea     (468,%a0), %a4
    lea     (948,%a0), %a5
    lea     (720,%a0), %a6
    move.l  %a6, (452,%a0)
    move.l  #0x00000091, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    and.l   (%a2)+, %d0
    muls.l  #0x00000000, %d1
    ori.l  #0x0000e970, %d3
    muls.w  %d5, %d3
    move.l  #0x00000100, %d0
    move.l  #0x00000101, %d7
    divs.l  %d7, %d0:%d5
    lea     (592,%a0), %a4
    lea     (944,%a0), %a5
    lea     (624,%a0), %a6
    move.l  %a5, (%a6)
    lea     (944,%a0), %a6
    move.l  #0xdeadbeef, (%a6)
    move.l  #0x000000e3, %d7
    move.l  #0x00000000, %d1
    .word   0xDEB4, 0x1925, 0x0020
    add.l   %d1, %d4
    cmpi.l  #0x0000649f, %d4
    and.l   (%a1), %d1
    move.l  %d3, (96,%a2)
    move.l  #0x000000ff, %d7
    divu.w  %d7, %d5
    movea.l #0x000059e2, %a4
    sls     (65,%a0)
    lea     (516,%a0), %a4
    lea     (884,%a0), %a5
    lea     (548,%a0), %a6
    move.l  %a5, (%a6)
    lea     (884,%a0), %a6
    move.l  #0xf5756769, (%a6)
    move.l  #0x000000fd, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1921, 0x0020
    lea     (524,%a0), %a4
    lea     (812,%a0), %a5
    lea     (556,%a0), %a6
    move.l  %a5, (%a6)
    lea     (812,%a0), %a6
    move.l  #0x80000000, (%a6)
    move.l  #0xb80b8e7b, %d2
    move.l  #0x00000000, %d1
    .word   0xD4B4, 0x1921, 0x0020
    or.l    %d5, (%a0)
    tst.l   (%a0)
    bchg    #30, %d2
    moveq   #-8, %d3
    add.l   %d5, %d5   | sets X for chain
    addx.l  %d2, %d4
    addx.l  %d4, %d0
    subx.l  %d1, %d1
    move.l  %d4, %d2
    move.l  %a0, %a3
    adda.l  #944, %a3
    move.l  %a0, %a4
    adda.l  #1224, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x00000c2a, (%a4)
    move.l  #0x0000e0a0, %d3
    moveq   #1, %d3
    .word   0xeff3, 0x34e3, 0x0164, 0x0010
    btst    #31, %d4
    nop
    move.l  #0x89abcd10, %d5
    neg.b   %d5
    spl     %d0
    subi.l  #0x000000dd, %d0
    movep.w 944(%a1), %d1
    lea     (388,%a0), %a4
    lea     (972,%a0), %a5
    lea     (652,%a0), %a6
    move.l  %a6, (372,%a0)
    move.l  #0xffffffff, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    lea     (68,%a0), %a4
    move.l  -(%a4), %d1
    movep.l 790(%a2), %d1
    link    %a6, #-64
    addq.l  #1, %d4
    unlk    %a6
    moveq   #0, %d0
    moveq   #0, %d1
    cmpi.l  #0x5e6117b3, (140,%a2)
    move.l  %d5, %d4
    cmp.l   (104,%a0), %d3
    move.l  %d5, (84,%a2)
    bra    fwd_39
    moveq   #4, %d0
    lea     (1,%a0), %a4
    move.b  (%a4)+, (2,%a2,%d0.l)
    cmpi.l  #0x00000095, %d4
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    sls     %d5
    or.l    (%a2)+, %d1
    move.l  #0x80000000, %d5
    andi.l  #0x0000003f, %d4  | dynamic count in 0..63
    asl.l   %d4, %d5
    bge     shift_v_done_2530
    nop
shift_v_done_2530:
    roxl.l  #7, %d0
    andi.l  #0x000000ed, %d4
    move.l  #0x00FF00FF, %d4
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d4
    ble     shift_v_done_65ee
    nop
shift_v_done_65ee:
    mulu.l  %d2, %d3
fwd_39:
    movep.l 274(%a1), %d0
    moveq   #-26, %d3
    move.l  #0x00000081, %d1
    move.l  #0x00000043, %d4
    abcd    %d4, %d1
    divs.l  #0x00000011, %d0
    add.l   %d0, %d0
    cmp.l   %d0, %d1
    lsr.l  %d2, %d0
    lea     (224,%a0), %a4
    neg.b   (%a4)
    blt    fwd_40
    bclr    #2, %d0
    jmp     jmp_41
fwd_40:
    lea     (368,%a0), %a4
    lea     (544,%a0), %a5
    lea     (352,%a0), %a6
    move.l  %a5, (%a6)
    lea     (544,%a0), %a6
    move.l  #0x000018ce, (%a6)
    .word   0x2034, 0x8161, 0xfff0
jmp_41:
    move.l  %d5, (%a2)
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #0, %d5
    moveq   #12, %d6
    move.l   (0,%a4,%d5.w*1), (4,%a5,%d6.l*1)
    moveq   #0, %d2
    move.w  (%a0)+, %d2
    subq.l  #2, %a0
    lea     (252,%a0), %a4
    move.l  -(%a4), %d4
    subq.l  #1, %d2
    bne     fwd_42
    move.l  #0x7FFFFFFF, %d0
    andi.l  #0x0000003f, %d3  | dynamic count in 0..63
    asl.l   %d3, %d0
    bge     shift_v_done_279f
    nop
shift_v_done_279f:
fwd_42:
    bclr    #8, %d4
    btst    #17, %d1
    subi.l  #0x00002d79, %d0
    moveq   #0, %d2
    move.l  %d0, %d3
    lea     (112,%a1), %a5
    move.b  #0x2b, (12,%a5)
    moveq   #8, %d5
    btst    %d5, (12,%a5)
    move.l  0x00106a04, %d4
    moveq   #1, %d0
    bra     _pcidxw_after_44
_pcidxw_tbl_43:
    .word   0xe0f7, 0xf25f, 0xcda1, 0xaa0a
_pcidxw_after_44:
    move.w  _pcidxw_tbl_43(%pc,%d0.w*2), %d5
    bhi    fwd_45
    move.l  %d2, %d3
    moveq   #2, %d4
    bra     _pcidxw_after_47
_pcidxw_tbl_46:
    .word   0x86cf, 0x107b, 0x9383, 0xa0c7
_pcidxw_after_47:
    move.w  _pcidxw_tbl_46(%pc,%d4.w*2), %d5
fwd_45:
    jmp     jmp_48
    bcc    fwd_49
    cmpi.l  #0xfe85b236, (%a1)
    bgt    fwd_50
    move.l  #0x00000100, %d7
    divu.l  %d7, %d2
jmp_48:
    or.l    (%a3), %d0
fwd_49:
    cmp.l   %d0, %d3
    bls    fwd_51
fwd_50:
    move.l  %d4, %d6
    move.l  %d6, %d2
    move.l  %d2, %d5
    movep.w %d4, 760(%a0)
    move.l  (100,%a2), %d3
    lea     0x00100000, %a4
    adda.w  (12,%a1), %a4
    lea     (20,%a1), %a5
    andi.l  #0x0000180d, (%a5)+
    move.l  #0x0000861f, %d1
fwd_51:
    bftst   %d3{27:6}
    ori.l  #0x9ee14a9d, %d2
    lea     (688,%a0), %a4
    lea     (904,%a0), %a5
    lea     (720,%a0), %a6
    move.l  %a5, (%a6)
    lea     (904,%a0), %a6
    move.l  #0x7fffffff, (%a6)
    .word   0x02B4, 0x0044, 0xBEEF, 0x0164, 0x0020
    sne     %d5
    lea     (52,%a0), %a3
    move.b  #0x10, (%a3)
    btst    #2, (%a3)+
    lea     (128,%a0), %a4
    cmpi.b  #0x6, (%a4)+
    and.l   (%a0), %d1
    tst.l   %d1
    seq     %d2
    add.l   %d2, %d3   | sets X for chain
    addx.l  %d4, %d4
    addx.l  %d0, %d3
    cmpi.l  #0x80000000, %d1
    cmp.l   (%a3), %d2
    scs     %d3
    bcc    fwd_52
    movep.l %d4, 110(%a0)
    lea     0x00100000, %a4
    adda.l  (%a3), %a4
    bhi    fwd_53
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #24, %d5
    moveq   #0, %d6
    move.w   (4,%a4,%d5.l*4), (4,%a5,%d6.l*4)
    lea     (368,%a0), %a4
    lea     (568,%a0), %a5
    lea     (352,%a0), %a6
    move.l  %a5, (%a6)
    lea     (564,%a0), %a6
    move.l  #0x14df4251, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    bcs    fwd_54
    move.l  #0x89abcd10, %d1
    clr.b   %d1
    or.l    (%a2)+, %d3
    move.l  %d2, 0x001032a0
    move.l  #0x00007fff, %d4
    move.l  #0x00008001, %d7
    divs.l  %d7, %d4:%d3
    cmp.l   -(%a0), %d1
    and.l   (%a2)+, %d5
    bhi    fwd_55
fwd_52:
    cmpi.l  #0x00000089, %d3
    subq.l  #2, %d0
    lea     (232,%a0), %a4
    lea     (100,%a1), %a5
    move.l  (%a4), (%a5)+
    lea     0x00100000, %a5
    adda.l  -(%a1), %a5
fwd_53:
    lea     (176,%a0), %a4
    moveq   #12, %d5
    and.b   (8,%a4,%d5.l*8), %d3
    cmp.l   -(%a2), %d4
    smi     %d1
fwd_54:
    nop
    bra    fwd_56
fwd_55:
    movep.w %d2, 12(%a3)
    tst.l   (64,%a3)
    lea     0x00100000, %a4
    adda.l  -(%a3), %a4
    move.l  #0x80000000, %d3
    or.l    (%a1)+, %d0
    lea     (28,%a0), %a4
    move.l  -(%a4), %d4
fwd_56:
    move.l  #0x00003408, %d3
    or.l    (%a1)+, %d0
    move.l  #0xe33385f6, (%a3)
    movea.l (%a3)+, %a6
    move.w  #0x003b, %d4
dbcc_57:
    addq.l  #1, %d3
    dbcc   %d4, dbcc_57
    cmp.l   %d1, %d0
    ble    fwd_58
    movep.l %d1, 240(%a0)
fwd_58:
    move.b  #0x49, (208,%a3)
    move.l  #0x000035dd, %d2
    eori.w  #0x08db, %d2
    tst.l   %d2
    bchg    %d5, %d3
    bgt    fwd_59
    bsr     sub_60
    and.l   %d2, %d5
fwd_59:
    cmp.l   (%a3), %d2
    or.l    (4,%a1), %d3
    lea     0x00100000, %a4
    adda.l  -(%a3), %a4
    add.w   -(%a0), %d2
    lea     (204,%a0), %a4
    neg.b   (%a4)
    bcc    fwd_61
    moveq   #1, %d2
    bra     _pcidxw_after_63
_pcidxw_tbl_62:
    .word   0xdf6f, 0xb868, 0xf9a0, 0xaf41
_pcidxw_after_63:
    move.w  _pcidxw_tbl_62(%pc,%d2.w*2), %d5
    sub.b   (208,%a3), %d3
    cmp.l   (%a2)+, %d4
fwd_61:
    clr.l   (220,%a1)
    bftst   %d3{18:5}
    bne    fwd_64
    bclr    %d5, %d1
fwd_64:
    eor.l   %d1, %d1
    sub.l   (%a0)+, %d5
    tst.l   %d0
    move.w  #0x7b7f, (40,%a2)
    move.l  #0x89abcd10, %d0
    clr.b   %d0
    clr.l   (248,%a1)
    add.l   %d3, %d1
    sub.l   (%a3), %d4
    tst.l   (%a1)
    lea     (4,%a0), %a4
    negx.w   (%a4)+
    moveq   #-99, %d1
    lea     0x00100000, %a6
    adda.l  -(%a0), %a6
    bftst   %d4{26:%d4}
    bge    fwd_65
    move.l  #0x72f17c79, (%a0)
    movea.l (%a0)+, %a4
fwd_65:
    blt    fwd_66
    move.l  #0x0000005b, %d4
    eori.b  #0x00bf, %d4
    tst.l   %d4
    subq.l  #1, %d3
    bne     fwd_67
    beq    fwd_68
    bfffo  %d3{11:12}, %d1
    move.l  (%a0), %d1
    lea     (180,%a1), %a5
    andi.l  #0x00000072, (%a5)+
    lea     0x00100000, %a4
    adda.l  -(%a3), %a4
fwd_66:
    bhi    fwd_69
fwd_67:
    lsl.l  #7, %d4
fwd_68:
    move.l  %d0, %d1
    lsl.l  %d2, %d5
fwd_69:
    move.l  %d1, %d5
    move.l  #0xdeadbeef, %d0
    addi.l  #0x00003b24, %d0
    move.l  %d6, %d1
    move.l  %d1, %d0
    move.l  %d0, %d3
    move.l  %d3, %d4
    move.l  %d4, %d5
    move.l  %d5, %d2
    mulu.w  (%a0), %d1
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #4, %d5
    moveq   #8, %d6
    move.w   (8,%a4,%d5.w*1), (0,%a5,%d6.l*2)
    addq.l  #4, %d2
    bls    fwd_70
    move.l  #0xa5a5a5a5, %d7
    divsl.l  %d7, %d3:%d1
    lea     0x00100000, %a4
    move.l  #0x00008000, %d3
    adda.w  %d3, %a4
fwd_70:
    lea     (100,%a0), %a4
    neg.b   (%a4)+
    move.l  #0x00000003, %d7
    divs.l  %d7, %d3
    nop
    divs.w  #0x7fff, %d0
    and.l   (224,%a2), %d4
    move.l  %d5, 0x00102874
    lea     0x00100000, %a5
    adda.l  (%a2)+, %a5
    addq.b  #3, (248,%a1)
    move.l  #0x00000007, %d5
    move.l  #0x00000100, %d6
    divu.l  %d6, %d5:%d7
    move.l  (168,%a0), %d5
    move.l  %d1, %d0
    move.l  %d0, %d4
    move.l  %d4, %d6
    move.l  %d6, %d2
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (888,%a4), %a1
    lea     (1128,%a4), %a0
    moveq   #4, %d2
    move.l  #0x00000001, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    moveq   #2, %d4
_pcidxfb_shape_71:
    .word   0x123b, 0x4320, 0x003c
    bra     _pcidxfb_after_72
    .space  0x34, 0
    .byte   0x08, 0x00, 0xb9, 0x00, 0x46, 0x00, 0x11, 0x00
    .align  2
_pcidxfb_after_72:
    moveq   #63, %d6
back_73:
    addq.l  #1, %d2
    subq.l  #1, %d6
    bcs     back_73
    moveq   #3, %d6
    tst.l   %d2
    beq    fwd_74
fwd_74:
    and.l   (%a3)+, %d2
    ble    fwd_75
    nop
    lea     (396,%a0), %a4
    lea     (964,%a0), %a5
    lea     (684,%a0), %a6
    move.l  %a6, (380,%a0)
    move.l  #0x00000088, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    tst.l   %d4
fwd_75:
    and.l   %d2, (%a2)
    cmp.l   -(%a1), %d1
    move.l  %d5, (12,%a2)
    move.l  #0x00000001, %d6
    divul.l  %d6, %d1:%d7
    bge    fwd_76
    move.l  #0x00000003, %d5
    move.l  #0x00000032, %d5
    sbcd    %d5, %d5
    asr.l  #3, %d4
    move.l  #0x0000e82f, %d7
    pack    %d7, %d2, #0x0000
fwd_76:
    and.l   (148,%a0), %d3
    bne    fwd_77
    bmi    fwd_78
    move.l  #0x00010000, %d7
    divul.l  %d7, %d3:%d2
    cmp.l   %d0, %d0
fwd_77:
    asl.l  #6, %d1
    move.l  #0xFFFFFFFE, %d3
    andi.l  #0x0000003f, %d2  | dynamic count in 0..63
    asl.l   %d2, %d3
    ble     shift_v_done_0fe1
    nop
shift_v_done_0fe1:
    move.l  %d1, (%a2)
fwd_78:
    lea     (188,%a1), %a5
    move.w  #0x2715, (%a5)+
    move.l  %d0, 0x001034b0
    addq.w  #2, %d3
    or.l    (132,%a2), %d3
    muls.l  #0x00000007, %d4
    move.l  #0x89abcd10, %d2
    neg.b   %d2
    moveq   #3, %d6
back_79:
    addq.l  #1, %d0
    subq.l  #1, %d6
    bpl     back_79
    moveq   #3, %d6
    lea     (340,%a0), %a4
    lea     (688,%a0), %a5
    lea     (324,%a0), %a6
    move.l  %a5, (%a6)
    lea     (688,%a0), %a6
    move.l  #0x088b5a84, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    bclr    #25, %d5
    or.l    (%a1), %d0
    sub.l   %d0, %d5
    bge    fwd_80
fwd_80:
    lea     (520,%a0), %a4
    lea     (836,%a0), %a5
    lea     (552,%a0), %a6
    move.l  %a5, (%a6)
    lea     (836,%a0), %a6
    move.l  #0x0000ecfe, (%a6)
    move.l  #0x29772745, %d1
    .word   0xD2B4, 0x0164, 0x0020
    subq.l  #1, %d1
    moveq   #52, %d4
    bfset   %d2{3:%d3}
    lea     (160,%a0), %a4
    lea     (60,%a1), %a5
    move.l  (%a4), (%a5)+
    move.b  (210,%a0), %d1
    moveq   #18, %d4
    or.l    (%a0)+, %d3
    eori.l  #0x000082ec, %d5
    blt    fwd_81
    muls.w  #0x007f, %d1
fwd_81:
    moveq   #24, %d3
    addi.l  #0x00000001, %d1
    cmp.l   (128,%a2), %d3
    subq.l  #1, %d2
    lea     (156,%a1), %a5
    move.w  #0x65a8, (%a5)+
    move.l  #0x00000017, %d3
    move.l  #0x00000082, %d5
    abcd    %d5, %d3
    add.l   %d1, %d5   | sets X for chain
    addx.l  %d5, %d5
    subx.l  %d4, %d0
    move.l  #0x00000003, %d4
    move.l  #0x00000100, %d7
    divs.l  %d7, %d4:%d0
    cmp.l   (%a2), %d3
    move.l  %d5, %d1
    move.l  %d1, %d0
    move.l  %d0, %d4
    move.l  %d4, %d2
    move.l  %d2, %d3
    moveq   #105, %d3
    or.l    %d2, (%a1)
    beq    fwd_82
    andi.l  #0x00000001, %d2
    move.l  #0x4658a055, %d0
    cmp.l   (%a0), %d3
    lea     0x00100000, %a6
    .word   0xbcf8, 0x1000
fwd_82:
    btst    %d0, %d3
    lea     0x00100000, %a4
    adda.l  (%a1), %a4
    nop
    add.l   %d1, %d5   | sets X for chain
    subx.l  %d3, %d4
    subx.l  %d4, %d1
    addx.l  %d3, %d1
    move.l  %a0, %a1
    adda.l  #960, %a1
    move.l  %a0, %a4
    adda.l  #1160, %a4
    move.l  %a4, 16(%a1)
    move.l  #0xe33212f4, (%a4)
    moveq   #6, %d6
    .word   0xeaf1, 0x2226, 0x0164, 0x0010
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #4, %d5
    moveq   #20, %d6
    move.b   (4,%a4,%d5.l*1), (8,%a5,%d6.w*2)
    tst.l   %d1
    move.l  %d5, %d0
    move.l  %d0, %d6
    move.l  %d6, %d1
    move.l  %d1, %d3
    move.l  %d3, %d2
    move.l  %d3, %d4
    move.l  %d3, (%a3)
    bmi    fwd_83
fwd_83:
    movep.l 504(%a2), %d5
    tst.l   %a1
    bpl    fwd_84
    sub.l   %d2, %d2
    and.l   (%a0), %d1
    add.l   %d2, %d5   | sets X for chain
    subx.l  %d5, %d1
    addx.l  %d2, %d4
fwd_84:
    move.l  (164,%a0), %d5
    bge    fwd_85
    cmp.l   %d0, %d3
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (880,%a4), %a1
    lea     (1048,%a4), %a0
    moveq   #0, %d2
    move.l  #0x00000015, (0,%a1)
    move.l  #0x00000000, (0,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
fwd_85:
    lea     (544,%a0), %a4
    lea     (944,%a0), %a5
    lea     (576,%a0), %a6
    move.l  %a5, (%a6)
    lea     (944,%a0), %a6
    move.l  #0xd16814da, (%a6)
    move.l  #0x65d50f6e, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1925, 0x0020
    moveq   #2, %d0
    lea     (13,%a0), %a4
    move.b  (%a4)+, (1,%a2,%d0.l)
    lsl.l  #6, %d0
    addq.l  #6, %d4
    lea     (384,%a0), %a4
    lea     (1000,%a0), %a5
    lea     (680,%a0), %a6
    move.l  %a6, (368,%a0)
    move.l  #0x5a485e4f, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    cmp.l   -(%a2), %d5
    move.l  #0x00000021, %d5
    move.l  #0x00000044, %d1
    abcd    %d1, %d5
    movep.l -2(%a3), %d1
    move.l  %a0, %a3
    adda.l  #896, %a3
    move.l  %a0, %a4
    adda.l  #1160, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x00000000, (%a4)
    move.l  #0x7fffffff, %d5
    moveq   #3, %d3
    .word   0xeff3, 0x54e3, 0x0164, 0x0010
    bftst   %d4{7:1}
    move.l  %d4, %d1
    lea     (200,%a0), %a4
    move.b  #0x69, (%a4)
    bclr    #14, (%a4)
    move.l  %d3, %d5
    bgt    fwd_86
    lea     0x00100000, %a5
    adda.l  (%a0), %a5
    rol.l  #1, %d1
fwd_86:
    move.l  %d5, %d2
    move.l  %d2, %d0
    move.l  %d0, %d6
    move.w  #0xf290, (240,%a2)
    bra    fwd_87
    movea.l %d3, %a6
    btst    #15, %d3
    lea     (168,%a0), %a4
    add.b   %d2, (%a4)+
    cmpi.l  #0x80000000, (144,%a3)
    or.l    (%a3), %d3
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    lea     (20,%a0), %a4
    move.b  #0x69, (%a4)
    bset    #4, (%a4)
    tst.w   (8,%a1)
    bpl    fwd_88
fwd_87:
    moveq   #90, %d2
fwd_88:
    lea     0x00100000, %a4
    adda.l  -(%a1), %a4
    cmp.l   (108,%a2), %d5
    move.l  #0x00000001, %d3
    eori.b  #0x00f5, %d3
    tst.l   %d3
    move.l  #0x00000007, %d5
    unpk    %d5, %d2, #0xbb7a
    and.l   (224,%a3), %d0
    mulu.l  #0xffffffff, %d3
    moveq   #3, %d0
    move.b  %d1, (1,%a0,%d0.l)
    add.l   %d1, %d4
    lea     (556,%a0), %a4
    lea     (1016,%a0), %a6
    move.l  %a6, (540,%a0)
    move.l  #0xffffffff, %d7
    .word   0x2987, 0x0164, 0xfff0
    tst.l   %a1
    move.l  #0x99722c4a, %d1
    divu.l  #0x00000007, %d3
    or.l    (132,%a2), %d4
    nop
    or.l   %d3, %d2
    beq    fwd_89
    tst.w   %a2
    bmi    fwd_90
fwd_89:
    move.l  #0x89abcd10, %d5
    neg.b   %d5
fwd_90:
    subq.w  #3, %d5
    move.l  %d2, (%a0)
    nop
    subq.l  #3, %d3
    sgt     %d2
    sub.w   -(%a2), %d1
    move.l  %d5, %d5
    move.l  %d3, %d3
    tst.l   %d0
    moveq   #10, %d6
back_91:
    addq.l  #1, %d3
    subq.l  #1, %d6
    blt     back_91
    moveq   #3, %d6
    subq.l  #1, %d5
    bne     fwd_92
    cmpi.b  #0x8e, (168,%a0)
fwd_92:
    spl     %d1
    bls    fwd_93
    lea     0x00100000, %a4
    adda.l  (%a1), %a4
    and.l   (%a3)+, %d3
fwd_93:
    lea     0x00100000, %a6
    adda.l  (%a0), %a6
    ble    fwd_94
    and.l   (%a1)+, %d4
fwd_94:
    addq.l  #1, %d4
    lea     0x00100000, %a5
    adda.l  -(%a3), %a5
    moveq   #0, %d1
    bls    fwd_95
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #20, %d5
    moveq   #4, %d6
    move.b   (4,%a4,%d5.l*4), (4,%a5,%d6.l*8)
fwd_95:
    addi.l  #0xb52b8099, %d3
    subq.w  #5, (4,%a3)
    tst.b   (200,%a1)
    moveq   #0, %d4
    lea     (488,%a0), %a4
    lea     (796,%a0), %a5
    lea     (520,%a0), %a6
    move.l  %a5, (%a6)
    lea     (796,%a0), %a6
    move.l  #0x80000000, (%a6)
    move.l  #0x00000000, %d6
    .word   0xDCB4, 0x0164, 0x0020
    andi.l  #0x00006c08, %d2
    cmp.l   (%a2)+, %d4
    eor.l   %d3, %d3
    move.l  #0x00000075, %d1
    addq.l  #1, %d0
    beq     fwd_96
fwd_96:
    moveq   #0, %d5
    move.l  #0x000000cc, %d3
    unpk    %d3, %d4, #0x0000
    move.l  %a0, %a2
    adda.l  #920, %a2
    move.l  %a0, %a4
    adda.l  #1160, %a4
    move.l  %a4, 16(%a2)
    move.l  #0x4230ed5c, (%a4)
    moveq   #3, %d4
    .word   0xebf2, 0x3907, 0x0164, 0x0010
    sub.b   (%a0), %d0
    addq.l  #5, %d4
    lea     (408,%a0), %a4
    lea     (612,%a0), %a5
    lea     (392,%a0), %a6
    move.l  %a5, (%a6)
    lea     (608,%a0), %a6
    move.l  #0x000093bc, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    moveq   #3, %d3
    bra     _pcidxw_after_98
_pcidxw_tbl_97:
    .word   0xbd13, 0xe8b8, 0x3435, 0x0dc8
_pcidxw_after_98:
    move.w  _pcidxw_tbl_97(%pc,%d3.w*2), %d1
    add.w   (%a0)+, %d1
    add.l   (%a2)+, %d2
    moveq   #11, %d5
    move.l  #0x00FF00FF, %d3
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d3
    ble     shift_v_done_d49b
    nop
shift_v_done_d49b:
    bne    fwd_99
    and.l   (%a2), %d1
    move.l  #0x0000003b, %d2
    move.l  #0x00000044, %d7
    nbcd    %d7
fwd_99:
    muls.l  %d3, %d2
    lea     (184,%a0), %a4
    tst.l   (%a4)+
    bset    %d5, %d0
    lea     (208,%a1), %a5
    move.w  #0x4e54, (%a5)+
    moveq   #28, %d2
    lea     (220,%a1), %a5
    move.b  #0x20, (12,%a5)
    btst    #0, (12,%a5)
    sub.l   %d0, (172,%a2)
    move.l  %d0, %d4
    move.l  %d4, %d1
    move.l  %d1, %d3
    move.l  %d3, %d5
    move.w  #0x8b33, (68,%a2)
    muls.w  %d3, %d4
    cmp.l   -(%a0), %d1
    lea     (81,%a0), %a4
    lea     (133,%a1), %a5
    move.b  (%a4)+, (%a5)+
    lea     0x00100000, %a6
    adda.l  -(%a1), %a6
    lea     (240,%a1), %a5
    move.b  #0x9e, (2,%a5)
    moveq   #0, %d0
    btst    %d0, (2,%a5)
    ror.l  #1, %d3
    cmp.l   %d1, %d1
    lea     (224,%a0), %a4
    neg.l   -(%a4)
    move.l  %d1, %d1
    add.l   %d1, %d0   | sets X for chain
    addx.l  %d4, %d1
    subx.l  %d3, %d3
    subx.l  %d1, %d4
    move.l  #0x000000ff, %d2
    move.l  #0xdeadbeef, %d7
    divu.l  %d7, %d2:%d5
    moveq   #10, %d6
back_100:
    addq.l  #1, %d3
    subq.l  #1, %d6
    bge     back_100
    moveq   #3, %d6
    ror.w  #3, %d1
    cmp.l   (%a3)+, %d0
    move.l  #0x7FFFFFFF, %d2
    andi.l  #0x0000003f, %d0  | dynamic count in 0..63
    asl.l   %d0, %d2
    bgt     shift_v_done_51c3
    nop
shift_v_done_51c3:
    move.w  #0x0003, (60,%a0)
    divs.w  (60,%a0), %d2
    bhi    fwd_101
    nop
    bcs    fwd_102
    move.l  #0x80000000, %d0
    andi.l  #0x0000003f, %d2  | dynamic count in 0..63
    asl.l   %d2, %d0
    ble     shift_v_done_b1bd
    nop
shift_v_done_b1bd:
    beq    fwd_103
    move.l  0x00107f30, %d1
    lea     0x00100000, %a4
    adda.l  (128,%a0), %a4
    lea     (112,%a1), %a5
    move.b  #0x9e, (%a5)+
fwd_101:
    move.l  #0x00000016, %d0
    move.l  #0x00000067, %d0
    sbcd    %d0, %d0
    lea     (236,%a0), %a4
    tst.w   (%a4)+
fwd_102:
    bchg    #9, %d3
    cmp.l   (0,%a0), %d3
fwd_103:
    bpl    fwd_104
    lea     0x0010a064, %a6
    bge    fwd_105
    lea     (172,%a0), %a4
    cmpi.l  #0x298d, (%a4)+
    or.l   %d1, %d0
    or.l    %d3, (%a3)
    move.l  #0x00000040, %d6
    move.l  #0x00000008, %d1
    abcd    %d1, %d6
    lea     (200,%a0), %a4
    tst.w   -(%a4)
    lea     0x00100000, %a6
    adda.l  (200,%a0), %a6
    move.l  #0x0000a792, %d5
fwd_104:
    move.l  %a0, %a2
    adda.l  #992, %a2
    move.l  %a0, %a4
    adda.l  #1272, %a4
    move.l  %a4, 16(%a2)
    move.l  #0xdeadbeef, (%a4)
    .word   0xecf2, 0x5184, 0x0164, 0x0010
    or.l    (28,%a3), %d0
fwd_105:
    move.l  %d1, 0x00108324
    roxl.l  #3, %d1
    lea     (436,%a0), %a4
    lea     (640,%a0), %a5
    lea     (420,%a0), %a6
    move.l  %a5, (%a6)
    lea     (640,%a0), %a6
    move.l  #0xa954701e, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #24, %d5
    moveq   #8, %d6
    move.w   (4,%a4,%d5.l*4), (8,%a5,%d6.l*8)
    cmp.l   (%a0)+, %d2
    move.l  #0x000000ff, %d7
    divu.w  %d7, %d5
    moveq   #-47, %d3
    or.l    (%a0)+, %d1
    subi.l  #0x00000023, %d3
    btst    %d5, %d4
    tst.l   %d5
    lea     0x00100000, %a6
    adda.l  (%a0)+, %a6
    lea     0x00100000, %a4
    adda.l  (%a2)+, %a4
    lea     (336,%a0), %a4
    lea     (632,%a0), %a5
    lea     (320,%a0), %a6
    move.l  %a5, (%a6)
    lea     (632,%a0), %a6
    move.l  #0x00000000, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    lea     0x00100000, %a5
    adda.w  (16,%a3), %a5
    move.l  #0x00000007, %d7
    divsl.l  %d7, %d1:%d5
    move.l  %d3, (212,%a3)
    rol.l  %d3, %d2
    movep.l 138(%a1), %d3
    lea     (12,%a0), %a4
    move.l  -(%a4), %d3
    sgt     %d2
    move.l  #0x80000000, %d3
    or.l   %d1, %d5
    nop
    move.l  %d3, %d1
    move.l  %d1, %d6
    move.l  %d6, %d5
    move.l  %d5, %d4
    move.l  %d4, %d2
    lea     0x00100000, %a5
    adda.l  -(%a2), %a5
    mulu.w  (20,%a3), %d1
    move.l  #0x00000025, %d1
    move.l  #0x00000077, %d6
    abcd    %d6, %d1
    not.l   %d4
    add.l   %d5, %d0   | sets X for chain
    addx.l  %d1, %d4
    addx.l  %d2, %d4
    lea     0x00100000, %a4
    adda.l  (%a1)+, %a4
    moveq   #-84, %d0
    lea     0x00100000, %a5
    adda.l  (136,%a0), %a5
    bchg    %d2, %d4
    lea     (108,%a0), %a4
    move.l  -(%a4), %d4
    moveq   #0, %d0
    lea     (14,%a0), %a4
    move.b  (%a4)+, (1,%a3,%d0.l)
    clr.l   (112,%a0)
    move.l  %d3, (%a1)
    tst.b   (%a3)
    lea     (552,%a0), %a4
    lea     (1020,%a0), %a6
    move.l  %a6, (536,%a0)
    move.l  #0x65805d21, %d7
    .word   0x2987, 0x0164, 0xfff0
    lea     (520,%a0), %a4
    lea     (860,%a0), %a5
    lea     (552,%a0), %a6
    move.l  %a5, (%a6)
    lea     (860,%a0), %a6
    move.l  #0x1f35a02f, (%a6)
    move.l  #0x0000c27a, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1921, 0x0020
    move.l  #0x6f8dc3df, %d3
    cmp.l   (236,%a1), %d5
    move.w  #0x7139, (136,%a0)
    cmp.l   %d2, %d3
    lea     0x00100000, %a4
    adda.l  (%a1), %a4
    moveq   #42, %d1
    nop
    move.l  #0x0000001a, %d1
    ori.b  #0x004c, %d1
    tst.l   %d1
    sub.l   (%a3)+, %d2
    lea     (152,%a1), %a5
    move.b  #0x5c, (2,%a5)
    bclr    #9, (2,%a5)
    sub.l   %d4, %d1
    sub.l   (%a3), %d0
    lea     (180,%a1), %a5
    move.b  #0xb5, (4,%a5)
    bclr    #5, (4,%a5)
    roxl.l  #2, %d2
    lea     (604,%a0), %a4
    lea     (912,%a0), %a5
    lea     (636,%a0), %a6
    move.l  %a5, (%a6)
    lea     (912,%a0), %a6
    move.l  #0x000000a8, (%a6)
    move.l  #0x000000c6, %d0
    .word   0xD1B4, 0x0164, 0x0020
    sub.l   (216,%a2), %d3
    move.l  #0x00000016, %d4
    ori.b  #0x0006, %d4
    tst.l   %d4
    bmi    fwd_106
fwd_106:
    add.l   %d4, %d0
    cmpi.l  #0x80000000, %d3
    move.l  #0x00000030, %d5
    move.l  #0x00000083, %d6
    sbcd    %d6, %d5
    mulu.l  %d1, %d3
    mulu.w  (46,%a2), %d3
    bcs    fwd_107
fwd_107:
    moveq   #1, %d0
    move.b  %d5, (1,%a2,%d0.l)
    move.l  #0x00000060, %d6
    move.l  #0x00000058, %d0
    abcd    %d0, %d6
    scs     %d0
    svc     %d3
    swap    %d0
    or.l    %d3, (%a1)
    lea     (524,%a0), %a4
    lea     (904,%a0), %a5
    lea     (556,%a0), %a6
    move.l  %a5, (%a6)
    lea     (904,%a0), %a6
    move.l  #0xffffffff, (%a6)
    move.l  #0x00004349, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1921, 0x0020
    lea     0x001076c4, %a4
    cmpi.w  #0xba41, (156,%a2)
    move.l  #0x0000da9f, %d1
    pack    %d1, %d1, #0x3030
    bcc    fwd_108
    moveq   #1, %d5
    bra     _pcidx_after_110
_pcidx_tbl_109:
    .byte   0x8c, 0xa7, 0x4a, 0xb0
    .align  2
_pcidx_after_110:
    move.b  _pcidx_tbl_109(%pc,%d5.w), %d2
fwd_108:
    move.l  %d0, (%a0)
    move.w  #0x00ff, (2,%a0)
    divs.w  (2,%a0), %d5
    move.l  #0x1a888c58, %d3
    moveq   #16, %d5
    move.l  %d2, 0x00104d38
    and.l   (160,%a1), %d4
    tst.l   %d2
    bhi    fwd_111
    moveq   #-86, %d5
fwd_111:
    and.l   (%a3), %d3
    divs.w  #0xffff, %d0
    lea     0x00100000, %a4
    .word   0xb9f8, 0x0bb4
    move.l  #0x00007fff, %d4
    move.l  #0x00008001, %d7
    divs.l  %d7, %d4:%d3
    cmp.l   -(%a3), %d4
    moveq   #7, %d0
    lea     (1,%a0), %a4
    move.b  (%a4)+, (0,%a3,%d0.l)
    moveq   #5, %d0
    lea     (4,%a0), %a4
    move.b  (%a4)+, (7,%a3,%d0.l)
    lea     (348,%a0), %a4
    lea     (664,%a0), %a5
    lea     (332,%a0), %a6
    move.l  %a5, (%a6)
    lea     (664,%a0), %a6
    move.l  #0x00000073, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    bmi    fwd_112
fwd_112:
    lea     0x00100000, %a4
    adda.l  (%a1)+, %a4
    move.l  %d1, (224,%a1)
    sub.l   %d3, %d3
    lea     (128,%a0), %a4
    not.b   (%a4)
    bfset   %d3{9:4}
    move.l  #0x7fffffff, %d5
    lea     (52,%a0), %a4
    lea     (208,%a1), %a5
    move.l  (%a4), (%a5)+
    sub.l   %d1, (0,%a1)
    move.l  (100,%a0), %d1
    not.l   %d2
    swap    %d2
    bgt    fwd_113
    sub.l   -(%a0), %d4
fwd_113:
    lea     0x00100000, %a6
    adda.l  (244,%a0), %a6
    eor.l   %d5, %d5
    move.l  %d4, %d0
    move.l  %a0, %a3
    adda.l  #976, %a3
    move.l  %a0, %a4
    adda.l  #1216, %a4
    move.l  %a4, 16(%a3)
    move.l  #0xdab36ae1, (%a4)
    moveq   #3, %d6
    .word   0xe8f3, 0x0987, 0x0164, 0x0010
    lea     (74,%a0), %a4
    lea     (45,%a1), %a5
    move.b  (%a4)+, (%a5)+
    tst.l   (96,%a1)
    and.l   (%a2)+, %d1
    moveq   #2, %d2
    bra     _pcidx_after_115
_pcidx_tbl_114:
    .byte   0x1c, 0x1a, 0xd2, 0x97
    .align  2
_pcidx_after_115:
    move.b  _pcidx_tbl_114(%pc,%d2.w), %d2
    cmpi.l  #0x0000fdd9, %d1
    muls.l  %d3, %d0
    move.l  #0x00000017, %d3
    move.l  #0x00000098, %d0
    abcd    %d0, %d3
    moveq   #2, %d0
_pcidxfb_shape_116:
    .word   0x103b, 0x0320, 0x003c
    bra     _pcidxfb_after_117
    .space  0x34, 0
    .byte   0xc4, 0x00, 0x58, 0x00, 0x0b, 0x00, 0x31, 0x00
    .align  2
_pcidxfb_after_117:
    sub.l   (%a2), %d0
    move.l  #0x00000080, %d1
    negx.b   %d1
    ble    fwd_118
    move.l  #0xdeadbeef, %d5
    move.l  #0x5d5f0feb, (%a2)
    movea.l (%a2)+, %a4
    moveq   #5, %d0
    lea     (6,%a0), %a4
    move.b  (%a4)+, (3,%a2,%d0.l)
fwd_118:
    sub.l   %d1, (56,%a0)
    moveq   #2, %d0
_pcidxfb_shape_119:
    .word   0x163b, 0x0320, 0x003c
    bra     _pcidxfb_after_120
    .space  0x34, 0
    .byte   0x56, 0x00, 0x9b, 0x00, 0xe3, 0x00, 0xcc, 0x00
    .align  2
_pcidxfb_after_120:
    move.l  #0x0000ef31, %d3
    lea     (64,%a0), %a4
    not.w   (%a4)+
    move.l  #0x0000f1af, %d5
    subq.l  #2, (196,%a0)
    bchg    #14, %d5
    addq.l  #7, %d2
    or.l   %d5, %d1
    mulu.l  %d1, %d3
    move.l  (%a0), %d4
    lea     (108,%a0), %a4
    move.b  #0xfb, (%a4)
    btst    #12, (%a4)
    move.l  #0x00000099, %d6
    move.l  #0x00000093, %d6
    sbcd    %d6, %d6
    lea     (416,%a0), %a4
    lea     (640,%a0), %a5
    lea     (400,%a0), %a6
    move.l  %a5, (%a6)
    lea     (640,%a0), %a6
    move.l  #0xb02a8ccc, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    move.l  #0x59907ce6, %d4
    moveq   #-121, %d3
    exg     %d0, %a4
    subq.l  #4, (220,%a0)
    lea     0x00100000, %a5
    adda.w  %a0, %a5
    addi.l  #0x0000e55b, %d0
    cmp.l   %d0, %d5
    movep.l %d0, 56(%a2)
    move.l  %d4, 0x00108994
    lea     (168,%a1), %a5
    move.w  %d3, (%a5)+
    moveq   #0, %d3
    movep.l %d3, 172(%a0)
    move.l  #0x0000f1fb, %d0
    asl.l  %d3, %d4
    eori.l  #0xbcb37b29, %d0
    lea     (56,%a0), %a4
    move.l  -(%a4), %d5
    bra    fwd_121
    cmp.l   -(%a0), %d3
fwd_121:
    move.l  #0x00000001, %d7
    move.l  #0x00010000, %d5
    divu.l  %d5, %d7:%d6
    subi.l  #0x00000065, %d3
    lea     (412,%a0), %a4
    lea     (664,%a0), %a5
    lea     (396,%a0), %a6
    move.l  %a5, (%a6)
    lea     (660,%a0), %a6
    move.l  #0x0000003e, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    link    %a6, #-256
    addq.l  #1, %d1
    unlk    %a6
    link.l  %a6, #8
    subq.l  #1, %d4
    unlk    %a6
    nop
    or.l    (%a2), %d1
    scc     %d1
    lea     (672,%a0), %a4
    lea     (944,%a0), %a5
    lea     (704,%a0), %a6
    move.l  %a5, (%a6)
    lea     (944,%a0), %a6
    move.l  #0x71989d77, (%a6)
    .word   0x02B4, 0x000E, 0x7230, 0x0164, 0x0020
    cmp.l   (228,%a3), %d1
    lea     (76,%a0), %a4
    move.b  #0x7e, (%a4)
    bclr    #6, (%a4)
    move.l  %d0, %d1
    move.l  #0x00000003, %d6
    divsl.l  %d6, %d1:%d7
    add.l   %d2, %d1
    addq.l  #5, %d4
    lea     0x00100000, %a6
    adda.l  -(%a2), %a6
    roxl.l  #3, %d1
    move.w  #0x0021, %d5
dbcc_122:
    addq.l  #1, %d2
    dbmi   %d5, dbcc_122
    addq.b  #6, (204,%a1)
    bfextu  %d0{5:%d1}, %d5
    move.l  %d4, %d0
    move.l  %d3, (16,%a0)
    or.l    (%a1)+, %d4
    lea     (376,%a0), %a4
    lea     (644,%a0), %a5
    lea     (360,%a0), %a6
    move.l  %a5, (%a6)
    lea     (640,%a0), %a6
    move.l  #0x00004ca3, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    eor.l   %d3, %d3
    cmpm.l  (%a0)+, (%a3)+
    bfclr   %d1{18:24}
    move.l  #0x00000005, %d7
    divu.l  %d7, %d1
    move.l  %d5, %d1
    cmp.l   %d0, %d3
    lea     0x00100000, %a4
    move.l  #0x00008000, %d5
    adda.w  %d5, %a4
    move.l  #0x00001450, %d2
    subq.l  #2, %d0
    beq    fwd_123
    st     %d5
    cmp.l   (%a1), %d1
fwd_123:
    and.l   (%a1)+, %d4
    and.l   %d3, %d5
    move.l  %d6, %d5
    move.l  %d5, %d4
    move.l  %d4, %d3
    move.l  %d3, %d2
    bls    fwd_124
    cmpi.l  #0x000046df, (%a2)
fwd_124:
    cmp.l   %d3, %d1
    tst.l   %a3
    eori.l  #0x7e79ea3f, %d0
    move.l  #0x00000057, %d4
    bgt    fwd_125
    cmpi.l  #0x17ca5dd5, %d4
    lea     0x00109e34, %a6
    moveq   #5, %d0
    lea     (0,%a0), %a4
    move.b  (%a4)+, (1,%a2,%d0.l)
    moveq   #3, %d2
_pcidxfb_shape_126:
    .word   0x1a3b, 0x2320, 0x003c
    bra     _pcidxfb_after_127
    .space  0x34, 0
    .byte   0x5e, 0x00, 0x47, 0x00, 0xa6, 0x00, 0x73, 0x00
    .align  2
_pcidxfb_after_127:
    and.l   (%a3), %d0
    mulu.w  %d5, %d3
    lea     (160,%a0), %a4
    moveq   #24, %d5
    and.w   (12,%a4,%d5.w*1), %d4
fwd_125:
    move.l  #0xedae93a5, %d3
    lea     (114,%a0), %a4
    lea     (70,%a1), %a5
    move.b  (%a4)+, (%a5)+
    tst.b   (%a1)
    rol.w  #3, %d2
    lea     (448,%a0), %a4
    moveq   #20, %d5
    and.b   (12,%a4,%d5.l*8), %d3
    add.w   -(%a1), %d0
    btst    #22, %d0
    sub.w   %d5, (84,%a2)
    add.b   (196,%a2), %d2
    lea     (212,%a0), %a4
    tst.b   -(%a4)
    move.l  #0x7FFFFFFF, %d4
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d4
    bge     shift_v_done_d269
    nop
shift_v_done_d269:
    lea     (632,%a0), %a4
    lea     (940,%a0), %a5
    lea     (664,%a0), %a6
    move.l  %a5, (%a6)
    lea     (940,%a0), %a6
    move.l  #0x0000cd9a, (%a6)
    move.l  #0x0000007b, %d0
    move.l  #0x00000000, %d1
    .word   0xD0B4, 0x1925, 0x0020
    bclr    #28, %d3
    lea     (76,%a1), %a5
    move.b  #0x29, (4,%a5)
    moveq   #14, %d4
    btst    %d4, (4,%a5)
    subq.l  #1, %d5
    and.l   (64,%a2), %d5
    link    %a6, #-128
    addq.l  #1, %d3
    unlk    %a6
    lea     (192,%a0), %a4
    moveq   #16, %d5
    and.l   (12,%a4,%d5.l*4), %d1
    bls    fwd_128
    or.l    (%a2)+, %d5
fwd_128:
    move.l  %d4, 0x0010ad74
    blt    fwd_129
    add.b   (%a3), %d1
    move.w  #0x000e, %d4
dbcc_130:
    addq.l  #1, %d2
    dbpl   %d4, dbcc_130
fwd_129:
    bclr    %d5, %d2
    nop
    or.l   %d2, %d2
    lea     (384,%a0), %a4
    lea     (928,%a0), %a5
    lea     (668,%a0), %a6
    move.l  %a6, (368,%a0)
    move.l  #0x0000009d, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    move.l  %d0, (4,%a3)
    movep.w 368(%a3), %d4

_end:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt

sub_8:
    addq.l  #1, %d5
    addq.l  #1, %d1
    rts

sub_26:
    addq.l  #1, %d3
    addq.l  #1, %d1
    addq.l  #1, %d3
    addq.l  #1, %d1
    rts

sub_37:
    addq.l  #1, %d2
    addq.l  #1, %d2
    addq.l  #1, %d4
    addq.l  #1, %d2
    rts

sub_60:
    addq.l  #1, %d3
    addq.l  #1, %d3
    addq.l  #1, %d3
    addq.l  #1, %d1
    rts
