| Auto-generated by gen_program.py --seed 1957614086
    .text
    .org 0

_start:
    lea     0x00080000, %a7   | stack top
    lea     0x00100000, %a0   | A0 data pool
    lea     0x00104000, %a1   | A1 data pool
    lea     0x00108000, %a2   | A2 data pool
    lea     0x0010c000, %a3   | A3 data pool
    moveq   #3, %d6           | D6 = hop counter
    moveq   #0, %d4
    moveq   #0, %d5

    move.l  #0x7fffffff, %d7
    divu.l  %d7, %d3
    move.l  (%a2), %d0
    or.l   %d5, %d5
    roxr.l  #6, %d3
    andi.l  #0x0000001f, %d2
    ori.l   #0x00000001, %d2
    roxr.l  %d2, %d0
    bcc    fwd_1
    or.l   %d5, %d2
fwd_1:
    tst.l   %d1
    asr.l  #7, %d4
    move.l  #0x00000066, %d5
    move.l  #0x00000080, %d6
    sbcd    %d6, %d5
    move.l  #0x00000000, %d4
    cmp.l   %d5, %d2
    bls    fwd_2
back_3:
    sub.l   %d4, %d4
fwd_2:
    and.l   %d0, (%a3)
back_4:
    moveq   #6, %d0
    move.b  %d3, (0,%a2,%d0.l)
    move.l  (%a3), %d0
back_5:
    bchg    #9, %d0
    move.l  (%a1)+, %d4
    cmp.l   (%a1), %d2
back_6:
    eor.l   %d5, %d5
    bfset   %d0{16:%d2}
    eor.l   %d1, %d1
    move.l  #0x00000025, %d2
    move.l  #0x00000088, %d7
    sbcd    %d7, %d2
    move.l  %d0, (152,%a0)
    subi.l  #0x00001ff1, %d1
    move.l  %d5, (188,%a0)
back_7:
    moveq   #0, %d4
dbcc_8:
    addq.l  #1, %d3
    dbge   %d4, dbcc_8
back_9:
    andi.l  #0x0000001f, %d0
    ori.l   #0x00000001, %d0
    ror.l  %d0, %d4
    move.l  (%a2), %d3
    bhi    fwd_10
back_11:
    move.l  0x0010981c, %d0
fwd_10:
    andi.l  #0x0000001f, %d2
    ori.l   #0x00000001, %d2
    lsl.l  %d2, %d1
    movea.l (72,%a3), %a4
    ble    fwd_12
fwd_12:
back_13:
    tst.l   %d0
    bpl    fwd_14
back_15:
    subq.l  #1, %d4
    bne     fwd_16
    move.l  (20,%a0), %d3
fwd_14:
    lea     0x00100000, %a4
    adda.l  (%a0)+, %a4
    cmp.l   %d5, %d2
    bls    fwd_17
fwd_16:
    move.l  #0x00FF00FF, %d1
    andi.l  #0x00000015, %d4  | count in {0..21}
    ori.l   #0x00000001, %d4  | count in 1..21 (avoid 0-preserve-X bug)
    asl.l   %d4, %d1
    bge     shift_v_done_b721
    nop
shift_v_done_b721:
fwd_17:

_end:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt
