| Auto-generated by gen_program.py --seed 999
    .text
    .org 0

_start:
    lea     0x00080000, %a7   | stack top
    lea     0x00100000, %a0   | A0 data pool
    lea     0x00104000, %a1   | A1 data pool
    lea     0x00108000, %a2   | A2 data pool
    lea     0x0010c000, %a3   | A3 data pool
    move.l  #0x000000fb, %d0   | D0 init (B1b)
    move.l  #0x00000001, %d1   | D1 init (B1b)
    move.l  #0x24ca3945, %d2   | D2 init (B1b)
    move.l  #0x00000060, %d3   | D3 init (B1b)
    movea.l #0x00008777, %a4  | A4 init (B1b)
    movea.l #0x00000081, %a5  | A5 init (B1b)
    movea.l #0x00000001, %a6  | A6 init (B1b)
    moveq   #3, %d6           | D6 = hop counter
    moveq   #0, %d4
    moveq   #0, %d5

    tst.l   %d0
    sub.l   (%a1)+, %d1
    lea     0x00100000, %a4
    adda.w  (84,%a3), %a4
    move.l  0x0010bc7c, %d1
    move.l  #0x00000001, %d7
    divsl.l  %d7, %d3:%d0
    move.l  %d5, (%a1)
    cmpi.l  #0x8ad20cd4, (%a1)
    or.l   %d4, %d4
    sub.b   (52,%a0), %d1
    blt    fwd_1
    lea     (564,%a0), %a4
    lea     (916,%a0), %a5
    lea     (596,%a0), %a6
    move.l  %a5, (%a6)
    lea     (916,%a0), %a6
    move.l  #0x00000012, (%a6)
    move.l  #0x80000000, %d0
    move.l  #0x00000000, %d1
    .word   0xD0B4, 0x1921, 0x0020
    bftst   %d2{%d4:%d2}
    movep.l 46(%a3), %d0
    add.l   %d2, %d0
    moveq   #1, %d3
    bra     _pcidxw_after_3
_pcidxw_tbl_2:
    .word   0xde50, 0xcf22, 0x55ad, 0xe7a2
_pcidxw_after_3:
    move.w  _pcidxw_tbl_2(%pc,%d3.w*2), %d2
    lea     0x00100000, %a6
    adda.l  (%a0), %a6
    move.l  #0x0000faf4, %d4
    add.l   %d1, %d2   | sets X for chain
    subx.l  %d4, %d0
    subx.l  %d3, %d3
    lea     (176,%a1), %a5
    andi.l  #0x0000006e, (%a5)+
    moveq   #55, %d5
    move.l  %d2, 0x0010b38c
    and.l   %d3, %d0
    tst.l   %d5
    lea     (148,%a0), %a4
    move.b  #0xcc, (%a4)
    bclr    #0, (%a4)
    move.l  %d4, (%a2)
    and.l   %d1, %d2
fwd_1:
    move.l  0x00106e4c, %d1
    cmpi.l  #0x80000000, (%a1)
    lea     (28,%a0), %a4
    move.b  #0x44, (%a4)
    moveq   #12, %d3
    bset    %d3, (%a4)
    nop
    move.l  #0x00000012, %d4
    move.l  #0x00000091, %d6
    abcd    %d6, %d4
    lea     (52,%a0), %a3
    move.b  #0x1c, (%a3)
    btst    #0, (%a3)
    move.l  #0xf18bb9e0, %d1
    addq.b  #1, (124,%a0)
    bls    fwd_4
    ror.l  #7, %d3
    cmpi.l  #0x0000834f, %d3
    move.l  (244,%a1), %d5
    and.l   %d3, %d5
    clr.w   %d3
fwd_4:
    add.l   %d5, %d0   | sets X for chain
    subx.l  %d0, %d5
    subx.l  %d2, %d0
    subx.l  %d2, %d2
    sub.l   (%a3)+, %d2
    bge    fwd_5
    lea     0x00100000, %a4
    adda.w  %a2, %a4
    moveq   #99, %d1
fwd_5:
    add.l   %d1, %d5
    bcs    fwd_6
    cmpi.w  #0xbdce, (224,%a0)
    lea     (180,%a0), %a4
    cmpi.w  #0x9f38, (%a4)+
    or.l   %d1, %d2
    tst.l   %d4
fwd_6:
    move.l  #0x89abcd10, %d1
    negx.b   %d1
    lea     (216,%a0), %a4
    not.l   -(%a4)
    tst.l   %d4
    beq    fwd_7
    lea     0x00100000, %a6
    adda.l  (%a3), %a6
    divu.w  #0xa5a5, %d2
    add.w   %d2, (%a1)
fwd_7:
    lea     0x00100000, %a5
    adda.w  (44,%a1), %a5
    lea     (452,%a0), %a4
    lea     (776,%a0), %a5
    lea     (484,%a0), %a6
    move.l  %a5, (%a6)
    lea     (776,%a0), %a6
    move.l  #0x0000006a, (%a6)
    move.l  #0x00005f8e, %d1
    .word   0xD2B4, 0x0164, 0x0020
    subq.w  #4, (64,%a2)
    and.l   (4,%a2), %d4
    move.l  #0x00000011, %d7
    divs.l  %d7, %d3
    add.b   (244,%a3), %d1
    lea     (524,%a0), %a4
    lea     (856,%a0), %a5
    lea     (556,%a0), %a6
    move.l  %a5, (%a6)
    lea     (856,%a0), %a6
    move.l  #0x7fffffff, (%a6)
    move.l  #0x000000c8, %d0
    move.l  #0x00000000, %d1
    .word   0xD0B4, 0x1925, 0x0020
    tst.l   %d1
    bpl    fwd_8
fwd_8:
    move.l  #0x00000081, %d5
    move.l  #0x00000032, %d6
    sbcd    %d6, %d5
    move.l  %d5, %d2
    move.l  %d3, %d6
    move.l  %d6, %d2
    move.l  %d2, %d1
    lea     0x00100000, %a5
    adda.l  (%a1), %a5
    move.l  0x0010599c, %d2
    add.l   %d1, %d3   | sets X for chain
    subx.l  %d3, %d4
    addx.l  %d2, %d4
    movea.l 0x0010db3c, %a4
    lea     (4,%a0), %a4
    add.b   %d1, (%a4)+
    move.l  #0x00000032, %d0
    move.l  #0x00000001, %d1
    sbcd    %d1, %d0
    lea     (164,%a0), %a4
    move.l  -(%a4), %d1
    bcc    fwd_9
    moveq   #-72, %d5
    add.l   -(%a0), %d3
fwd_9:
    moveq   #122, %d1
    addi.l  #0x7fffffff, %d2
    cmp.l   -(%a0), %d0
    bpl    fwd_10
    lea     (196,%a1), %a5
    andi.l  #0x00002128, (%a5)+
    moveq   #3, %d1
    bra     _pcidxw_after_12
_pcidxw_tbl_11:
    .word   0x4ec4, 0x9d4e, 0x8f42, 0xcf52
_pcidxw_after_12:
    move.w  _pcidxw_tbl_11(%pc,%d1.w*2), %d2
fwd_10:
    moveq   #0, %d0
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #20, %d5
    moveq   #20, %d6
    move.l   (4,%a4,%d5.l*8), (4,%a5,%d6.l*1)
    move.l  #0x0000e9c9, (%a0)
    movea.l (%a0)+, %a4
    move.l  #0x00000018, %d2
    blt    fwd_13
    muls.l  #0x00000100, %d0
    move.l  #0xfffffffe, %d7
    divul.l  %d7, %d3:%d4
fwd_13:
    move.l  %d3, %d4
    move.l  %d4, %d6
    move.l  %d6, %d0
    move.l  %d0, %d2
    lea     (92,%a0), %a4
    move.b  #0x8f, (%a4)
    btst    #0, (%a4)
    lsl.l  %d0, %d1
    move.l  %d1, %d5
    move.l  #0x00002e5b, %d2
    pack    %d2, %d5, #0x0000
    lea     0x00100000, %a5
    .word   0xbaf9, 0x0010, 0xbd8c
    bhi    fwd_14
    sub.l   -(%a3), %d1
    lea     0x0010a8a8, %a6
    cmp.l   (116,%a2), %d3
    and.l   %d3, %d0
    move.l  #0x00000080, %d1
    negx.b   %d1
fwd_14:
    bgt    fwd_15
    moveq   #-27, %d1
    move.w  #0x0033, %d5
dbcc_16:
    addq.l  #1, %d4
    dbge   %d5, dbcc_16
fwd_15:
    bhi    fwd_17
    moveq   #29, %d1
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (808,%a4), %a1
    lea     (1052,%a4), %a0
    moveq   #4, %d2
    move.l  #0x3926a67d, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    muls.l  %d1, %d0
fwd_17:
    bge    fwd_18
    andi.l  #0x00000012, %d2
    bgt    fwd_19
fwd_18:
    bfclr   %d4{28:16}
    moveq   #3, %d6
back_20:
    addq.l  #1, %d5
    subq.l  #1, %d6
    bmi     back_20
    moveq   #3, %d6
    move.l  #0x00000000, %d2
    move.l  %d0, (44,%a0)
fwd_19:
    nop
    move.l  #0x00000013, %d4
    move.l  #0x00000038, %d0
    sbcd    %d0, %d4
    move.l  %d5, %d1
    mulu.l  %d0, %d2
    cmp.l   -(%a3), %d5
    bcs    fwd_21
    move.l  %d0, %d3
    move.l  %d3, %d6
    move.l  %d6, %d2
    move.l  %d2, %d1
    addi.l  #0x7fffffff, %d5
    lea     (228,%a0), %a4
    tst.b   (%a4)+
    move.l  #0x00007fff, %d2
    move.l  #0x7fffffff, %d7
    divu.l  %d7, %d2:%d1
    lea     (65,%a0), %a4
    lea     (144,%a1), %a5
    move.b  (%a4)+, (%a5)+
    and.l   (%a3)+, %d4
    lea     (88,%a0), %a4
    move.b  #0x80, (%a4)
    bchg    #14, (%a4)
    mulu.l  %d0, %d5
    beq    fwd_22
    lea     0x00100000, %a6
    .word   0xbcf9, 0x0010, 0xa674
    bcs    fwd_23
fwd_21:
    lea     0x00100000, %a4
    adda.l  (%a3)+, %a4
fwd_22:
    ble    fwd_24
    lea     (192,%a0), %a4
    add.l   %d1, (%a4)+
    move.l  #0x00000001, %d4
    move.l  #0x00000007, %d6
    divu.l  %d6, %d4:%d7
    tst.l   %a1
fwd_23:
    move.l  %d2, (%a0)
fwd_24:
    cmp.l   %d1, %d2
    bhi    fwd_25
    moveq   #10, %d6
back_26:
    addq.l  #1, %d3
    subq.l  #1, %d6
    bhi     back_26
    moveq   #3, %d6
fwd_25:
    cmp.l   (216,%a1), %d2
    add.w   %d0, (%a0)
    lea     (112,%a0), %a4
    moveq   #4, %d5
    and.w   (12,%a4,%d5.l*1), %d1
    bls    fwd_27
    eor.l   %d5, %d5
    lea     (24,%a1), %a5
    andi.l  #0x0000c978, (%a5)+
fwd_27:
    lea     0x00100000, %a5
    adda.l  (48,%a2), %a5
    move.w  #0x000c, %d5
dbcc_28:
    addq.l  #1, %d4
    dbmi   %d5, dbcc_28
    bfexts  %d1{%d1:%d4}, %d1
    move.l  #0x00000009, %d6
    move.l  #0x00000083, %d7
    abcd    %d7, %d6
    add.w   -(%a0), %d3
    lea     (144,%a0), %a4
    tst.w   (%a4)+
    move.l  #0x00000012, %d1
    move.l  #0x00000050, %d2
    sbcd    %d2, %d1
    sub.b   -(%a3), %d2
    moveq   #2, %d3
    bra     _pcidxw_after_30
_pcidxw_tbl_29:
    .word   0x1854, 0x0cc6, 0x5183, 0xb47f
_pcidxw_after_30:
    move.w  _pcidxw_tbl_29(%pc,%d3.w*2), %d5
    moveq   #-46, %d3
    move.l  %d1, %d3
    subq.l  #1, %d4
    bne     fwd_31
    move.w  #0x0019, %d4
dbcc_32:
    addq.l  #1, %d3
    dbra   %d4, dbcc_32
fwd_31:
    move.l  #0x00000001, %d5
    negx.b   %d5
    cmp.l   -(%a3), %d3
    addq.l  #6, (56,%a0)
    subq.l  #1, %d3
    move.l  %d0, %d0
    or.l    (%a3)+, %d1
    clr.w   %d4
    tst.l   %d3
    bne    fwd_33
    lea     (500,%a0), %a4
    lea     (820,%a0), %a5
    lea     (532,%a0), %a6
    move.l  %a5, (%a6)
    lea     (820,%a0), %a6
    move.l  #0x000000e6, (%a6)
    move.l  #0x00000a4d, %d3
    move.l  #0x00000000, %d1
    .word   0xD6B4, 0x1921, 0x0020
    tst.l   %d5
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (840,%a4), %a1
    lea     (1148,%a4), %a0
    moveq   #12, %d2
    move.l  #0x000000cc, (12,%a1)
    move.l  #0x00000000, (12,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
fwd_33:
    cmpi.l  #0x0000af5d, %d5
    move.l  #0x00000074, %d7
    move.l  #0x00000063, %d5
    abcd    %d5, %d7
    cmp.l   %d3, %d2
    bra    fwd_34
    link.l  %a6, #-16
    subq.l  #1, %d5
    unlk    %a6
fwd_34:
    sub.b   (%a1), %d0
    btst    #14, %d4
    cmpi.l  #0xdeadbeef, (%a3)
    move.l  #0x00000100, %d5
    move.l  #0x00000101, %d7
    divu.l  %d7, %d5:%d4
    lea     0x00100000, %a6
    adda.l  -(%a3), %a6
    lea     (0,%a1), %a5
    move.w  %d5, (%a5)+
    move.l  %d0, (%a1)
    mulu.w  (60,%a3), %d4
    lea     (460,%a0), %a4
    lea     (652,%a0), %a5
    lea     (444,%a0), %a6
    move.l  %a5, (%a6)
    lea     (652,%a0), %a6
    move.l  #0x000000b4, (%a6)
    .word   0x2034, 0x0164, 0xfff0
    move.l  %d2, 0x0010dce4
    move.l  #0xbda4f1d7, %d0
    nop
    eori.l  #0x000000f2, %d0
    moveq   #0, %d3
    move.w  (%a1)+, %d3
    subq.l  #2, %a1
    divs.w  #0x8000, %d0
    addq.l  #1, %d4
    beq     fwd_35
    move.l  (%a3), %d3
    lea     (200,%a0), %a4
    negx.l   -(%a4)
    sub.l   -(%a1), %d5
    lea     (200,%a0), %a4
    move.b  #0x8a, (%a4)
    bclr    #0, (%a4)
fwd_35:
    bge    fwd_36
    ror.l  #8, %d1
    cmp.l   %d3, %d3
    move.l  %d0, (%a0)
fwd_36:
    bls    fwd_37
fwd_37:
    addq.l  #1, %d1
    beq     fwd_38
    moveq   #1, %d5
    bra     _pcidx_after_40
_pcidx_tbl_39:
    .byte   0x88, 0x76, 0xa8, 0xd5
    .align  2
_pcidx_after_40:
    move.b  _pcidx_tbl_39(%pc,%d5.w), %d4
    bfextu  %d2{23:23}, %d1
fwd_38:
    subq.l  #7, (252,%a1)
    cmp.l   %d3, %d3
    move.l  %a0, %a2
    adda.l  #960, %a2
    move.l  %a0, %a4
    adda.l  #1232, %a4
    move.l  %a4, 16(%a2)
    move.l  #0xdeadbeef, (%a4)
    .word   0xeaf2, 0x200a, 0x0164, 0x0010
    bge    fwd_41
    lea     (239,%a0), %a4
    lea     (220,%a1), %a5
    move.b  (%a4)+, (%a5)+
    btst    #11, %d3
    add.l   %d2, %d4
    or.l    (148,%a2), %d3
    link.l  %a6, #16
    subq.l  #1, %d3
    unlk    %a6
    cmp.l   %d1, %d1
    moveq   #-102, %d5
fwd_41:
    cmpi.l  #0x000000da, %d5
    tst.l   %d5
    beq    fwd_42
    or.l   %d2, %d0
fwd_42:
    move.l  #0x80000000, %d1
    andi.l  #0x0000003f, %d4  | dynamic count in 0..63
    asl.l   %d4, %d1
    blt     shift_v_done_4afa
    nop
shift_v_done_4afa:
    move.l  #0x00000080, %d4
    not.b   %d4
    bcs    fwd_43
fwd_43:
    move.l  0x00103558, %d3
    bcc    fwd_44
    move.l  %d1, 0x0010e6ac
    addq.l  #1, %d3
    beq     fwd_45
    move.l  %d0, 0x00107640
    add.l   %d3, (%a3)
    ble    fwd_46
    move.l  #0x00000000, %d4
    eori.l  #0xbada6ba0, %d1
    move.l  #0x00000000, %d1
    moveq   #3, %d6
back_47:
    addq.l  #1, %d4
    subq.l  #1, %d6
    bge     back_47
    moveq   #3, %d6
    moveq   #1, %d3
    bra     _pcidxw_after_49
_pcidxw_tbl_48:
    .word   0x0628, 0x1f5f, 0x4fc1, 0x7c13
_pcidxw_after_49:
    move.w  _pcidxw_tbl_48(%pc,%d3.w*2), %d1
    move.l  #0x00009ea3, %d4
    or.l    (%a1), %d1
    cmp.l   %d1, %d4
fwd_44:
    bfextu  %d3{26:23}, %d3
    move.l  #0x00000016, %d5
    movep.l 34(%a0), %d1
fwd_45:
    ble    fwd_50
    or.l   %d1, %d1
    and.l   %d1, %d2
    roxl.l  %d4, %d0
fwd_46:
    subq.l  #5, %d3
fwd_50:
    move.w  #0xf40a, (156,%a0)
    move.l  %d6, %d2
    move.l  %d2, %d1
    move.l  %d1, %d5
    move.l  %d5, %d0
    move.l  %d0, %d3
    subq.w  #2, %d0
    lea     0x00100000, %a5
    adda.l  (%a1), %a5
    cmpi.l  #0x0000dcc6, %d4
    bcs    fwd_51
    bclr    #3, %d4
fwd_51:
    move.l  #0x00000097, %d7
    nbcd    %d7
    ext.l   %d0
    move.l  #0x00000019, %d2
    movem.l %d0/%d2/%d6/%a1-%a5, -(%a7)
    lea     0x00100000, %a3
    lea     0x00100100, %a1
    move.l  #0xdead0002, %d0
    lea     0x00100300, %a5
    lea     0x00100400, %a4
    move.l  #0xdead0005, %d2
    lea     0x00100600, %a2
    move.l  #0xdead0007, %d6
    movem.l (%a7)+, %d0/%d2/%d6/%a1-%a5
    movem.l %d0/%d2-%d5/%d7/%a0/%a2/%a5-%a6, -(%a7)
    lea     0x00100000, %a2
    lea     0x00100100, %a5
    move.l  #0xdead0002, %d0
    move.l  #0xdead0003, %d7
    move.l  #0xdead0004, %d3
    move.l  #0xdead0005, %d5
    move.l  #0xdead0006, %d4
    lea     0x00100700, %a6
    move.l  #0xdead0008, %d2
    lea     0x00100900, %a0
    movem.l (%a7)+, %d0/%d2-%d5/%d7/%a0/%a2/%a5-%a6
    bne    fwd_52
    bcs    fwd_53
    lea     (612,%a0), %a4
    lea     (888,%a0), %a5
    lea     (644,%a0), %a6
    move.l  %a5, (%a6)
    lea     (888,%a0), %a6
    move.l  #0x87d56626, (%a6)
    move.l  #0x0000fba4, %d5
    move.l  #0x00000000, %d1
    .word   0xDAB4, 0x1925, 0x0020
fwd_52:
    move.l  #0x00000039, %d2
    unpk    %d2, %d1, #0x0000
    move.l  %d1, %d6
    move.l  %d6, %d0
    move.l  %d0, %d3
    move.l  %d3, %d5
    move.l  %d5, %d4
    sf     (205,%a2)
fwd_53:
    add.l   %d1, %d2   | sets X for chain
    addx.l  %d0, %d3
    subx.l  %d0, %d4
    add.l   %d5, %d0   | sets X for chain
    addx.l  %d0, %d5
    subx.l  %d1, %d5
    addx.l  %d1, %d4
    subq.l  #1, %d2
    bne     fwd_54
    sub.w   (44,%a2), %d2
    movep.l 390(%a0), %d5
fwd_54:
    movem.l %d0-%d7/%a0/%a2-%a6, -(%a7)
    move.l  #0xdead0000, %d0
    move.l  #0xdead0001, %d6
    lea     0x00100200, %a3
    lea     0x00100300, %a4
    lea     0x00100400, %a6
    move.l  #0xdead0005, %d4
    lea     0x00100600, %a0
    lea     0x00100700, %a2
    move.l  #0xdead0008, %d2
    move.l  #0xdead0009, %d7
    move.l  #0xdead000a, %d3
    lea     0x00100b00, %a5
    move.l  #0xdead000c, %d1
    move.l  #0xdead000d, %d5
    movem.l (%a7)+, %d0-%d7/%a0/%a2-%a6
    or.l    (%a2), %d0
    or.l    (%a1)+, %d4
    beq    fwd_55
fwd_55:
    moveq   #2, %d0
    lea     (5,%a0), %a4
    move.b  (%a4)+, (7,%a3,%d0.l)
    bra    fwd_56
fwd_56:
    move.l  %d1, %d5
    lea     0x00100000, %a4
    adda.l  (24,%a0), %a4
    tst.l   %d2
    sub.b   (%a3)+, %d4
    move.l  %d1, %d3
    cmpi.b  #0xc5, (148,%a1)
    nop
    lea     0x00100000, %a6
    adda.l  -(%a1), %a6
    move.l  #0x00000001, %d4
    clr.b   %d4
    subi.l  #0x70c0d5be, %d5
    moveq   #0, %d0
    move.w  (%a1)+, %d0
    subq.l  #2, %a1
    and.l   (%a1), %d1
    lea     (100,%a0), %a4
    cmpi.l  #0x1, (%a4)+
    lea     (496,%a0), %a4
    moveq   #16, %d5
    and.b   (8,%a4,%d5.w*2), %d3
    bge    fwd_57
fwd_57:
    bcs    fwd_58
    subq.l  #1, %d5
    bne     fwd_59
    move.l  #0x00000005, %d3
    move.l  #0x00000006, %d2
    abcd    %d2, %d3
fwd_58:
    move.l  #0xdeadbeef, %d4
    lea     0x00100000, %a6
    adda.l  -(%a2), %a6
fwd_59:
    lea     (172,%a0), %a4
    move.b  #0xf3, (%a4)
    bchg    #8, (%a4)
    muls.l  %d5, %d0
    bne    fwd_60
fwd_60:
    lea     0x00100000, %a5
    adda.w  %a3, %a5
    lea     (372,%a0), %a4
    lea     (636,%a0), %a5
    lea     (356,%a0), %a6
    move.l  %a5, (%a6)
    lea     (636,%a0), %a6
    move.l  #0xffffffff, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    or.l    %d1, (%a3)
    lea     (252,%a0), %a4
    lea     (113,%a1), %a5
    move.b  (%a4)+, (%a5)+
    lea     (600,%a0), %a4
    lea     (976,%a0), %a5
    lea     (632,%a0), %a6
    move.l  %a5, (%a6)
    lea     (976,%a0), %a6
    move.l  #0xc48c1bfe, (%a6)
    .word   0x02B4, 0xB5A3, 0xFEC1, 0x0164, 0x0020
    moveq   #63, %d6
back_61:
    addq.l  #1, %d3
    subq.l  #1, %d6
    bgt     back_61
    moveq   #3, %d6
    lea     0x00100000, %a5
    adda.l  (%a0), %a5
    move.l  %d2, %d0
    tst.l   (%a0)
    lea     (238,%a0), %a4
    lea     (60,%a1), %a5
    move.b  (%a4)+, (%a5)+
    moveq   #4, %d0
    bmi    fwd_62
    bls    fwd_63
    lea     (632,%a0), %a4
    lea     (940,%a0), %a5
    lea     (664,%a0), %a6
    move.l  %a5, (%a6)
    lea     (940,%a0), %a6
    move.l  #0xb6d1b298, (%a6)
    .word   0x02B4, 0x0C14, 0xBEEF, 0x0164, 0x0020
fwd_62:
    and.l   (%a0)+, %d5
fwd_63:
    movep.w %d2, 256(%a0)
    and.l   (%a3)+, %d3
    bra    fwd_64
    lea     (62,%a0), %a4
    lea     (118,%a1), %a5
    move.b  (%a4)+, (%a5)+
    lea     (188,%a0), %a4
    cmpi.w  #0x5eea, (%a4)+
    lea     0x00100000, %a4
    adda.l  (8,%a0), %a4
fwd_64:
    move.l  %d0, (%a0)
    and.l   %d0, (%a0)
    add.w   (%a2)+, %d3
    sub.w   (208,%a3), %d0
    subi.l  #0xffffffff, %d0
    lea     (624,%a0), %a4
    lea     (852,%a0), %a5
    lea     (656,%a0), %a6
    move.l  %a5, (%a6)
    lea     (852,%a0), %a6
    move.l  #0x00000084, (%a6)
    move.l  #0x00000003, %d4
    move.l  #0x00000000, %d1
    .word   0xD8B4, 0x1925, 0x0020
    bchg    %d0, %d3
    add.l   %d3, %d3   | sets X for chain
    subx.l  %d2, %d4
    subx.l  %d5, %d4
    lea     0x0010e2ec, %a4
    move.l  (108,%a1), %d5
    cmp.l   -(%a1), %d1
    move.l  %d4, %d4
    muls.l  %d2, %d1
    mulu.l  %d4, %d5
    lea     (180,%a0), %a4
    tst.w   -(%a4)
    lea     0x00100000, %a6
    adda.w  (96,%a2), %a6
    lea     (92,%a0), %a4
    add.l   %d2, (%a4)+
    movem.l %d4, -(%a7)
    move.l  #0xdead0000, %d4
    movem.l (%a7)+, %d4
    sub.w   (%a3), %d1
    lea     0x00100000, %a4
    adda.w  %a1, %a4
    bra    fwd_65
    moveq   #5, %d0
    move.b  %d3, (0,%a1,%d0.l)
fwd_65:
    addq.l  #1, %d5
    beq     fwd_66
    nop
    tst.l   %d1
    cmpi.l  #0xea947410, %d3
    tst.l   (%a3)
    and.l   %d1, (%a0)
    move.l  #0x0000001b, %d6
    unpk    %d6, %d2, #0x0000
    lea     (444,%a0), %a4
    lea     (636,%a0), %a5
    lea     (428,%a0), %a6
    move.l  %a5, (%a6)
    lea     (636,%a0), %a6
    move.l  #0xffffffff, (%a6)
    .word   0x2034, 0x0164, 0xfff0
fwd_66:
    movep.l -12(%a3), %d5
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    lea     (4,%a0), %a4
    lea     (212,%a1), %a5
    move.l  (%a4), (%a5)+
    move.l  #0x000058cc, %d2
    pack    %d2, %d3, #0x3030
    subi.l  #0x000000af, %d0
    or.l   %d0, %d4
    add.b   (120,%a0), %d1
    move.l  #0x00005de0, %d3
    eori.w  #0xeebe, %d3
    tst.l   %d3
    roxr.l  %d3, %d5
    cmp.l   %d0, %d4
    lea     (120,%a0), %a4
    move.b  #0xde, (%a4)
    bclr    #0, (%a4)
    lea     (40,%a0), %a6
    move.b  #0x83, -1(%a6)
    bset    #3, -(%a6)
    nop
    divs.l  #0x00000001, %d0
    sub.w   (96,%a0), %d0
    btst    %d4, %d1
    cmp.l   (%a3)+, %d4
    tst.b   (40,%a3)
    moveq   #63, %d6
back_67:
    addq.l  #1, %d4
    subq.l  #1, %d6
    blt     back_67
    moveq   #3, %d6
    lea     (112,%a0), %a4
    not.w   (%a4)+
    moveq   #0, %d2
    move.w  (%a1)+, %d2
    subq.l  #2, %a1
    bchg    #4, %d3
    addi.l  #0x000000e8, %d2
    lea     (108,%a0), %a4
    move.l  -(%a4), %d1
    move.l  %d6, %d2
    move.l  %d2, %d0
    move.l  %d0, %d3
    move.l  %d3, %d4
    move.l  %d4, %d5
    move.l  %d5, %d1
    or.l    (%a2), %d0
    bgt    fwd_68
    sub.l   %d3, %d4
fwd_68:
    lea     0x00100000, %a6
    adda.l  (%a2)+, %a6
    ror.l  %d5, %d2
    add.l   %d2, %d4   | sets X for chain
    subx.l  %d5, %d0
    subx.l  %d5, %d5
    lea     (548,%a0), %a4
    lea     (928,%a0), %a5
    lea     (580,%a0), %a6
    move.l  %a5, (%a6)
    lea     (928,%a0), %a6
    move.l  #0x0000005b, (%a6)
    move.l  #0x00000d0c, %d6
    .word   0xDDB4, 0x0164, 0x0020
    move.l  #0x00000001, %d2
    andi.l  #0x0000003f, %d0  | dynamic count in 0..63
    asl.l   %d0, %d2
    blt     shift_v_done_b93d
    nop
shift_v_done_b93d:
    move.l  0x0010fa14, %d5
    cmp.l   (%a1), %d2
    lea     (236,%a0), %a4
    lea     (56,%a1), %a5
    move.l  (%a4), (%a5)+
    and.l   (152,%a1), %d2
    clr.w   %d5
    movep.w 110(%a2), %d3
    move.l  %d1, %d3
    move.w  #0xd531, (4,%a2)
    sub.l   %d0, %d4
    lea     (256,%a0), %a4
    moveq   #20, %d5
    and.w   (4,%a4,%d5.w*8), %d0
    cmp.l   -(%a2), %d3
    muls.w  %d3, %d1
    move.l  #0x123456a5, %d1
    negx.b   %d1
    or.l    (%a2), %d5
    or.l    (%a2), %d1
    lea     sub_69-16, %a4
    jsr     16(%a4)
    bmi    fwd_70
    and.l   %d3, (%a3)
    move.l  0x0010d5f4, %d5
    cmp.l   (%a0), %d1
fwd_70:
    lea     (192,%a0), %a4
    tst.w   (%a4)+
    link    %a6, #-32
    addq.l  #1, %d1
    unlk    %a6
    beq    fwd_71
    move.l  #0x00000097, %d7
    move.l  #0x00000061, %d4
    abcd    %d4, %d7
fwd_71:
    bfextu  %d2{%d4:27}, %d4
    cmpi.l  #0x0000ea27, (%a3)
    add.l   %d1, %d0
    move.l  %d1, %d3
    bchg    %d0, %d1
    movea.l %d5, %a6
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    moveq   #6, %d0
    move.b  %d5, (5,%a3,%d0.l)
    add.l   %d2, %d1
    move.l  #0x00000005, %d4
    move.l  #0x00000093, %d0
    abcd    %d0, %d4
    link.l  %a6, #16
    subq.l  #1, %d2
    unlk    %a6
    movea.l 0x001008cc, %a6
    addq.w  #2, %d4
    cmp.l   (%a0), %d0
    lea     (108,%a1), %a5
    move.w  %d2, (%a5)+
    mulu.w  (16,%a1), %d3
    add.w   %d4, (%a0)
    or.l    (136,%a2), %d3
    subi.l  #0x00000001, %d2
    move.l  (248,%a0), %d2
    move.l  #0x00000001, %d0
    move.l  #0x00000090, %d1
    move.l  #0x00000099, %d2
    sbcd    %d2, %d1
    addq.w  #7, %d4
    moveq   #101, %d1
    lea     (168,%a0), %a4
    move.b  #0xc6, (%a4)
    moveq   #3, %d0
    btst    %d0, (%a4)
    move.l  (212,%a1), %d1
    eori.l  #0x000000d3, %d3
    move.l  %d1, %d0
    move.l  %d0, %d3
    move.l  %d3, %d6
    move.l  %d6, %d4
    move.w  #0x000b, %d5
dbcc_72:
    addq.l  #1, %d3
    dbne   %d5, dbcc_72
    and.l   %d0, (%a2)
    moveq   #38, %d5
    tst.b   (%a2)
    moveq   #8, %d0
    move.b  %d2, (2,%a2,%d0.l)
    movep.w %d0, 622(%a1)
    lea     0x00100000, %a5
    .word   0xbaf9, 0x0010, 0x7654
    move.l  %d0, %d6
    move.l  %d6, %d5
    move.l  %d5, %d2
    move.l  %d2, %d4
    move.l  %d4, %d3
    move.l  %d3, %d1
    blt    fwd_73
    moveq   #90, %d4
fwd_73:
    cmp.l   %d0, %d3
    bgt    fwd_74
    move.l  %d3, %d1
fwd_74:
    sub.b   -(%a0), %d5
    bfclr   %d4{25:31}
    blt    fwd_75
    moveq   #63, %d6
back_76:
    addq.l  #1, %d3
    subq.l  #1, %d6
    bmi     back_76
    moveq   #3, %d6
fwd_75:
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #8, %d5
    moveq   #0, %d6
    move.w   (0,%a4,%d5.w*4), (8,%a5,%d6.l*4)
    and.l   %d2, %d1
    cmp.l   (%a0), %d5
    cmpi.l  #0x00000000, (%a3)
    moveq   #3, %d0
    move.l  #0x0000d1cd, %d5
    lsl.l  %d0, %d1
    lea     (580,%a0), %a4
    lea     (916,%a0), %a5
    lea     (612,%a0), %a6
    move.l  %a5, (%a6)
    lea     (916,%a0), %a6
    move.l  #0x8b3d79fd, (%a6)
    move.l  #0x000000f3, %d4
    move.l  #0x00000000, %d1
    .word   0xD8B4, 0x1921, 0x0020
    cmp.l   (%a0), %d0
    tst.w   (%a0)
    rol.l  %d5, %d0
    moveq   #103, %d3
    and.l   (%a1)+, %d3
    moveq   #10, %d6
back_77:
    addq.l  #1, %d3
    subq.l  #1, %d6
    blt     back_77
    moveq   #3, %d6
    bra    fwd_78
fwd_78:
    move.l  (32,%a0), %d4
    move.l  #0x00000001, %d7
    divsl.l  %d7, %d4:%d6
    divu.l  #0x00000003, %d1
    bra    fwd_79
    subq.l  #1, %d0
    bne     fwd_80
    lea     (232,%a0), %a4
    tst.w   (%a4)+
    cmpi.l  #0x0000006b, %d3
    move.l  #0x00000055, %d5
    move.l  #0x00000054, %d3
    abcd    %d3, %d5
    move.w  #0xa9cd, (240,%a3)
fwd_79:
    sub.b   (%a2), %d4
    add.l   -(%a2), %d1
    blt    fwd_81
    move.l  %a0, %a3
    adda.l  #944, %a3
    move.l  %a0, %a4
    adda.l  #1168, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x0000bfdd, (%a4)
    moveq   #5, %d5
    .word   0xeaf3, 0x3941, 0x0164, 0x0010
    lea     (172,%a0), %a4
    cmpi.w  #0x85d, (%a4)+
fwd_80:
    move.l  %d0, (%a3)
fwd_81:
    cmp.l   (%a3), %d4
    nop
    moveq   #3, %d3
    bra     _pcidxw_after_83
_pcidxw_tbl_82:
    .word   0xdb75, 0xc319, 0xc814, 0xd77f
_pcidxw_after_83:
    move.w  _pcidxw_tbl_82(%pc,%d3.w*2), %d2
    sub.b   %d4, (236,%a0)
    and.l   %d2, %d1
    lea     0x00100000, %a6
    adda.l  -(%a3), %a6
    move.l  %d2, 0x0010e730
    ori.l  #0x80000000, %d3
    bhi    fwd_84
fwd_84:
    move.l  #0x00000084, %d4
    move.l  #0x00000085, %d4
    abcd    %d4, %d4
    bhi    fwd_85
fwd_85:
    lea     (172,%a1), %a5
    move.b  #0x14, (8,%a5)
    bset    #2, (8,%a5)
    move.l  %d4, %d3
    add.b   -(%a3), %d2
    lea     0x00100000, %a4
    adda.l  (0,%a0), %a4
    lea     (596,%a0), %a4
    lea     (844,%a0), %a5
    lea     (628,%a0), %a6
    move.l  %a5, (%a6)
    lea     (844,%a0), %a6
    move.l  #0xf070bfd5, (%a6)
    move.l  #0x8e0b0366, %d3
    move.l  #0x00000000, %d1
    .word   0xD6B4, 0x1921, 0x0020
    moveq   #2, %d0
    move.b  %d3, (8,%a3,%d0.l)
    eori.l  #0x000006f6, %d5
    move.l  %d2, (%a2)
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    bset    #5, %d5
    move.l  0x001024ec, %d3
    move.w  #0x0026, %d5
dbcc_86:
    addq.l  #1, %d2
    dbge   %d5, dbcc_86
    movea.l 0x00107898, %a5
    bfclr   %d1{13:27}
    sls     %d4
    move.l  (%a0), %d1
    lea     (76,%a0), %a4
    scs     (%a4)+
    cmp.l   %d3, %d4
    bhi    fwd_87
    moveq   #10, %d6
back_88:
    addq.l  #1, %d5
    subq.l  #1, %d6
    bcs     back_88
    moveq   #3, %d6
fwd_87:
    add.l   %d4, %d1   | sets X for chain
    subx.l  %d1, %d0
    subx.l  %d2, %d1
    blt    fwd_89
    add.b   (%a0)+, %d1
    nop
    lea     (188,%a0), %a4
    move.b  #0x77, (%a4)
    bset    #8, (%a4)
    mulu.l  %d3, %d3
    jmp     jmp_90
    move.l  #0x80000000, %d2
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d2
    ble     shift_v_done_3f52
    nop
shift_v_done_3f52:
fwd_89:
    bpl    fwd_91
jmp_90:
    move.l  %d4, (120,%a1)
    cmp.l   %d0, %d0
fwd_91:
    movep.l 312(%a0), %d0
    ext.l   %d1
    move.l  (%a2), %d2
    moveq   #0, %d4
    move.w  (%a2)+, %d4
    subq.l  #2, %a2
    move.l  (236,%a3), %d2
    mulu.l  #0x80000000, %d3
    cmp.l   (%a2), %d5
    add.w   (%a3), %d5
    bne    fwd_92
    lea     0x00100000, %a5
    adda.l  (100,%a3), %a5
    btst    #29, %d2
    lea     (460,%a0), %a4
    lea     (1008,%a0), %a6
    move.l  %a6, (444,%a0)
    move.l  #0x00000063, %d7
    .word   0x2987, 0x0164, 0xfff0
    move.l  %d5, 0x00108e6c
    cmpi.l  #0xffffffff, %d2
    move.l  #0x0000001a, %d3
    ori.b  #0x004c, %d3
    tst.l   %d3
    or.l    %d3, (%a1)
    move.l  (%a3), %d4
    muls.l  #0x00000100, %d3
    lea     0x00100000, %a5
    adda.l  -(%a1), %a5
    sub.w   (%a3)+, %d5
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #8, %d5
    moveq   #16, %d6
    move.b   (0,%a4,%d5.w*1), (0,%a5,%d6.l*4)
fwd_92:
    rol.l  #8, %d3
    move.l  0x00108090, %d0
    tst.l   %d1
    addq.l  #6, %d3
    movea.l %a0, %a4
    movea.l %a1, %a5
    lea     (820,%a4), %a1
    lea     (1084,%a4), %a0
    moveq   #4, %d2
    move.l  #0xffffffff, (4,%a1)
    move.l  #0x00000000, (4,%a0)
    .word   0x21b1, 0x2000, 0x2000
    movea.l %a4, %a0
    movea.l %a5, %a1
    move.l  #0xFFFFFFFE, %d4
    andi.l  #0x0000003f, %d5  | dynamic count in 0..63
    asl.l   %d5, %d4
    bgt     shift_v_done_f4b0
    nop
shift_v_done_f4b0:
    eor.l   %d0, %d0
    bra    fwd_93
fwd_93:
    lea     (36,%a0), %a4
    move.b  #0x6a, (%a4)
    bset    #4, (%a4)
    cmpi.l  #0x0000006b, (%a0)
    blt    fwd_94
    move.l  #0x00000097, %d2
    move.l  #0x00000027, %d1
    abcd    %d1, %d2
    moveq   #1, %d1
    bra     _pcidx_after_96
_pcidx_tbl_95:
    .byte   0x95, 0x57, 0x20, 0xf8
    .align  2
_pcidx_after_96:
    move.b  _pcidx_tbl_95(%pc,%d1.w), %d2
fwd_94:
    subi.l  #0x000000ba, %d2
    lea     (200,%a0), %a4
    lea     (164,%a1), %a5
    move.l  (%a4), (%a5)+
    bclr    #15, %d4
    subi.l  #0x000061d9, %d2
    lea     (192,%a0), %a4
    tst.l   -(%a4)
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #8, %d5
    moveq   #8, %d6
    move.w   (4,%a4,%d5.l*8), (8,%a5,%d6.w*4)
    sub.l   %d2, %d2
    movea.l #0x0000009f, %a6
    move.l  %d5, %d5
    lea     (18,%a0), %a4
    lea     (139,%a1), %a5
    move.b  (%a4)+, (%a5)+
    lea     0x00100000, %a5
    adda.w  (228,%a2), %a5
    bpl    fwd_97
    moveq   #2, %d0
    bra     _pcidxw_after_99
_pcidxw_tbl_98:
    .word   0xb480, 0xf7e2, 0xd21f, 0xc06e
_pcidxw_after_99:
    move.w  _pcidxw_tbl_98(%pc,%d0.w*2), %d0
    mulu.l  %d0, %d0
    move.l  #0x00000001, %d4
    addq.l  #2, %d3
    move.l  (28,%a1), %d3
fwd_97:
    mulu.w  %d4, %d4
    link    %a6, #-32
    addq.l  #1, %d5
    unlk    %a6
    lea     (168,%a0), %a4
    tst.l   (%a4)+
    move.l  %d4, %d4
    cmp.l   %d2, %d1
    bhi    fwd_100
    subq.b  #7, (200,%a3)
    clr.w   %d4
    cmp.l   (%a1), %d5
    movep.l -4(%a3), %d3
fwd_100:
    beq    fwd_101
    lea     0x001097f8, %a4
    exg     %d1, %d0
    move.l  %a0, %a3
    adda.l  #912, %a3
    move.l  %a0, %a4
    adda.l  #1200, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x00000033, (%a4)
    moveq   #5, %d4
    .word   0xecf3, 0x1624, 0x0164, 0x0010
    movep.l 74(%a0), %d3
fwd_101:
    tst.l   %d3
    move.l  #0x00000073, %d6
    move.l  #0x00000034, %d1
    sbcd    %d1, %d6
    lea     (132,%a0), %a4
    cmpi.w  #0x690f, (%a4)+
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #0, %d5
    moveq   #20, %d6
    move.l   (8,%a4,%d5.l*8), (8,%a5,%d6.w*8)
    addq.l  #4, %d3
    rol.w  #8, %d4
    link    %a6, #-128
    addq.l  #1, %d1
    unlk    %a6
    move.l  %d5, %d2
    move.l  %d2, %d6
    move.l  %d6, %d4
    moveq   #0, %d5
    move.w  (%a2)+, %d5
    subq.l  #2, %a2
    bls    fwd_102
    moveq   #37, %d4
    lea     (116,%a1), %a5
    move.b  #0x2e, (4,%a5)
    btst    #12, (4,%a5)
fwd_102:
    lea     (160,%a1), %a5
    move.b  #0x56, (%a5)+
    neg.l   %d3
    nop
    lea     0x00100000, %a6
    adda.l  (%a3)+, %a6
    lea     (492,%a0), %a4
    lea     (880,%a0), %a5
    lea     (524,%a0), %a6
    move.l  %a5, (%a6)
    lea     (880,%a0), %a6
    move.l  #0x00000000, (%a6)
    move.l  #0x8ccf7c4f, %d2
    .word   0xD4B4, 0x0164, 0x0020
    lsr.l  %d2, %d0
    bcs    fwd_103
    btst    #4, %d4
    lea     0x00100000, %a4
    adda.w  (232,%a2), %a4
    move.l  #0x89abcd10, %d1
    neg.b   %d1
    muls.w  #0x0002, %d3
fwd_103:
    cmp.l   -(%a3), %d2
    lea     (564,%a0), %a4
    lea     (872,%a0), %a5
    lea     (596,%a0), %a6
    move.l  %a5, (%a6)
    lea     (872,%a0), %a6
    move.l  #0x000047ea, (%a6)
    move.l  #0x00003bcd, %d5
    move.l  #0x00000000, %d1
    .word   0xDAB4, 0x1925, 0x0020
    subq.l  #7, %d4
    asr.l  #4, %d5
    cmp.l   %d1, %d5
    bne    fwd_104
    move.l  (%a1)+, %d3
    lea     (%a0), %a4
    negx.l   (148,%a4)
    subq.l  #1, %d1
    bne     fwd_105
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    bset    %d5, %d5
fwd_104:
    lea     0x00100000, %a5
    adda.l  -(%a2), %a5
    move.l  %d2, 0x00106834
    lea     0x00100000, %a6
    adda.l  (236,%a2), %a6
fwd_105:
    moveq   #10, %d6
back_106:
    addq.l  #1, %d0
    subq.l  #1, %d6
    bgt     back_106
    moveq   #3, %d6
    lea     (532,%a0), %a4
    lea     (944,%a0), %a5
    lea     (564,%a0), %a6
    move.l  %a5, (%a6)
    lea     (944,%a0), %a6
    move.l  #0x00000059, (%a6)
    move.l  #0x00000047, %d3
    move.l  #0x00000000, %d1
    .word   0xD6B4, 0x1925, 0x0020
    bra    fwd_107
    tst.l   %d5
fwd_107:
    move.l  %d2, (16,%a0)
    moveq   #0, %d0
    move.b  %d2, (1,%a3,%d0.l)
    and.l   (%a0), %d0
    move.l  #0x0000001e, (%a2)
    movea.l (%a2)+, %a6
    bgt    fwd_108
    or.l    (%a1)+, %d2
    cmp.l   -(%a3), %d1
    lea     (372,%a0), %a4
    lea     (896,%a0), %a5
    lea     (696,%a0), %a6
    move.l  %a6, (356,%a0)
    move.l  #0x00000032, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    move.l  (%a0), %d4
    sub.l   %d0, %d0
    movep.l 698(%a0), %d2
    lea     (440,%a0), %a4
    lea     (956,%a0), %a5
    lea     (656,%a0), %a6
    move.l  %a6, (424,%a0)
    move.l  #0x0000006f, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
fwd_108:
    link.l  %a6, #-512
    subq.l  #1, %d0
    unlk    %a6
    move.l  #0x00000100, %d4
    move.l  #0xfffffffe, %d6
    divu.l  %d6, %d4:%d7
    move.l  %d3, (112,%a1)
    sub.b   %d2, (120,%a1)
    bfffo  %d4{4:30}, %d4
    addq.l  #3, %d4
    bge    fwd_109
    moveq   #3, %d0
    bra     _pcidx_after_111
_pcidx_tbl_110:
    .byte   0xa5, 0xcc, 0xaa, 0xb2
    .align  2
_pcidx_after_111:
    move.b  _pcidx_tbl_110(%pc,%d0.w), %d2
    cmpi.l  #0x000000a3, (%a2)
    move.l  #0x0000007f, %d7
    divs.w  %d7, %d1
    and.l   %d0, (%a3)
    add.b   (%a1), %d1
fwd_109:
    and.l   (%a2)+, %d1
    neg.l   %d0
    move.l  (%a0)+, %d4
    bra    fwd_112
fwd_112:
    moveq   #63, %d6
back_113:
    addq.l  #1, %d1
    subq.l  #1, %d6
    bls     back_113
    moveq   #3, %d6
    move.l  #0x00000003, %d6
    move.l  #0x00000092, %d6
    sbcd    %d6, %d6
    bls    fwd_114
    move.l  #0x000000c4, %d5
    unpk    %d5, %d2, #0x0000
    lea     (252,%a1), %a5
    move.w  %d1, (%a5)+
    move.l  #0x96ab2f18, %d4
    asl.l  %d5, %d4
    bls    fwd_115
    move.l  %d5, %d3
fwd_114:
    move.l  %a0, %a2
    adda.l  #928, %a2
    move.l  %a0, %a4
    adda.l  #1168, %a4
    move.l  %a4, 16(%a2)
    move.l  #0x7fffffff, (%a4)
    move.l  #0x00000000, %d7
    moveq   #12, %d7
    .word   0xeff2, 0x79c8, 0x0164, 0x0010
fwd_115:
    nop
    move.l  #0x00000080, %d3
    neg.b   %d3
    cmp.l   -(%a1), %d0
    cmp.l   (%a1)+, %d3
    asr.l  %d0, %d2
    link.l  %a6, #8
    subq.l  #1, %d2
    unlk    %a6
    move.l  %d2, (%a3)
    lea     (340,%a0), %a4
    lea     (648,%a0), %a5
    lea     (324,%a0), %a6
    move.l  %a5, (%a6)
    lea     (648,%a0), %a6
    move.l  #0x3e1b955d, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    divu.l  #0xfffffffe, %d2
    add.l   %d4, %d4   | sets X for chain
    addx.l  %d1, %d4
    addx.l  %d3, %d5
    and.l   (%a0), %d4
    lea     0x00100000, %a6
    adda.l  -(%a3), %a6
    cmp.l   (%a0)+, %d0
    moveq   #7, %d0
    lea     (1,%a0), %a4
    move.b  (%a4)+, (7,%a2,%d0.l)
    and.l   %d3, (%a2)
    move.l  #0x00000040, %d7
    nbcd    %d7
    lea     (504,%a0), %a4
    lea     (844,%a0), %a5
    lea     (536,%a0), %a6
    move.l  %a5, (%a6)
    lea     (844,%a0), %a6
    move.l  #0x0000002d, (%a6)
    move.l  #0x4c4f1d64, %d1
    .word   0xD2B4, 0x0164, 0x0020
    add.b   (4,%a3), %d3
    muls.l  %d1, %d3
    tst.l   %d1
    asr.l  #3, %d3
    beq    fwd_116
fwd_116:
    move.l  (236,%a1), %d5
    moveq   #3, %d6
back_117:
    addq.l  #1, %d4
    subq.l  #1, %d6
    bne     back_117
    moveq   #3, %d6
    btst    #6, %d3
    addi.l  #0x000000bf, %d3
    and.l   (%a2)+, %d1
    bchg    %d2, %d3
    sle     %d0
    move.l  #0x00000022, %d2
    move.l  #0x00000051, %d1
    sbcd    %d1, %d2
    add.w   (28,%a0), %d4
    or.l   %d0, %d0
    lea     0x00100000, %a4
    adda.l  (%a2)+, %a4
    move.l  %a0, %a3
    adda.l  #936, %a3
    move.l  %a0, %a4
    adda.l  #1184, %a4
    move.l  %a4, 16(%a3)
    move.l  #0x000000c1, (%a4)
    moveq   #12, %d7
    .word   0xebf3, 0x19c8, 0x0164, 0x0010
    moveq   #1, %d4
    bra     _pcidxw_after_119
_pcidxw_tbl_118:
    .word   0xbd78, 0xb376, 0x18c6, 0x2abd
_pcidxw_after_119:
    move.w  _pcidxw_tbl_118(%pc,%d4.w*2), %d2
    sub.w   (216,%a3), %d1
    lea     0x00100000, %a5
    adda.l  (%a3)+, %a5
    lea     (60,%a0), %a4
    not.l   -(%a4)
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #0, %d5
    moveq   #12, %d6
    move.b   (8,%a4,%d5.l*1), (4,%a5,%d6.l*2)
    moveq   #87, %d1
    and.l   (88,%a0), %d4
    add.l   %d1, %d5
    ble    fwd_120
    cmp.l   (%a0)+, %d0
    moveq   #24, %d0
    add.b   (188,%a0), %d0
fwd_120:
    lea     (224,%a0), %a4
    moveq   #16, %d5
    and.b   (8,%a4,%d5.w*8), %d4
    and.l   %d1, %d1
    lea     (32,%a0), %a4
    lea     (116,%a1), %a5
    move.l  (%a4), (%a5)+
    add.l   (76,%a0), %d4
    or.l    (212,%a3), %d2
    move.l  #0x00000080, %d2
    move.l  #0x00000073, %d5
    abcd    %d5, %d2
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #24, %d5
    moveq   #16, %d6
    move.b   (0,%a4,%d5.l*4), (0,%a5,%d6.l*2)
    and.l   (%a2), %d4
    movep.l 850(%a0), %d3
    muls.w  (52,%a1), %d0
    bcc    fwd_121
    move.l  #0x000000ff, %d3
    move.l  #0x00000101, %d7
    divs.l  %d7, %d3:%d0
    moveq   #-59, %d5
    addq.l  #1, %d4
    beq     fwd_122
    move.l  #0x00000039, %d1
    unpk    %d1, %d5, #0x0000
    tst.l   %d1
    add.l   %d5, %d4
fwd_121:
    bmi    fwd_123
fwd_122:
    lea     (11,%a0), %a4
    lea     (4,%a1), %a5
    move.b  (%a4)+, (%a5)+
fwd_123:
    lea     (212,%a0), %a4
    neg.w   (%a4)+
    add.b   (212,%a3), %d5
    tst.l   %a3
    lea     0x00100000, %a5
    adda.l  (%a1)+, %a5
    move.l  (104,%a3), %d2
    sub.l   %d0, %d3
    cmp.l   %d3, %d1
    bpl    fwd_124
    lea     0x00101f28, %a4
    moveq   #1, %d5
    bra     _pcidxw_after_126
_pcidxw_tbl_125:
    .word   0xa91c, 0xfe89, 0xf5f7, 0x384f
_pcidxw_after_126:
    move.w  _pcidxw_tbl_125(%pc,%d5.w*2), %d5
    move.l  #0x00000024, %d3
    move.l  #0x00000063, %d3
    abcd    %d3, %d3
fwd_124:
    move.b  (44,%a3), %d0
    move.l  (24,%a3), %d2
    move.l  (%a3), %d4
    lea     (656,%a0), %a4
    lea     (964,%a0), %a5
    lea     (688,%a0), %a6
    move.l  %a5, (%a6)
    lea     (964,%a0), %a6
    move.l  #0x00000dc8, (%a6)
    .word   0x02B4, 0xFFFF, 0xEDE1, 0x0164, 0x0020
    move.l  #0x00000065, %d3
    lea     (216,%a0), %a4
    move.l  -(%a4), %d4
    eor.l   %d2, %d2
    lea     (340,%a0), %a4
    lea     (572,%a0), %a5
    lea     (324,%a0), %a6
    move.l  %a5, (%a6)
    lea     (572,%a0), %a6
    move.l  #0x00009a4d, (%a6)
    .word   0x2034, 0x8161, 0xfff0
    move.l  #0xe5ad644e, %d1
    mulu.l  %d1, %d1
    lea     (16,%a0), %a4
    add.b   %d3, (%a4)+
    move.l  %d1, %d5
    bset    #31, %d4
    movep.w %d3, 658(%a2)
    lea     sub_127-4, %a4
    jsr     4(%a4)
    moveq   #-32, %d4
    cmpi.l  #0x00004f38, %d4
    moveq   #12, %d0
    cmp.l   %d3, %d4
    cmpi.l  #0x80000000, (%a2)
    move.l  (228,%a2), %d5
    move.w  #0x000c, %d4
dbcc_128:
    addq.l  #1, %d3
    dble   %d4, dbcc_128
    bfset   %d2{1:19}
    or.l   %d1, %d2
    move.l  (76,%a1), %d1
    sub.l   %d2, %d1
    tst.l   %d5
    lea     (96,%a0), %a4
    lea     (28,%a1), %a5
    move.l  (%a4), (%a5)+
    lea     (160,%a1), %a5
    move.b  #0x5, (%a5)+
    moveq   #5, %d0
    move.b  %d2, (6,%a0,%d0.l)
    move.l  #0x00000001, %d5
    andi.l  #0x0000003f, %d1  | dynamic count in 0..63
    asl.l   %d1, %d5
    blt     shift_v_done_f92e
    nop
shift_v_done_f92e:
    moveq   #4, %d0
    move.b  %d4, (8,%a3,%d0.l)
    lea     0x00100000, %a4
    move.l  #0x00007fff, %d1
    adda.w  %d1, %a4
    and.l   (148,%a3), %d0
    tst.l   %a0
    move.l  (160,%a2), %d4
    move.l  #0x00000052, %d5
    move.l  #0x00000030, %d1
    abcd    %d1, %d5
    link.l  %a6, #-16
    subq.l  #1, %d1
    unlk    %a6
    cmpi.l  #0xee2b3524, (%a1)
    lea     (200,%a0), %a4
    cmpi.b  #0x3a, (%a4)+
    move.l  #0x00000001, %d7
    divsl.l  %d7, %d6:%d4
    bge    fwd_129
    addq.l  #6, %d1
    bfexts  %d5{21:%d0}, %d4
fwd_129:
    lea     (184,%a0), %a4
    lea     (140,%a1), %a5
    move.l  (%a4), (%a5)+
    move.l  %d4, %d5
    subq.l  #4, %d3
    bchg    #25, %d3
    move.l  %d0, %d3
    move.l  %d3, %d2
    move.l  %d2, %d5
    move.l  %d5, %d6
    move.l  (80,%a1), %d0
    cmp.l   (%a3)+, %d2
    cmp.l   %d0, %d5
    bge    fwd_130
    movep.w 958(%a2), %d0
    moveq   #1, %d1
_pcidxfb_shape_131:
    .word   0x163b, 0x1320, 0x003c
    bra     _pcidxfb_after_132
    .space  0x34, 0
    .byte   0x10, 0x00, 0xf1, 0x00, 0xee, 0x00, 0x6c, 0x00
    .align  2
_pcidxfb_after_132:
    sub.l   (152,%a1), %d5
    lea     (244,%a0), %a4
    add.b   %d2, (%a4)+
    moveq   #10, %d6
back_133:
    addq.l  #1, %d0
    subq.l  #1, %d6
    bne     back_133
    moveq   #3, %d6
    lea     (128,%a0), %a4
    lea     (153,%a1), %a5
    move.b  (%a4)+, (%a5)+
fwd_130:
    move.l  %d5, %d4
    move.l  %d4, %d6
    move.l  %d6, %d1
    move.l  %d1, %d0
    asr.l  #6, %d3
    lea     (88,%a1), %a5
    move.b  #0x89, (%a5)+
    lea     (220,%a0), %a4
    neg.b   (%a4)+
    add.b   -(%a2), %d0
    move.l  (152,%a2), %d4
    tst.l   (144,%a3)
    lea     0x00100000, %a5
    adda.l  (%a0)+, %a5
    move.l  #0x00002d17, (%a3)
    movea.l (%a3)+, %a6
    eori.l  #0xffffffff, %d1
    cmp.l   (%a0)+, %d3
    move.l  %d1, 0x00102700
    divu.w  #0x0001, %d3
    cmp.l   (%a3), %d2
    move.l  #0x054f60ca, (%a2)
    movea.l (%a2)+, %a5
    mulu.w  %d5, %d1
    lsr.l  #6, %d0
    scc     %d5
    or.l    (%a1), %d1
    ble    fwd_134
    cmp.l   -(%a2), %d5
    bpl    fwd_135
    bcc    fwd_136
    cmpi.l  #0x00008ee5, (%a3)
fwd_134:
    lea     (444,%a0), %a4
    lea     (916,%a0), %a5
    lea     (652,%a0), %a6
    move.l  %a6, (428,%a0)
    move.l  #0x80000000, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    cmpi.b  #0x5c, (116,%a2)
    moveq   #-110, %d5
    move.l  %d5, %d0
    move.l  %d0, %d4
    move.l  %d4, %d6
    move.l  %d6, %d3
    lea     (376,%a0), %a4
    lea     (960,%a0), %a5
    lea     (676,%a0), %a6
    move.l  %a6, (360,%a0)
    move.l  #0xe9e43bbc, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
fwd_135:
    lsl.l  #6, %d1
    or.l    (172,%a0), %d2
    sgt     %d4
    and.l   (%a0)+, %d1
    move.l  (%a0), %d0
fwd_136:
    move.l  (%a0), %d5
    lea     0x00100000, %a6
    .word   0xbdf9, 0x0010, 0x7dc4
    divu.l  #0x0000000d, %d1
    movep.w %d3, 998(%a1)
    movep.l 262(%a0), %d4
    move.l  #0x0000f5a8, %d4
    pack    %d4, %d1, #0x0000
    eor.l   %d2, %d2
    sub.w   (%a3)+, %d0
    mulu.l  %d4, %d1
    lea     (552,%a0), %a4
    lea     (884,%a0), %a5
    lea     (584,%a0), %a6
    move.l  %a5, (%a6)
    lea     (884,%a0), %a6
    move.l  #0x000010b0, (%a6)
    move.l  #0x80000000, %d6
    .word   0xDDB4, 0x0164, 0x0020
    movep.l 692(%a3), %d4
    eori.l  #0x000000af, %d0
    move.l  %d5, (204,%a2)
    move.l  #0x000057b5, %d4
    moveq   #1, %d2
_pcidxfb_shape_137:
    .word   0x163b, 0x2320, 0x003c
    bra     _pcidxfb_after_138
    .space  0x34, 0
    .byte   0x00, 0x00, 0xfd, 0x00, 0x8c, 0x00, 0xd6, 0x00
    .align  2
_pcidxfb_after_138:
    move.l  %d2, %d0
    link.l  %a6, #-64
    subq.l  #1, %d5
    unlk    %a6
    asl.l  #3, %d3
    bfffo  %d4{4:31}, %d5
    move.l  %d1, %d2
    lea     (564,%a0), %a4
    lea     (972,%a0), %a5
    lea     (596,%a0), %a6
    move.l  %a5, (%a6)
    lea     (972,%a0), %a6
    move.l  #0x00005fb5, (%a6)
    move.l  #0x80000000, %d4
    .word   0xD9B4, 0x0164, 0x0020
    move.l  %d3, (60,%a3)
    bmi    fwd_139
    moveq   #-17, %d1
    move.l  (%a2), %d1
    add.l   -(%a2), %d1
    subq.l  #5, %d5
    lea     0x00100000, %a6
    .word   0xbcf9, 0x0010, 0xa9e0
    move.l  #0x00000075, %d3
    move.l  #0x00000012, %d4
    sbcd    %d4, %d3
    lea     (224,%a0), %a4
    not.w   (%a4)+
fwd_139:
    movea.l %d1, %a5
    cmp.l   (240,%a2), %d4
    move.l  %d3, %d4
    move.l  %d4, %d6
    move.l  %d6, %d2
    move.l  %d2, %d1
    bls    fwd_140
fwd_140:
    bhi    fwd_141
    movep.w %d1, 504(%a2)
    swap    %d0
fwd_141:
    lea     0x00100000, %a6
    adda.l  -(%a0), %a6
    move.l  %d5, (%a1)
    lea     (404,%a0), %a4
    lea     (1004,%a0), %a5
    lea     (676,%a0), %a6
    move.l  %a6, (388,%a0)
    move.l  #0x7fffffff, (%a6)
    .word   0x2AB4, 0x0164, 0xfff0
    subq.l  #5, %d3
    move.l  #0x00000005, %d0
    move.l  #0x00000054, %d0
    abcd    %d0, %d0
    lea     0x00100000, %a6
    adda.l  (%a1), %a6
    movea.l 0x0010ee24, %a5
    mulu.w  %d3, %d0
    tst.b   (140,%a0)
    lea     0x00100000, %a4
    adda.l  (%a3)+, %a4
    beq    fwd_142
    lea     (80,%a0), %a4
    move.l  -(%a4), %d5
    add.l   (%a3), %d5
    lea     (0x40,%a0), %a4
    lea     (0x140,%a0), %a5
    moveq   #20, %d5
    moveq   #24, %d6
    move.w   (8,%a4,%d5.l*4), (4,%a5,%d6.l*4)
    lea     (308,%a0), %a4
    lea     (664,%a0), %a5
    lea     (292,%a0), %a6
    move.l  %a5, (%a6)
    lea     (660,%a0), %a6
    move.l  #0x0000bd4c, (%a6)
    .word   0x2034, 0x8162, 0xfff0
    .word   0xfffc
    lea     0x00100000, %a5
    adda.w  (212,%a1), %a5
    cmp.l   -(%a1), %d2
    and.l   %d0, %d4
    move.l  %d2, 0x0010e324
    lea     0x00100000, %a5
    adda.l  (104,%a3), %a5
    tst.l   %d5
fwd_142:
    move.l  (%a2), %d0
    add.w   %d3, (%a0)
    tst.l   %a0
    subq.l  #2, %d2
    tst.l   %d2
    tst.l   %d0
    bfset   %d0{25:22}
    lea     (148,%a0), %a4
    neg.b   (%a4)+
    divu.l  #0xfffffffe, %d2
    movem.l %d1-%d2/%d4-%d5/%d7/%a0-%a2/%a4-%a5, -(%a7)
    lea     0x00100000, %a1
    move.l  #0xdead0001, %d7
    lea     0x00100200, %a4
    lea     0x00100300, %a5
    lea     0x00100400, %a2
    lea     0x00100500, %a0
    move.l  #0xdead0006, %d5
    move.l  #0xdead0007, %d1
    move.l  #0xdead0008, %d2
    move.l  #0xdead0009, %d4
    movem.l (%a7)+, %d1-%d2/%d4-%d5/%d7/%a0-%a2/%a4-%a5
    bchg    #30, %d0
    move.l  %d6, %d3
    move.l  %d3, %d1
    move.l  %d1, %d2
    bgt    fwd_143
    cmp.l   (%a3), %d1
    lea     0x00100000, %a6
    adda.l  (92,%a0), %a6
    add.b   (%a2)+, %d5
    bmi    fwd_144
    lsl.l  %d2, %d2
    move.l  #0x00000007, %d2
    move.l  #0x00000010, %d2
    abcd    %d2, %d2
    moveq   #3, %d6
back_145:
    addq.l  #1, %d1
    subq.l  #1, %d6
    bhi     back_145
    moveq   #3, %d6
    lsl.l  %d1, %d0
    move.l  (148,%a2), %d4
    move.l  (%a1), %d3
    bmi    fwd_146
    moveq   #2, %d4
    bra     _pcidxw_after_148
_pcidxw_tbl_147:
    .word   0xa481, 0x4af1, 0x8814, 0x0e26
_pcidxw_after_148:
    move.w  _pcidxw_tbl_147(%pc,%d4.w*2), %d1
    move.b  (100,%a0), %d2
    moveq   #2, %d2
    bra     _pcidx_after_150
_pcidx_tbl_149:
    .byte   0x0f, 0x5f, 0xb1, 0xd5
    .align  2
_pcidx_after_150:
    move.b  _pcidx_tbl_149(%pc,%d2.w), %d1
    move.l  %d0, (%a3)
    move.l  %d3, %d5
    lsr.l  #4, %d5
    move.l  #0x00000080, %d2
    clr.b   %d2
    addq.l  #2, (136,%a1)
    move.l  (%a0)+, %d3
fwd_143:
    move.b  (135,%a1), %d0
    move.l  %d2, (%a2)
    move.l  %d0, %d6
    move.l  %d6, %d3
    move.l  %d3, %d1
    lea     (236,%a0), %a4
    lea     (200,%a1), %a5
    move.b  (%a4)+, (%a5)+
    movea.l 0x00101aa0, %a6
    ori.l  #0x74934a66, %d4
fwd_144:
    exg     %d5, %a5
    move.l  #0x00008000, %d7
    divu.w  %d7, %d3
fwd_146:
    move.l  %d2, (156,%a2)
    link    %a6, #-128
    addq.l  #1, %d5
    unlk    %a6
    move.l  %d6, %d0
    move.l  %d0, %d1
    move.l  %d1, %d2
    move.l  %d2, %d4
    move.l  %d4, %d5
    addi.l  #0x0000192c, %d3
    blt    fwd_151
    move.l  #0x00000002, %d1
    move.l  #0x00000003, %d6
    divu.l  %d6, %d1:%d7
    sub.b   %d4, (8,%a0)
    cmp.l   (%a1)+, %d2
    cmp.l   -(%a2), %d0
    move.l  #0x00000031, %d5
    move.l  #0x00000023, %d5
    abcd    %d5, %d5
fwd_151:
    lea     0x00100000, %a6
    adda.w  (208,%a3), %a6
    addq.l  #6, %d0
    moveq   #6, %d0
    lea     (6,%a0), %a4
    move.b  (%a4)+, (8,%a2,%d0.l)
    lea     0x00100000, %a6
    adda.l  -(%a2), %a6
    bhi    fwd_152
    sge     (53,%a3)
    move.l  %d4, %d5
    cmp.l   (%a1)+, %d5
fwd_152:
    cmpi.l  #0xdeadbeef, (%a3)
    bge    fwd_153
    scs     %d5
fwd_153:
    moveq   #86, %d5
    cmp.l   (%a2), %d0
    sub.l   %d3, %d3
    lea     (244,%a1), %a5
    move.w  %d0, (%a5)+
    sub.b   (%a0)+, %d4
    or.l    (168,%a0), %d0
    or.l   %d0, %d4
    mulu.l  #0x00000001, %d5
    mulu.l  %d3, %d5
    moveq   #-16, %d2
    moveq   #0, %d3
    subq.w  #8, %d5
    cmp.l   (220,%a0), %d1
    lea     (528,%a0), %a4
    lea     (824,%a0), %a5
    lea     (560,%a0), %a6
    move.l  %a5, (%a6)
    lea     (824,%a0), %a6
    move.l  #0xfc0fbedf, (%a6)
    move.l  #0x00004a3f, %d6
    move.l  #0x00000000, %d1
    .word   0xDCB4, 0x1921, 0x0020
    tst.l   %d0
    bsr     sub_154
    link.l  %a6, #8
    subq.l  #1, %d0
    unlk    %a6
    moveq   #33, %d3
    lea     (48,%a0), %a4
    moveq   #8, %d5
    and.b   (0,%a4,%d5.l*1), %d0
    lea     (252,%a0), %a4
    lea     (28,%a1), %a5
    move.l  (%a4), (%a5)+
    movea.l 0x00106c68, %a4
    sub.l   (%a2), %d4
    move.l  #0x00000080, %d0
    neg.b   %d0
    bmi    fwd_155
    sub.l   %d1, %d1
    or.l    (%a0), %d2
    tst.l   %d1
    cmpm.l  (%a0)+, (%a2)+
fwd_155:
    bls    fwd_156
fwd_156:
    bra    fwd_157
    bne    fwd_158
    muls.l  %d0, %d2
    subq.b  #5, (12,%a0)
    lea     0x00107830, %a4
    move.l  %a0, %a2
    adda.l  #1000, %a2
    move.l  %a0, %a4
    adda.l  #1160, %a4
    move.l  %a4, 16(%a2)
    move.l  #0x7fffffff, (%a4)
    .word   0xebf2, 0x10d0, 0x0164, 0x0010
    and.l   (156,%a2), %d1
fwd_157:
    move.l  %d2, %d5
    bcs    fwd_159
    move.l  #0x00000090, %d2
    move.l  #0x00000076, %d0
    abcd    %d0, %d2
    beq    fwd_160
    and.l   (%a2)+, %d1
fwd_158:
    lea     (272,%a0), %a4
    moveq   #16, %d5
    and.l   (0,%a4,%d5.w*4), %d3
    subq.w  #8, %d3
    lea     (44,%a1), %a5
    move.b  #0x92, (12,%a5)
    bclr    #10, (12,%a5)
    lea     (60,%a0), %a4
    move.l  -(%a4), %d0
    moveq   #2, %d3
    bra     _pcidxw_after_162
_pcidxw_tbl_161:
    .word   0x8f44, 0xd3d3, 0x1a8f, 0x2c69
_pcidxw_after_162:
    move.w  _pcidxw_tbl_161(%pc,%d3.w*2), %d2
fwd_159:
    move.l  0x00107c78, %d2
    beq    fwd_163
    lea     (144,%a0), %a4
    move.b  #0xe1, (%a4)
    bchg    #9, (%a4)
    bset    #24, %d3
fwd_160:
fwd_163:

_end:
    move.l  #0xC0FFEE00, %d7
    lea     0xFFFF0000, %a1
    move.l  %d7, (%a1)
_halt:
    bra     _halt

sub_69:
    addq.l  #1, %d2
    addq.l  #1, %d4
    rts

sub_127:
    addq.l  #1, %d0
    addq.l  #1, %d3
    addq.l  #1, %d2
    rts

sub_154:
    addq.l  #1, %d1
    addq.l  #1, %d1
    addq.l  #1, %d3
    rts
