// tb_pram_clear_pulse.cpp — PRAM-clear one-shot (vio_boot_ctrl[4]) unit tb
//
// Build/run: make tb-pram-clear-pulse
//
// The DUT is NOT a hand-written mirror of the RTL: it is generated by
// tools/extract_pram_clear_oneshot.py, which lifts the shipped logic out of
// rtl/soc/fpga_top_clocks.vh verbatim between the PRAM_CLEAR_ONESHOT markers.
// So this test cannot drift away from the thing it claims to cover.
//
// What's at stake.  PRAM is battery-backed as of the pram-survives-reset
// change: rtc.v deliberately never clears the array on reset, so Mac OS
// settings persist across reboots the way they do on real silicon.  The
// escape hatch is `pram_clear`, driven from VIO probe-out bit 4 -- and VIO
// probe-outs are LEVEL driven.  rtc.v rewrites all 256 bytes on EVERY clock
// pram_clear is high, so routing the raw level through would mean a bit left
// set (or stranded high by a dropped JTAG link) silently swallows every PRAM
// write the OS makes.  That misreads as "PRAM persistence is broken" rather
// than "the zap is stuck on", which is why the RTL edge-detects it.
//
// Scenarios:
//   1. A rising edge produces exactly one pulse of exactly PULSE_CYCLES.
//   2. A level held high FOREVER still produces only that one pulse, and the
//      output returns low -- the headline property.
//   3. Dropping the level does not itself fire a pulse.
//   4. A fresh low->high re-arms and fires exactly once more.
//   5. A 1-cycle blip is still caught (the JTAG REPL drives a slow
//      level, but nothing should depend on the pulse being long).
//   6. Reset forces the output low and disarms cleanly.
//
// Positive control: scenario 0 asserts the DUT can actually raise its output
// at all.  Without it, a DUT whose output were stuck at 0 would "pass" every
// stuck-high assertion below vacuously.

#include <cstdio>
#include <cstdint>
#include <verilated.h>
#include "Vpram_clear_oneshot_dut.h"

#ifndef PULSE_CYCLES
#define PULSE_CYCLES 8
#endif

static Vpram_clear_oneshot_dut* dut = nullptr;
static int n_pass = 0, n_fail = 0;

static int prev_out = 0;
static long total_high = 0;
static long edges = 0;

static void tick() {
    dut->sys_clk = 0; dut->eval();
    dut->sys_clk = 1; dut->eval();
    if (dut->pulse_out) total_high++;
    if (dut->pulse_out && !prev_out) edges++;
    prev_out = dut->pulse_out;
}

static void ticks(long n) { for (long i = 0; i < n; i++) tick(); }

static void counters_reset() { total_high = 0; edges = 0; }

static void do_reset() {
    dut->platform_resetn = 0;
    dut->jtag_pram_clear = 0;
    ticks(4);
    dut->platform_resetn = 1;
    ticks(4);
    counters_reset();
}

#define CHECK_EQ(name, got, exp) do { \
    if ((long)(got) != (long)(exp)) { \
        printf("  FAIL %s: got %ld, expected %ld\n", \
               name, (long)(got), (long)(exp)); \
        return false; \
    } \
} while(0)

// ─── Scenario 0: positive control — the output can go high at all ──────
static bool test_positive_control_pulse_fires() {
    do_reset();
    dut->jtag_pram_clear = 1;
    ticks(2);
    CHECK_EQ("output actually rises (control)", edges, 1);
    dut->jtag_pram_clear = 0;
    ticks(PULSE_CYCLES + 8);
    return true;
}

// ─── Scenario 1: one rising edge → exactly one pulse of exact width ────
static bool test_single_edge_exact_width() {
    do_reset();
    dut->jtag_pram_clear = 1;
    ticks(2);
    dut->jtag_pram_clear = 0;
    ticks(PULSE_CYCLES * 4 + 32);
    CHECK_EQ("exactly one pulse", edges, 1);
    CHECK_EQ("pulse width", total_high, PULSE_CYCLES);
    CHECK_EQ("output low afterwards", dut->pulse_out, 0);
    return true;
}

// ─── Scenario 2: THE headline property — stuck-high cannot hold it ─────
//
// Simulates the JTAG link dropping with the VIO bit stranded high.  If this
// ever regresses, PRAM would be held permanently cleared and every Mac OS
// PRAM write would vanish.
static bool test_stuck_high_level_does_not_hold() {
    do_reset();
    dut->jtag_pram_clear = 1;       // and never released
    ticks(100000);
    CHECK_EQ("stuck level yields exactly one pulse", edges, 1);
    CHECK_EQ("stuck level pulse is bounded", total_high, PULSE_CYCLES);
    CHECK_EQ("output released despite level still high", dut->pulse_out, 0);
    CHECK_EQ("source really is still asserted", dut->jtag_pram_clear, 1);
    return true;
}

// ─── Scenario 3: dropping the level is not itself a trigger ────────────
static bool test_falling_edge_does_not_fire() {
    do_reset();
    dut->jtag_pram_clear = 1;
    ticks(PULSE_CYCLES * 4 + 32);   // pulse completes while held
    long edges_after_rise = edges;
    CHECK_EQ("one pulse from the rise", edges_after_rise, 1);
    dut->jtag_pram_clear = 0;
    ticks(PULSE_CYCLES * 4 + 32);
    CHECK_EQ("falling edge fires nothing", edges, edges_after_rise);
    CHECK_EQ("still low", dut->pulse_out, 0);
    return true;
}

// ─── Scenario 4: a clean re-arm fires exactly once more ────────────────
static bool test_rearm_fires_once_more() {
    do_reset();
    for (int i = 0; i < 5; i++) {
        dut->jtag_pram_clear = 1;
        ticks(PULSE_CYCLES * 3 + 16);
        dut->jtag_pram_clear = 0;
        ticks(PULSE_CYCLES * 3 + 16);
    }
    CHECK_EQ("five zaps → five pulses", edges, 5);
    CHECK_EQ("five zaps → five pulse-widths", total_high, 5L * PULSE_CYCLES);
    return true;
}

// ─── Scenario 5: a 1-cycle blip still lands a full pulse ───────────────
static bool test_one_cycle_blip_is_caught() {
    do_reset();
    dut->jtag_pram_clear = 1;
    tick();                          // exactly one cycle high
    dut->jtag_pram_clear = 0;
    ticks(PULSE_CYCLES * 4 + 32);
    CHECK_EQ("blip caught", edges, 1);
    CHECK_EQ("blip still gives a full-width pulse", total_high, PULSE_CYCLES);
    return true;
}

// ─── Scenario 6: async reset drops the pulse and re-arms cleanly ───────
static bool test_reset_clears_and_rearms() {
    do_reset();
    dut->jtag_pram_clear = 1;
    ticks(2);
    CHECK_EQ("pulse in flight", dut->pulse_out, 1);

    dut->platform_resetn = 0;        // async reset mid-pulse
    ticks(4);
    CHECK_EQ("reset drops the pulse", dut->pulse_out, 0);
    dut->platform_resetn = 1;
    ticks(4);
    // Source is still high across the reset; because src_q also cleared, the
    // post-reset sample sees a rise and re-fires.  That is fine (a reset is
    // not a state we need PRAM to survive across in the other direction) —
    // what matters is that it is still BOUNDED.
    counters_reset();
    ticks(100000);
    CHECK_EQ("post-reset output is bounded, not stuck", dut->pulse_out, 0);
    if (total_high > (long)PULSE_CYCLES) {
        printf("  FAIL post-reset pulse not bounded: %ld cycles high\n", total_high);
        return false;
    }
    return true;
}

#define RUN(fn) do { \
    bool ok = fn(); \
    if (ok) { printf("[PASS] " #fn "\n"); n_pass++; } \
    else    { printf("[FAIL] " #fn "\n"); n_fail++; } \
} while(0)

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    dut = new Vpram_clear_oneshot_dut;
    printf("PRAM-clear one-shot tb (PULSE_CYCLES=%d, DUT extracted verbatim "
           "from fpga_top_clocks.vh)\n", (int)PULSE_CYCLES);

    RUN(test_positive_control_pulse_fires);
    RUN(test_single_edge_exact_width);
    RUN(test_stuck_high_level_does_not_hold);
    RUN(test_falling_edge_does_not_fire);
    RUN(test_rearm_fires_once_more);
    RUN(test_one_cycle_blip_is_caught);
    RUN(test_reset_clears_and_rearms);

    printf("\n%d/%d scenarios passed.\n", n_pass, n_pass + n_fail);
    dut->final();
    delete dut;
    return (n_fail == 0) ? 0 : 1;
}
